using System.Text.Json;using Microsoft.EntityFrameworkCore;using SenorArroz.Application.Common.Interfaces;using SenorArroz.Application.Common.Models;using SenorArroz.Domain.Enums;
namespace SenorArroz.Application.Common.Services;
public class AgentToolExecutor(IEnumerable<IAgentTool> tools,IApplicationDbContext db):IAgentToolExecutor,IAgentToolCatalog
{
 private readonly Dictionary<string,IAgentTool> registry=tools.ToDictionary(x=>x.Name,StringComparer.OrdinalIgnoreCase);
 public IReadOnlyList<AiToolDefinition> Definitions=>registry.Values.Select(x=>new AiToolDefinition(x.Name,x.Description,x.ParametersSchema)).ToList();
 public IReadOnlyList<AiToolDefinition> All=>Definitions;
 public IReadOnlyList<AiToolDefinition> GetByNames(IEnumerable<string> names){var allowed=names.ToHashSet(StringComparer.OrdinalIgnoreCase);return registry.Values.Where(x=>allowed.Contains(x.Name)).Select(x=>new AiToolDefinition(x.Name,x.Description,x.ParametersSchema)).ToList();}
 public bool ModifiesData(string name)=>registry.TryGetValue(name,out var tool)&&tool.ModifiesData;
 public async Task<AgentToolExecutionResult> ExecuteAsync(string name,AgentToolExecutionContext context,JsonElement arguments,CancellationToken ct){if(!registry.TryGetValue(name,out var tool))return new(false,null,"Herramienta no permitida.","tool_not_allowed");var conversation=await db.WhatsAppConversations.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==context.ConversationId,ct);if(conversation==null)return new(false,null,"Conversación no encontrada.","conversation_not_found");if(conversation.BranchId!=context.BranchId)return new(false,null,"La conversación no pertenece a la sucursal indicada por el contexto interno.","branch_mismatch");if(tool.RequiresAiMode&&conversation.AttentionMode!=WhatsAppAttentionMode.Ai)return new(false,null,"La conversación ya no está siendo atendida por IA.","attention_mode_changed");if(arguments.ValueKind!=JsonValueKind.Object)return new(false,null,"Los argumentos deben ser un objeto JSON.","invalid_arguments");var schema=tool.ParametersSchema;if(schema.TryGetProperty("required",out var required))foreach(var item in required.EnumerateArray()){var property=item.GetString()!;if(!arguments.TryGetProperty(property,out _))return new(false,null,$"Falta el argumento requerido: {property}.","invalid_arguments");}if(schema.TryGetProperty("properties",out var properties)&&schema.TryGetProperty("additionalProperties",out var additional)&&additional.ValueKind==JsonValueKind.False)foreach(var property in arguments.EnumerateObject())if(!properties.TryGetProperty(property.Name,out _))return new(false,null,$"Argumento no permitido: {property.Name}.","invalid_arguments");return await tool.ExecuteAsync(context with{BranchId=conversation.BranchId,PhoneNumber=conversation.PhoneNumber,CustomerId=conversation.CustomerId,AttentionMode=conversation.AttentionMode.ToString()},arguments,ct);}
}
