using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SenorArroz.Application.Common.Interfaces;
using SenorArroz.Application.Common.Models;
using SenorArroz.Application.Options;
using SenorArroz.Domain.Enums;
using SenorArroz.Domain.Services;
namespace SenorArroz.Application.Common.Services;

public class WhatsAppAiOrchestrator(IApplicationDbContext db, IWhatsAppAiMessageClaimer claimer, IAiChatProviderResolver providers, IAgentToolExecutor tools, IWhatsAppAutomaticMessageSender sender, WhatsAppAttentionService attention, IClock clock, IOptions<WhatsAppAiOrchestratorOptions> options, ILogger<WhatsAppAiOrchestrator> logger) : IWhatsAppAiOrchestrator
{
    private readonly WhatsAppAiOrchestratorOptions _o=options.Value;
    private const string Prompt="Eres el asistente de WhatsApp de El Señor Arroz. Responde de forma breve y clara. No inventes productos, precios, disponibilidad ni políticas. Usa las herramientas disponibles cuando necesites información real. Si no puedes resolver la solicitud, indica que un asesor continuará la atención.";
    public async Task<WhatsAppAiProcessingResult> ProcessIncomingMessageAsync(int conversationId,int incomingMessageId,CancellationToken cancellationToken=default)
    {
      using var timeout=CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);timeout.CancelAfter(TimeSpan.FromSeconds(_o.TotalTimeoutSeconds));var ct=timeout.Token;int calls=0,totalTools=0;string? providerName=null,model=null;
      try{
        var claimed=await claimer.TryClaimAsync(conversationId,incomingMessageId,ct);
        if(!claimed)return new(false,true,"Mensaje ya procesado, no pendiente o inválido.",false,false,null,null,0,0,null);
        var message=await db.WhatsAppMessages.AsNoTracking().FirstAsync(x=>x.Id==incomingMessageId,ct);var conversation=await db.WhatsAppConversations.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==conversationId,ct);
        if(conversation==null)return await Ignore(message,"Conversación inexistente.",ct);if(conversation.AttentionMode!=WhatsAppAttentionMode.Ai)return await Ignore(message,$"Modo {conversation.AttentionMode}.",ct);if(message.Type!=WhatsAppMessageType.Text||string.IsNullOrWhiteSpace(message.TextBody))return await Ignore(message,"Tipo no soportado.",ct);
        var setting=await db.BranchAiSettings.AsNoTracking().FirstOrDefaultAsync(x=>x.BranchId==conversation.BranchId&&x.IsActive&&x.IsVerified,ct);if(setting==null)return await Ignore(message,"IA inactiva o no verificada.",ct);providerName=setting.Provider;model=setting.Model;var provider=providers.Resolve(setting.Provider);if(provider==null)return await Transfer(message,conversation,"Proveedor no soportado.",ct,providerName,model,calls,totalTools);
        var history=await db.WhatsAppMessages.AsNoTracking().Where(x=>x.ConversationId==conversationId&&x.Id<=incomingMessageId).OrderByDescending(x=>x.Timestamp).Take(Math.Max(1,setting.MaxContextMessages)).OrderBy(x=>x.Timestamp).Select(x=>new AiChatMessage(x.Direction==WhatsAppMessageDirection.Inbound?"user":"assistant",x.TextBody,null,null)).ToListAsync(ct);var chat=new List<AiChatMessage>{new("system",Prompt)};chat.AddRange(history);
        while(calls<_o.MaxModelCallsPerMessage){if(!await StillAi(conversationId,ct))return await Ignore(message,"La atención cambió durante el procesamiento.",ct);calls++;var response=await GenerateWithRetry(provider,new(model,setting.ApiKey,chat,tools.Definitions,setting.Temperature),ct);if(response.Error!=null&&!response.IsTransientError)return await Transfer(message,conversation,response.Error,ct,providerName,model,calls,totalTools);if(response.ToolCalls.Count==0){if(string.IsNullOrWhiteSpace(response.Text))return await Transfer(message,conversation,"Respuesta vacía del proveedor.",ct,providerName,model,calls,totalTools);if(!await StillAi(conversationId,ct))return await Ignore(message,"La atención cambió antes del envío.",ct);var sent=await sender.SendTextAsync(conversationId,response.Text.Trim(),ct);await Finish(message.Id,sent?WhatsAppAiProcessingStatus.Completed:WhatsAppAiProcessingStatus.Failed,sent?null:"Falló el envío a WhatsApp.",ct);logger.LogInformation("WhatsApp AI completed ConversationId={ConversationId} MessageId={MessageId} Provider={Provider} Model={Model} Calls={Calls} Tools={Tools}",conversationId,incomingMessageId,providerName,model,calls,totalTools);return new(true,false,null,sent,false,providerName,model,calls,totalTools,sent?null:"Falló el envío.");}
          if(response.ToolCalls.Count>_o.MaxToolsPerCall||totalTools+response.ToolCalls.Count>_o.MaxTotalToolCalls)break;chat.Add(new("assistant",response.Text,null,response.ToolCalls));foreach(var call in response.ToolCalls){if(!await StillAi(conversationId,ct))return await Ignore(message,"La atención cambió antes de herramienta.",ct);var result=await tools.ExecuteAsync(call.Name,new(conversationId,conversation.BranchId),call.Arguments,ct);totalTools++;var json=JsonSerializer.Serialize(result);if(json.Length>_o.MaxToolResultCharacters)json=json[.._o.MaxToolResultCharacters];chat.Add(new("tool",json,call.Id));}}
        return await Transfer(message,conversation,"Se alcanzó el límite del ciclo de herramientas.",ct,providerName,model,calls,totalTools);
      }catch(OperationCanceledException){await Finish(incomingMessageId,WhatsAppAiProcessingStatus.Failed,"Timeout controlado.",CancellationToken.None);return new(true,false,null,false,false,providerName,model,calls,totalTools,"Timeout controlado.");}catch(Exception ex){logger.LogError(ex,"WhatsApp AI failed ConversationId={ConversationId} MessageId={MessageId}",conversationId,incomingMessageId);await Finish(incomingMessageId,WhatsAppAiProcessingStatus.Failed,"Error controlado del orquestador.",CancellationToken.None);return new(true,false,null,false,false,providerName,model,calls,totalTools,"Error controlado.");}
    }
    private async Task<AiChatResponse> GenerateWithRetry(IAiChatProvider p,AiChatRequest r,CancellationToken ct){AiChatResponse response=new(null,[],r.Model,null,null,null,true,"Sin respuesta");for(var i=0;i<=_o.TransientRetryCount;i++){response=await p.GenerateAsync(r,ct);if(!response.IsTransientError)return response;if(i<_o.TransientRetryCount)await Task.Delay(TimeSpan.FromMilliseconds(250*(i+1)),ct);}return response;}
    private Task<bool> StillAi(int id,CancellationToken ct)=>db.WhatsAppConversations.AsNoTracking().AnyAsync(x=>x.Id==id&&x.AttentionMode==WhatsAppAttentionMode.Ai,ct);
    private async Task<WhatsAppAiProcessingResult> Ignore(Domain.Entities.WhatsAppMessage m,string reason,CancellationToken ct){await Finish(m.Id,WhatsAppAiProcessingStatus.Ignored,reason,ct);return new(false,true,reason,false,false,null,null,0,0,null);}
    private async Task<WhatsAppAiProcessingResult> Transfer(Domain.Entities.WhatsAppMessage m,Domain.Entities.WhatsAppConversation snapshot,string error,CancellationToken ct,string? provider,string? model,int calls,int used){var c=await db.WhatsAppConversations.FirstAsync(x=>x.Id==snapshot.Id,ct);if(c.AttentionMode==WhatsAppAttentionMode.Ai)attention.RequestHuman(c,null,clock.UtcNow);m=await db.WhatsAppMessages.FirstAsync(x=>x.Id==m.Id,ct);m.AiProcessingStatus=WhatsAppAiProcessingStatus.TransferredToHuman;m.AiProcessingError=error[..Math.Min(1000,error.Length)];m.AiProcessedAt=clock.UtcNow;await db.SaveChangesAsync(ct);return new(true,false,null,false,true,provider,model,calls,used,error);}
    private async Task Finish(int id,WhatsAppAiProcessingStatus status,string? error,CancellationToken ct){var m=await db.WhatsAppMessages.FirstOrDefaultAsync(x=>x.Id==id,ct);if(m==null)return;m.AiProcessingStatus=status;m.AiProcessedAt=clock.UtcNow;m.AiProcessingError=error;await db.SaveChangesAsync(ct);}
}
