using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SenorArroz.Application.Common.Interfaces;
using SenorArroz.Application.Common.Models;
using SenorArroz.Application.Options;
using SenorArroz.Domain.Enums;
using SenorArroz.Domain.Services;
namespace SenorArroz.Application.Common.Services;

public class WhatsAppAiOrchestrator(IApplicationDbContext db, IWhatsAppAiMessageClaimer claimer, IAiChatProviderResolver providers, IAgentToolExecutor tools, IWhatsAppAutomaticMessageSender sender, IWhatsAppNotificationService notifications, IWhatsAppSystemPromptBuilder promptBuilder, WhatsAppAttentionService attention, IClock clock, IOptions<WhatsAppAiOrchestratorOptions> options, ILogger<WhatsAppAiOrchestrator> logger) : IWhatsAppAiOrchestrator
{
    private readonly WhatsAppAiOrchestratorOptions _o=options.Value;
    public async Task<WhatsAppAiProcessingResult> ProcessIncomingMessageAsync(int conversationId,int incomingMessageId,CancellationToken cancellationToken=default)
    {
      using var timeout=CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);timeout.CancelAfter(TimeSpan.FromSeconds(_o.TotalTimeoutSeconds));var ct=timeout.Token;int calls=0,totalTools=0;string? providerName=null,model=null;
      try{
        var claimed=await claimer.TryClaimAsync(conversationId,incomingMessageId,ct);
        if(!claimed)return new(false,true,"Mensaje ya procesado, no pendiente o inválido.",false,false,null,null,0,0,null);
        var message=await db.WhatsAppMessages.AsNoTracking().FirstAsync(x=>x.Id==incomingMessageId,ct);var conversation=await db.WhatsAppConversations.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==conversationId,ct);
        if(conversation==null)return await Ignore(message,"Conversación inexistente.",ct);if(conversation.AttentionMode!=WhatsAppAttentionMode.Ai)return await Ignore(message,$"Modo {conversation.AttentionMode}.",ct);if(message.Type!=WhatsAppMessageType.Text||string.IsNullOrWhiteSpace(message.TextBody))return await Ignore(message,"Tipo no soportado.",ct);
        var setting=await db.BranchAiSettings.AsNoTracking().FirstOrDefaultAsync(x=>x.BranchId==conversation.BranchId&&x.IsActive&&x.IsVerified,ct);if(setting==null)return await Ignore(message,"IA inactiva o no verificada.",ct);providerName=setting.Provider;model=setting.Model;var provider=providers.Resolve(setting.Provider);if(provider==null)return await Transfer(message,conversation,"Proveedor no soportado.",ct,providerName,model,calls,totalTools);
        var history=await db.WhatsAppMessages.AsNoTracking().Where(x=>x.ConversationId==conversationId&&x.Id<=incomingMessageId&&!string.IsNullOrWhiteSpace(x.TextBody)&&x.Type==WhatsAppMessageType.Text&&(x.Direction==WhatsAppMessageDirection.Inbound||(x.Direction==WhatsAppMessageDirection.Outbound&&x.Status!=WhatsAppMessageStatus.Failed))).OrderByDescending(x=>x.Timestamp).Take(Math.Max(1,setting.MaxContextMessages)).OrderBy(x=>x.Timestamp).Select(x=>new AiChatMessage(x.Direction==WhatsAppMessageDirection.Inbound?"user":"assistant",x.TextBody,null,null)).ToListAsync(ct);var chat=new List<AiChatMessage>{new("system",await promptBuilder.Build(conversation.BranchId,ct))};chat.AddRange(history);
        while(calls<_o.MaxModelCallsPerMessage){if(!await StillAi(conversationId,ct))return await Ignore(message,"La atención cambió durante el procesamiento.",ct);calls++;var response=await GenerateWithRetry(provider,new(model,setting.ApiKey,chat,tools.Definitions,setting.Temperature),ct);if(response.Error!=null&&response.IsTransientError)return await RetryOrTransfer(message,conversation,response.Error,ct,providerName,model,calls,totalTools);if(response.Error!=null)return await Transfer(message,conversation,response.Error,ct,providerName,model,calls,totalTools);if(response.ToolCalls.Count==0){if(string.IsNullOrWhiteSpace(response.Text))return await Transfer(message,conversation,"Respuesta vacía del proveedor.",ct,providerName,model,calls,totalTools);if(!await StillAi(conversationId,ct))return await Ignore(message,"La atención cambió antes del envío.",ct);var source=await db.WhatsAppMessages.FirstAsync(x=>x.Id==message.Id,ct);source.AiProcessingStatus=WhatsAppAiProcessingStatus.ResponseGenerated;source.AiGeneratedResponse=response.Text.Trim();source.AiResponseAttemptId??=Guid.NewGuid().ToString("N");await db.SaveChangesAsync(ct);var sent=await sender.SendTextAsync(conversationId,message.Id,source.AiResponseAttemptId,response.Text.Trim(),ct);if(sent.TransientFailure)return await RetryOrTransfer(message,conversation,sent.Error??"Fallo temporal de Meta.",ct,providerName,model,calls,totalTools);await Finish(message.Id,sent.Success?WhatsAppAiProcessingStatus.Completed:WhatsAppAiProcessingStatus.Failed,sent.Success?null:sent.Error,ct);logger.LogInformation("WhatsApp AI completed ConversationId={ConversationId} MessageId={MessageId} Provider={Provider} Model={Model} Calls={Calls} Tools={Tools}",conversationId,incomingMessageId,providerName,model,calls,totalTools);return new(true,false,null,sent.Success,false,providerName,model,calls,totalTools,sent.Error);}
          if(response.ToolCalls.Count>_o.MaxToolsPerCall||totalTools+response.ToolCalls.Count>_o.MaxTotalToolCalls)break;chat.Add(new("assistant",response.Text,null,response.ToolCalls));foreach(var call in response.ToolCalls){if(!await StillAi(conversationId,ct))return await Ignore(message,"La atención cambió antes de herramienta.",ct);var result=await tools.ExecuteAsync(call.Name,new(conversationId,conversation.BranchId,incomingMessageId,conversation.PhoneNumber,conversation.CustomerId,null,conversation.AttentionMode.ToString(),message.AiResponseAttemptId??=$"ai-{incomingMessageId}","whatsapp_ai"),call.Arguments,ct);totalTools++;var raw=JsonSerializer.Serialize(result);var json=raw.Length<=_o.MaxToolResultCharacters?raw:JsonSerializer.Serialize(new{success=result.Success,truncated=true,data=raw[..Math.Max(0,_o.MaxToolResultCharacters-100)]});chat.Add(new("tool",json,call.Id));}}
        return await Transfer(message,conversation,"Se alcanzó el límite del ciclo de herramientas.",ct,providerName,model,calls,totalTools);
      }catch(OperationCanceledException){var m=await db.WhatsAppMessages.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==incomingMessageId,CancellationToken.None);var c=await db.WhatsAppConversations.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==conversationId,CancellationToken.None);return m!=null&&c!=null?await RetryOrTransfer(m,c,"Timeout controlado.",CancellationToken.None,providerName,model,calls,totalTools):new(true,false,null,false,false,providerName,model,calls,totalTools,"Timeout controlado.");}catch(Exception ex){logger.LogError(ex,"WhatsApp AI failed ConversationId={ConversationId} MessageId={MessageId}",conversationId,incomingMessageId);await Finish(incomingMessageId,WhatsAppAiProcessingStatus.Failed,"Error controlado del orquestador.",CancellationToken.None);return new(true,false,null,false,false,providerName,model,calls,totalTools,"Error controlado.");}
    }
    private async Task<AiChatResponse> GenerateWithRetry(IAiChatProvider p,AiChatRequest r,CancellationToken ct){AiChatResponse response=new(null,[],r.Model,null,null,null,true,"Sin respuesta");for(var i=0;i<=_o.TransientRetryCount;i++){response=await p.GenerateAsync(r,ct);if(!response.IsTransientError)return response;if(i<_o.TransientRetryCount)await Task.Delay(TimeSpan.FromMilliseconds(250*(i+1)),ct);}return response;}
    private Task<bool> StillAi(int id,CancellationToken ct)=>db.WhatsAppConversations.AsNoTracking().AnyAsync(x=>x.Id==id&&x.AttentionMode==WhatsAppAttentionMode.Ai,ct);
    private async Task<WhatsAppAiProcessingResult> Ignore(Domain.Entities.WhatsAppMessage m,string reason,CancellationToken ct){await Finish(m.Id,WhatsAppAiProcessingStatus.Ignored,reason,ct);return new(false,true,reason,false,false,null,null,0,0,null);}
    private async Task<WhatsAppAiProcessingResult> RetryOrTransfer(SenorArroz.Domain.Entities.WhatsAppMessage m,SenorArroz.Domain.Entities.WhatsAppConversation c,string error,CancellationToken ct,string? provider,string? model,int calls,int used){var current=await db.WhatsAppMessages.FirstAsync(x=>x.Id==m.Id,ct);if(current.AiProcessingAttempts>=_o.MaxPersistentAttempts)return await Transfer(current,c,error,ct,provider,model,calls,used);current.AiProcessingStatus=WhatsAppAiProcessingStatus.Pending;current.AiProcessingStartedAt=null;current.AiNextRetryAt=clock.UtcNow.AddSeconds(Math.Pow(2,current.AiProcessingAttempts)*5);current.AiProcessingError=error[..Math.Min(1000,error.Length)];await db.SaveChangesAsync(ct);return new(true,false,null,false,false,provider,model,calls,used,error);}
    private async Task<WhatsAppAiProcessingResult> Transfer(SenorArroz.Domain.Entities.WhatsAppMessage m,SenorArroz.Domain.Entities.WhatsAppConversation snapshot,string error,CancellationToken ct,string? provider,string? model,int calls,int used){var c=await db.WhatsAppConversations.FirstAsync(x=>x.Id==snapshot.Id,ct);var changed=c.AttentionMode==WhatsAppAttentionMode.Ai&&attention.RequestHuman(c,null,clock.UtcNow);m=await db.WhatsAppMessages.FirstAsync(x=>x.Id==m.Id,ct);m.AiProcessingStatus=WhatsAppAiProcessingStatus.TransferredToHuman;m.AiProcessingError=error[..Math.Min(1000,error.Length)];m.AiProcessedAt=clock.UtcNow;await db.SaveChangesAsync(ct);if(changed){await notifications.NotifyAttentionChangedAsync(c.BranchId,new Features.WhatsApp.DTOs.WhatsAppConversationDto{Id=c.Id,BranchId=c.BranchId,PhoneNumber=c.PhoneNumber,Status="open",AttentionMode="waitingForHuman",LastMessageAt=c.LastMessageAt,LastMessagePreview=c.LastMessagePreview,UnreadCount=c.UnreadCount,CreatedAt=c.CreatedAt,UpdatedAt=c.UpdatedAt,AttentionModeUpdatedAt=c.AttentionModeUpdatedAt,AiPausedAt=c.AiPausedAt},ct);var configured=await db.BranchAiSettings.AsNoTracking().Where(x=>x.BranchId==c.BranchId).Select(x=>x.TransferMessage).FirstOrDefaultAsync(ct);var text=string.IsNullOrWhiteSpace(configured)?"Un asesor continuará con tu atención.":configured.Trim();await sender.SendTransferTextAsync(c.Id,m.Id,m.AiResponseAttemptId??=$"transfer-{m.Id}",text,ct);}return new(true,false,null,false,changed,provider,model,calls,used,error);}
    private async Task Finish(int id,WhatsAppAiProcessingStatus status,string? error,CancellationToken ct){var m=await db.WhatsAppMessages.FirstOrDefaultAsync(x=>x.Id==id,ct);if(m==null)return;m.AiProcessingStatus=status;m.AiProcessedAt=clock.UtcNow;m.AiProcessingError=error;await db.SaveChangesAsync(ct);}
}
