using System.Text.Json;using Microsoft.EntityFrameworkCore;using Moq;using SenorArroz.API.Services;using SenorArroz.Application.Common.Interfaces;using SenorArroz.Application.Common.Models;using SenorArroz.Domain.Entities;using SenorArroz.Domain.Enums;using SenorArroz.Infrastructure.Data;using SenorArroz.Infrastructure.Services;
namespace SenorArroz.Tests;
public class WhatsAppMediaAgentToolsTests
{
 [Fact]public async Task ProductTool_SendsRealImageAndDoesNotChangeAttention(){await using var db=Db();var branch=new Branch{Id=1,Name="Centro"};var category=new ProductCategory{Id=1,BranchId=1,Branch=branch,Name="Arroces"};var profile=new CommercialProfile{Id=1,BranchId=1,Name="Paisa",PhotoUrl="https://img/product.jpg",Description="Descripción"};db.Branches.Add(branch);db.ProductCategories.Add(category);db.CommercialProfiles.Add(profile);db.Products.Add(new Product{Id=1,CategoryId=1,Category=category,CommercialProfileId=1,CommercialProfile=profile,Name="Arroz paisa",Price=20000,Active=true});db.WhatsAppConversations.Add(new WhatsAppConversation{Id=1,BranchId=1,PhoneNumber="300",AttentionMode=WhatsAppAttentionMode.Ai});await db.SaveChangesAsync();var sender=new Mock<IWhatsAppAutomaticMessageSender>();sender.Setup(x=>x.SendAgentContentAsync(1,"run:product:1",It.IsAny<string>(),"https://img/product.jpg",It.IsAny<CancellationToken>())).ReturnsAsync(new WhatsAppAutomaticSendResult(true,false,"wamid",null));using var json=JsonDocument.Parse("""{"productId":1}""");var r=await new SendProductDetailsAgentTool(db,sender.Object).ExecuteAsync(new(1,1,ExecutionId:"run"),json.RootElement,default);Assert.True(r.Success);Assert.Equal(WhatsAppAttentionMode.Ai,(await db.WhatsAppConversations.FindAsync(1))!.AttentionMode);}
 [Fact]public async Task MenuTool_SendsEveryConfiguredImageWithStableKeys(){await using var db=Db();db.Branches.Add(new Branch{Id=1,Name="Centro",MenuImageUrl1="https://img/1.jpg",MenuImageUrl2="https://img/2.jpg"});await db.SaveChangesAsync();var sender=new Mock<IWhatsAppAutomaticMessageSender>();sender.Setup(x=>x.SendAgentContentAsync(1,It.IsAny<string>(),It.IsAny<string>(),It.IsAny<string>(),It.IsAny<CancellationToken>())).ReturnsAsync(new WhatsAppAutomaticSendResult(true,false,"wamid",null));using var json=JsonDocument.Parse("{}");var r=await new SendMenuAgentTool(db,sender.Object).ExecuteAsync(new(1,1,ExecutionId:"run"),json.RootElement,default);Assert.True(r.Success);sender.Verify(x=>x.SendAgentContentAsync(1,"run:menu:1",It.IsAny<string>(),"https://img/1.jpg",It.IsAny<CancellationToken>()),Times.Once);sender.Verify(x=>x.SendAgentContentAsync(1,"run:menu:2",It.IsAny<string>(),"https://img/2.jpg",It.IsAny<CancellationToken>()),Times.Once);}
 [Fact]public async Task MenuTool_WithoutConfiguredImagesReturnsControlledError(){await using var db=Db();db.Branches.Add(new Branch{Id=1,Name="Centro"});await db.SaveChangesAsync();using var json=JsonDocument.Parse("{}");var r=await new SendMenuAgentTool(db,Mock.Of<IWhatsAppAutomaticMessageSender>()).ExecuteAsync(new(1,1),json.RootElement,default);Assert.False(r.Success);Assert.Equal("menu_not_configured",r.Code);}
 [Fact]public async Task AutomaticSender_RepeatedDispatchDoesNotCallMetaAgain(){await using var db=Db();db.WhatsAppMessages.Add(new WhatsAppMessage{Id=1,ConversationId=1,Direction=WhatsAppMessageDirection.Outbound,Type=WhatsAppMessageType.Image,TextBody="Carta",MediaUrl="https://img/1.jpg",Status=WhatsAppMessageStatus.Sent,Timestamp=DateTime.UtcNow,SentByAi=true,AgentDispatchKey="run:menu:1",WhatsAppMessageId="wamid-existing"});await db.SaveChangesAsync();var cloud=new Mock<IWhatsAppCloudClient>();var sender=new WhatsAppAutomaticMessageSender(db,cloud.Object,Mock.Of<IWhatsAppNotificationService>(),Mock.Of<IClock>());var r=await sender.SendAgentContentAsync(1,"run:menu:1","Carta","https://img/1.jpg",default);Assert.True(r.Success);Assert.Equal("wamid-existing",r.WhatsAppMessageId);cloud.Verify(x=>x.SendImageLinkMessageAsync(It.IsAny<string>(),It.IsAny<string>(),It.IsAny<string>(),It.IsAny<string>(),It.IsAny<string>(),It.IsAny<CancellationToken>()),Times.Never);}
 private static ApplicationDbContext Db()=>new(new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
}
