using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Moq;
using SenorArroz.Application.Common.Interfaces;
using SenorArroz.Application.Common.Models;
using SenorArroz.Application.Common.Services;
using SenorArroz.Application.Options;
using SenorArroz.Domain.Entities;
using SenorArroz.Domain.Enums;
using SenorArroz.Infrastructure.Data;
using SenorArroz.Infrastructure.Services;

namespace SenorArroz.Tests;
public class WhatsAppConversationalBehaviorTests
{
 [Theory]
 [InlineData("Paisa Dúo","Paisa Dúo")]
 [InlineData("Dame un paisa duo","Paisa Dúo")]
 [InlineData("dame paisa dúo","Paisa Dúo")]
 [InlineData("quiero el paisa para dos","Paisa Dúo")]
 [InlineData("ropa viega super","Ropa Vieja Súper")]
 public async Task Matcher_resolves_accents_conversation_and_small_typos(string query,string expected){await using var db=Db();SeedCatalog(db);await db.SaveChangesAsync();var result=await new WhatsAppProductMatcher(db).MatchAsync(1,query,null);Assert.NotEmpty(result.Products);Assert.Equal(expected,result.Products[0].Name);}

 [Fact] public async Task Matcher_uses_people_and_orders_relevance(){await using var db=Db();SeedCatalog(db);await db.SaveChangesAsync();var result=await new WhatsAppProductMatcher(db).MatchAsync(1,"arroz para 2",null);Assert.Equal(2,result.ServesPeople);Assert.True(result.Products.Count>=2);Assert.All(result.Products,x=>Assert.True(x.ServesPeopleMin<=2&&x.ServesPeopleMax>=2));Assert.True(result.Products[0].Score>=result.Products[1].Score);}
 [Fact] public async Task Matcher_is_isolated_by_branch(){await using var db=Db();SeedCatalog(db);var branch2=new Branch{Id=2,Name="Otra"};var cat2=new ProductCategory{Id=2,BranchId=2,Branch=branch2,Name="Arroces"};db.Branches.Add(branch2);db.ProductCategories.Add(cat2);db.Products.Add(new Product{Id=99,Category=cat2,CategoryId=2,Name="Paisa Dúo Secreto",Price=1,Active=true,ServesPeopleMin=2,ServesPeopleMax=2});await db.SaveChangesAsync();var result=await new WhatsAppProductMatcher(db).MatchAsync(1,"paisa duo",null);Assert.DoesNotContain(result.Products,x=>x.ProductId==99);}

 [Fact] public void Ordinary_response_is_short_transactional_and_has_one_question(){var text=WhatsAppConversationPolicy.EnforceShortOrdinaryResponse("¡Este delicioso arroz es una combinación perfecta y te encantará! ¿Quieres pedirlo? ¿Deseas algo más? Además usamos una herramienta interna para buscarlo.");Assert.True(text.Length<=250);Assert.True(text.Count(x=>x=='?')<=1);Assert.DoesNotContain("delicioso",text,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("combinación perfecta",text,StringComparison.OrdinalIgnoreCase);}
 [Fact] public void Intent_policy_distinguishes_purchase_information_and_pickup(){Assert.True(WhatsAppConversationPolicy.IsPurchaseIntent("Dame un paisa dúo"));Assert.False(WhatsAppConversationPolicy.IsPurchaseIntent("Qué ingredientes trae el paisa dúo"));Assert.True(WhatsAppConversationPolicy.IsInformationRequest("Qué ingredientes trae el paisa dúo"));Assert.False(WhatsAppConversationPolicy.IsExplicitPickupRequest("No la tienen?"));Assert.True(WhatsAppConversationPolicy.IsExplicitPickupRequest("Paso por el pedido"));}

 [Fact] public async Task Purchase_intent_does_not_send_product_card(){await using var db=Db();SeedCatalog(db);db.WhatsAppConversations.Add(new WhatsAppConversation{Id=1,BranchId=1,PhoneNumber="1",AttentionMode=WhatsAppAttentionMode.Ai});db.WhatsAppMessages.Add(new WhatsAppMessage{Id=1,ConversationId=1,Direction=WhatsAppMessageDirection.Inbound,Type=WhatsAppMessageType.Text,TextBody="Dame un paisa dúo"});await db.SaveChangesAsync();var sender=new Mock<IWhatsAppAutomaticMessageSender>();using var args=JsonDocument.Parse("""{"productId":1}""");var result=await new SendProductDetailsAgentTool(db,sender.Object).ExecuteAsync(new(1,1,1),args.RootElement,default);Assert.False(result.Success);Assert.Equal("product_details_not_requested",result.Code);sender.Verify(x=>x.SendAgentContentAsync(It.IsAny<int>(),It.IsAny<string>(),It.IsAny<string>(),It.IsAny<string?>(),It.IsAny<CancellationToken>()),Times.Never);}
 [Fact] public async Task Information_request_allows_product_card(){await using var db=Db();SeedCatalog(db);db.WhatsAppConversations.Add(new WhatsAppConversation{Id=1,BranchId=1,PhoneNumber="1",AttentionMode=WhatsAppAttentionMode.Ai});db.WhatsAppMessages.Add(new WhatsAppMessage{Id=1,ConversationId=1,Direction=WhatsAppMessageDirection.Inbound,Type=WhatsAppMessageType.Text,TextBody="Qué ingredientes trae el paisa dúo"});await db.SaveChangesAsync();var sender=new Mock<IWhatsAppAutomaticMessageSender>();sender.Setup(x=>x.SendAgentContentAsync(1,It.IsAny<string>(),It.IsAny<string>(),It.IsAny<string?>(),It.IsAny<CancellationToken>())).ReturnsAsync(new WhatsAppAutomaticSendResult(true,false,"wamid",null));using var args=JsonDocument.Parse("""{"productId":1}""");var result=await new SendProductDetailsAgentTool(db,sender.Object).ExecuteAsync(new(1,1,1),args.RootElement,default);Assert.True(result.Success);}

 [Fact] public async Task New_draft_defaults_to_delivery(){await using var db=Db();var service=Drafts(db);var draft=await service.GetOrCreate(new(1,1,CustomerId:4),default);Assert.Equal(OrderType.Delivery,draft.OrderType);}
 [Theory][InlineData("No la tienen?")][InlineData("Cuál dirección?")]
 public async Task Pickup_requires_explicit_customer_request(string message){await using var db=Db();db.WhatsAppConversations.Add(new WhatsAppConversation{Id=1,BranchId=1,PhoneNumber="1",AttentionMode=WhatsAppAttentionMode.Ai});db.WhatsAppMessages.Add(new WhatsAppMessage{Id=1,ConversationId=1,Direction=WhatsAppMessageDirection.Inbound,Type=WhatsAppMessageType.Text,TextBody=message,Timestamp=DateTime.UtcNow});await db.SaveChangesAsync();using var args=JsonDocument.Parse("""{"type":"pickup"}""");var result=await new SetOrderTypeAgentTool(Drafts(db),db).ExecuteAsync(new(1,1,1,CustomerId:4),args.RootElement,default);Assert.False(result.Success);Assert.Equal("pickup_requires_explicit_customer_request",result.Code);Assert.Equal(OrderType.Delivery,(await db.WhatsAppOrderDrafts.SingleAsync()).OrderType);}
 [Fact] public async Task Explicit_pickup_request_is_accepted(){await using var db=Db();db.WhatsAppConversations.Add(new WhatsAppConversation{Id=1,BranchId=1,PhoneNumber="1",AttentionMode=WhatsAppAttentionMode.Ai});db.WhatsAppMessages.Add(new WhatsAppMessage{Id=1,ConversationId=1,Direction=WhatsAppMessageDirection.Inbound,Type=WhatsAppMessageType.Text,TextBody="Voy a recoger",Timestamp=DateTime.UtcNow});await db.SaveChangesAsync();using var args=JsonDocument.Parse("""{"type":"pickup"}""");var result=await new SetOrderTypeAgentTool(Drafts(db),db).ExecuteAsync(new(1,1,1,CustomerId:4),args.RootElement,default);Assert.True(result.Success);Assert.Equal(OrderType.Onsite,(await db.WhatsAppOrderDrafts.SingleAsync()).OrderType);}
 [Fact] public async Task Affirmative_reply_selects_primary_covered_address(){await using var db=Db();var branch=new Branch{Id=1,Name="Centro"};var neighborhood=new Neighborhood{Id=1,BranchId=1,Branch=branch,Name="Amazonia",Active=true,DeliveryFee=5000};var customer=new Customer{Id=4,BranchId=1,Name="Ana",Phone1="1"};db.AddRange(branch,neighborhood,customer,new Address{Id=12,CustomerId=4,Customer=customer,NeighborhoodId=1,Neighborhood=neighborhood,AddressText="Cr 59",IsPrimary=true},new WhatsAppConversation{Id=1,BranchId=1,PhoneNumber="1",CustomerId=4,AttentionMode=WhatsAppAttentionMode.Ai},new WhatsAppMessage{Id=1,ConversationId=1,Direction=WhatsAppMessageDirection.Inbound,Type=WhatsAppMessageType.Text,TextBody="Sí",Timestamp=DateTime.UtcNow});await db.SaveChangesAsync();using var args=JsonDocument.Parse("{}");var result=await new SelectCustomerAddressAgentTool(Drafts(db),db).ExecuteAsync(new(1,1,1,CustomerId:4),args.RootElement,default);Assert.True(result.Success);var draft=await db.WhatsAppOrderDrafts.SingleAsync();Assert.Equal(12,draft.AddressId);Assert.Equal(5000,draft.DeliveryFee);}
 [Fact] public async Task Multiple_addresses_send_selection_buttons_and_real_coverage(){await using var db=Db();var b1=new Branch{Id=1,Name="Centro"};var b2=new Branch{Id=2,Name="Otra"};var n1=new Neighborhood{Id=1,BranchId=1,Branch=b1,Name="Cubierto",Active=true};var n2=new Neighborhood{Id=2,BranchId=2,Branch=b2,Name="Fuera",Active=true};var customer=new Customer{Id=4,BranchId=1,Name="Ana",Phone1="1"};db.AddRange(b1,b2,n1,n2,customer,new Address{Id=1,CustomerId=4,Customer=customer,NeighborhoodId=1,Neighborhood=n1,AddressText="Cr 1",IsPrimary=true},new Address{Id=2,CustomerId=4,Customer=customer,NeighborhoodId=2,Neighborhood=n2,AddressText="Cr 2"});await db.SaveChangesAsync();var sender=new Mock<IWhatsAppAutomaticMessageSender>();sender.Setup(x=>x.SendAgentReplyButtonsAsync(1,It.IsAny<string>(),It.IsAny<string>(),It.IsAny<IReadOnlyList<WhatsAppReplyButton>>(),It.IsAny<CancellationToken>())).ReturnsAsync(new WhatsAppAutomaticSendResult(true,false,"wamid",null));using var args=JsonDocument.Parse("{}");var result=await new ListCustomerAddressesAgentTool(db,sender.Object).ExecuteAsync(new(1,1,1,CustomerId:4,ExecutionId:"run"),args.RootElement,default);sender.Verify(x=>x.SendAgentReplyButtonsAsync(1,"run:addresses","¿En cuál dirección entregamos?",It.Is<IReadOnlyList<WhatsAppReplyButton>>(buttons=>buttons.Count==2),It.IsAny<CancellationToken>()),Times.Once);var json=JsonSerializer.Serialize(result.Data);Assert.Contains("\"hasCoverage\":true",json);Assert.Contains("\"hasCoverage\":false",json);}

 [Fact] public async Task Old_draft_expires_and_new_one_has_no_hidden_items(){await using var db=Db();var old=new WhatsAppOrderDraft{Id=1,ConversationId=1,BranchId=1,CustomerId=4,OrderType=OrderType.Delivery,Status=WhatsAppOrderDraftStatus.Building,UpdatedAt=DateTime.UtcNow.AddHours(-2)};db.WhatsAppOrderDrafts.Add(old);await db.SaveChangesAsync();var clock=Mock.Of<IClock>(x=>x.UtcNow==DateTime.UtcNow);var service=new WhatsAppDraftService(db,new WhatsAppOrderDraftCalculator(db),Options.Create(new WhatsAppOrderDraftOptions{ResumeWindowMinutes=60}),clock);var current=await service.GetOrCreate(new(1,1,CustomerId:4),default);Assert.NotEqual(old.Id,current.Id);Assert.Equal(WhatsAppOrderDraftStatus.Expired,old.Status);Assert.Empty(current.Items);Assert.Equal(0,current.Total);}
 [Fact] public async Task Recent_draft_is_resumed(){await using var db=Db();var draft=new WhatsAppOrderDraft{Id=1,ConversationId=1,BranchId=1,CustomerId=4,OrderType=OrderType.Delivery,Status=WhatsAppOrderDraftStatus.Building,UpdatedAt=DateTime.UtcNow.AddMinutes(-10)};db.WhatsAppOrderDrafts.Add(draft);await db.SaveChangesAsync();var service=new WhatsAppDraftService(db,new WhatsAppOrderDraftCalculator(db),Options.Create(new WhatsAppOrderDraftOptions{ResumeWindowMinutes=60}));Assert.Equal(1,(await service.GetOrCreate(new(1,1,CustomerId:4),default)).Id);}
 [Fact] public async Task Summary_lists_every_item_and_total_matches_components(){await using var db=Db();SeedCatalog(db);var neighborhood=new Neighborhood{Id=10,BranchId=1,Name="Amazonia",Active=true,DeliveryFee=5000};var address=new Address{Id=10,CustomerId=4,NeighborhoodId=10,Neighborhood=neighborhood,AddressText="Cr 59"};db.Neighborhoods.Add(neighborhood);db.Addresses.Add(address);var draft=new WhatsAppOrderDraft{Id=10,ConversationId=1,BranchId=1,CustomerId=4,OrderType=OrderType.Delivery,AddressId=10,Address=address,Status=WhatsAppOrderDraftStatus.Building};draft.Items.Add(new WhatsAppOrderDraftItem{ProductId=1,Product=db.Products.Local.Single(x=>x.Id==1),Quantity=1});draft.Items.Add(new WhatsAppOrderDraftItem{ProductId=2,Product=db.Products.Local.Single(x=>x.Id==2),Quantity=2});db.WhatsAppOrderDrafts.Add(draft);await db.SaveChangesAsync();draft=await new WhatsAppOrderDraftCalculator(db).Recalculate(10);using var summary=JsonDocument.Parse(JsonSerializer.Serialize(WhatsAppDraftService.Summary(draft)));Assert.Equal(2,summary.RootElement.GetProperty("items").GetArrayLength());Assert.Equal(draft.Subtotal+draft.DeliveryFee-draft.DiscountTotal,draft.Total);Assert.Equal(218000,draft.Total);}
 [Fact] public async Task Complete_purchase_flow_resolves_adds_delivers_pays_and_summarizes(){await using var db=Db();SeedCatalog(db);var neighborhood=new Neighborhood{Id=10,BranchId=1,Name="Amazonia",Active=true,DeliveryFee=5000};var customer=new Customer{Id=4,BranchId=1,Name="Ana",Phone1="300"};var address=new Address{Id=10,CustomerId=4,Customer=customer,NeighborhoodId=10,Neighborhood=neighborhood,AddressText="Cr 59",IsPrimary=true};db.AddRange(neighborhood,customer,address,new WhatsAppConversation{Id=1,BranchId=1,CustomerId=4,PhoneNumber="300",AttentionMode=WhatsAppAttentionMode.Ai},new WhatsAppMessage{Id=1,ConversationId=1,Direction=WhatsAppMessageDirection.Inbound,Type=WhatsAppMessageType.Text,TextBody="Sí",Timestamp=DateTime.UtcNow});await db.SaveChangesAsync();var match=await new WhatsAppProductMatcher(db).MatchAsync(1,"Dame un paisa duo",null);Assert.Equal("Paisa Dúo",match.Products.Single(x=>x.Score==match.Products.Max(y=>y.Score)).Name);var drafts=Drafts(db);using(var add=JsonDocument.Parse("""{"productId":1,"quantity":1}"""))Assert.True((await new AddDraftItemAgentTool(drafts,db).ExecuteAsync(new(1,1,1,CustomerId:4),add.RootElement,default)).Success);using(var select=JsonDocument.Parse("{}"))Assert.True((await new SelectCustomerAddressAgentTool(drafts,db).ExecuteAsync(new(1,1,1,CustomerId:4),select.RootElement,default)).Success);using(var pay=JsonDocument.Parse("""{"paymentMethodId":0}"""))Assert.True((await new SetPaymentMethodAgentTool(drafts,db).ExecuteAsync(new(1,1,1,CustomerId:4),pay.RootElement,default)).Success);var draft=await drafts.ActiveDraft(1,default);using var summary=JsonDocument.Parse(JsonSerializer.Serialize(WhatsAppDraftService.Summary(draft!)));Assert.Equal("Paisa Dúo",summary.RootElement.GetProperty("items")[0].GetProperty("name").GetString());Assert.Equal("cash",summary.RootElement.GetProperty("paymentMethod").GetString());Assert.Equal(78000,summary.RootElement.GetProperty("Total").GetInt32());}

 private static WhatsAppDraftService Drafts(ApplicationDbContext db)=>new(db,new WhatsAppOrderDraftCalculator(db));
 private static ApplicationDbContext Db()=>new(new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
 private static void SeedCatalog(ApplicationDbContext db){var branch=new Branch{Id=1,Name="Centro"};var category=new ProductCategory{Id=1,BranchId=1,Branch=branch,Name="Arroces"};db.Branches.Add(branch);db.ProductCategories.Add(category);db.Products.AddRange(new Product{Id=1,Category=category,CategoryId=1,Name="Paisa Dúo",Price=73000,Active=true,ServesPeopleMin=2,ServesPeopleMax=2},new Product{Id=2,Category=category,CategoryId=1,Name="Ranchero Dúo",Price=70000,Active=true,ServesPeopleMin=2,ServesPeopleMax=2},new Product{Id=3,Category=category,CategoryId=1,Name="Ropa Vieja Súper",Price=80000,Active=true,ServesPeopleMin=2,ServesPeopleMax=3});}
}
