using Microsoft.EntityFrameworkCore;
using Moq;
using SenorArroz.Application.Common.Interfaces;
using SenorArroz.Application.Common.Services;
using SenorArroz.Domain.Entities;
using SenorArroz.Infrastructure.Data;

namespace SenorArroz.Tests;

public class WhatsAppPromptBuilderTests
{
 [Fact] public async Task Hours_AreOrderedAndFormatted(){await using var db=Db();db.BranchBusinessHours.AddRange(new BranchBusinessHour{BranchId=1,DayOfWeek=DayOfWeek.Tuesday,OpenTime=new(9,0),CloseTime=new(18,0),DisplayOrder=2},new BranchBusinessHour{BranchId=1,DayOfWeek=DayOfWeek.Monday,IsClosed=true,DisplayOrder=1});await db.SaveChangesAsync();var service=new BranchBusinessHoursService(db);var rows=await service.GetBusinessHours(1);Assert.Equal(DayOfWeek.Monday,rows[0].DayOfWeek);Assert.Contains("Cerrado",await service.GetBusinessHoursAsText(1));}
 [Fact] public async Task Prompt_UsesConfiguredOrderVariablesAndOmitsEmptyBlocks(){await using var db=Db();db.Branches.Add(new Branch{Id=1,Name="Centro",Address="Calle 1",Phone1="555"});db.BranchAiSettings.Add(new BranchAiSetting{BranchId=1,AssistantName="Lina",PromptObjective="Atender a {{BranchName}}",PromptRequiredRules="Llamar al {{BranchPhone}}"});db.BranchBusinessHours.Add(new BranchBusinessHour{BranchId=1,DayOfWeek=DayOfWeek.Monday,IsClosed=true,DisplayOrder=1});await db.SaveChangesAsync();var clock=new Mock<IClock>();clock.SetupGet(x=>x.UtcNow).Returns(new DateTime(2026,7,12,15,0,0,DateTimeKind.Utc));var prompt=await new WhatsAppSystemPromptBuilder(db,new BranchBusinessHoursService(db),clock.Object).Build(1);Assert.Contains(WhatsAppSystemPromptBuilder.InternalBasePrompt,prompt);Assert.Contains("Atender a Centro",prompt);Assert.Contains("555",prompt);Assert.Contains("Lunes: Cerrado",prompt);Assert.DoesNotContain("Personalidad:",prompt);Assert.True(prompt.IndexOf("Objetivo",StringComparison.Ordinal)<prompt.IndexOf("Reglas obligatorias",StringComparison.Ordinal));}
 [Fact] public void InternalPrompt_RequiresKnownCustomerNameAndSavedAddressConfirmation(){Assert.Contains("usa su nombre",WhatsAppSystemPromptBuilder.InternalBasePrompt);Assert.Contains("confirmar la dirección",WhatsAppSystemPromptBuilder.InternalBasePrompt);Assert.Contains("No asumas",WhatsAppSystemPromptBuilder.InternalBasePrompt);Assert.Contains("resolve_and_create_customer_address",WhatsAppSystemPromptBuilder.InternalBasePrompt);Assert.Contains("No afirmes que la dirección fue guardada",WhatsAppSystemPromptBuilder.InternalBasePrompt);}
 [Fact] public async Task MissingHours_ReturnsSevenClosedDaysMondayFirst(){await using var db=Db();var rows=await new BranchBusinessHoursService(db).GetBusinessHours(7);Assert.Equal(7,rows.Count);Assert.Equal(DayOfWeek.Monday,rows[0].DayOfWeek);Assert.Equal(DayOfWeek.Sunday,rows[6].DayOfWeek);Assert.All(rows,x=>Assert.True(x.IsClosed));}
 [Fact] public async Task Draft_ReplacesKnownVariablesCaseInsensitively_AndKeepsUnknown(){await using var db=Db();db.Branches.Add(new Branch{Id=1,Name="Centro",Address="Calle 1",Phone1="555"});await db.SaveChangesAsync();var clock=new Mock<IClock>();clock.SetupGet(x=>x.UtcNow).Returns(new DateTime(2026,7,12,15,30,0,DateTimeKind.Utc));var b=new WhatsAppSystemPromptBuilder(db,new BranchBusinessHoursService(db),clock.Object);var prompt=await b.Build(1,new WhatsAppPromptConfiguration(null,"{{branchname}} {{BranchAddress}} {{BranchPhone}} {{Today}} {{CurrentTime}} {{Unknown}}",null,null,null,null));Assert.Contains("Centro",prompt);Assert.Contains("Calle 1",prompt);Assert.Contains("555",prompt);Assert.Contains("2026-07-12",prompt);Assert.Contains("10:30",prompt);Assert.Contains("{{Unknown}}",prompt);}
 [Fact] public async Task Draft_DoesNotPersistConfiguration(){await using var db=Db();db.Branches.Add(new Branch{Id=1,Name="Centro"});await db.SaveChangesAsync();var clock=Mock.Of<IClock>(x=>x.UtcNow==DateTime.UtcNow);await new WhatsAppSystemPromptBuilder(db,new BranchBusinessHoursService(db),clock).Build(1,new WhatsAppPromptConfiguration("Borrador",null,null,null,null,null));Assert.Empty(db.BranchAiSettings);}
 private static ApplicationDbContext Db()=>new(new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
}
