using System.Text.Json;using Microsoft.EntityFrameworkCore;using SenorArroz.Application.Common.Models;using SenorArroz.Application.Common.Services;using SenorArroz.Domain.Entities;using SenorArroz.Infrastructure.Data;using SenorArroz.Infrastructure.Services;
namespace SenorArroz.Tests;
public class WhatsAppOrderDraftToolsTests
{
 [Fact]public async Task GetOrCreate_ReturnsSameActiveDraft(){await using var db=Db();var s=Service(db);var c=new AgentToolExecutionContext(1,1,CustomerId:4);var a=await s.GetOrCreate(c,default);var b=await s.GetOrCreate(c,default);Assert.Equal(a.Id,b.Id);Assert.Single(db.WhatsAppOrderDrafts);}
 [Fact]public async Task AddItem_UsesCurrentProductPriceAndRecalculates(){await using var db=Db();SeedProduct(db,1,1,12000);await db.SaveChangesAsync();var s=Service(db);var tool=new AddDraftItemAgentTool(s,db);using var json=JsonDocument.Parse("""{"productId":1,"quantity":2}""");var result=await tool.ExecuteAsync(new(1,1,CustomerId:4),json.RootElement,default);Assert.True(result.Success);var d=await db.WhatsAppOrderDrafts.Include(x=>x.Items).SingleAsync();Assert.Equal(24000,d.Subtotal);Assert.Equal(12000,d.Items.Single().UnitPrice);}
 [Fact]public async Task AddItem_RejectsProductFromAnotherBranch(){await using var db=Db();SeedProduct(db,1,2,12000);await db.SaveChangesAsync();var tool=new AddDraftItemAgentTool(Service(db),db);using var json=JsonDocument.Parse("""{"productId":1,"quantity":1}""");var result=await tool.ExecuteAsync(new(1,1,CustomerId:4),json.RootElement,default);Assert.False(result.Success);Assert.Equal("product_not_found",result.Code);}
 [Fact]public async Task CashChange_RejectsAmountBelowCurrentTotal(){await using var db=Db();SeedProduct(db,1,1,10000);var draft=new WhatsAppOrderDraft{Id=1,ConversationId=1,BranchId=1,CustomerId=4,PaymentMethod="cash"};draft.Items.Add(new WhatsAppOrderDraftItem{ProductId=1,Quantity=1,Product=db.Products.Local.First(),UnitPrice=10000,Subtotal=10000});db.WhatsAppOrderDrafts.Add(draft);await db.SaveChangesAsync();var tool=new CalculateCashChangeAgentTool(Service(db),db);using var json=JsonDocument.Parse("""{"cashReceived":5000}""");var r=await tool.ExecuteAsync(new(1,1,CustomerId:4),json.RootElement,default);Assert.False(r.Success);Assert.Equal("cash_insufficient",r.Code);}
 [Fact]public async Task CustomerToolSchema_DoesNotAllowPhoneOrBranch(){await using var db=Db();var tool=new CreateCustomerAgentTool(db);var schema=tool.ParametersSchema.GetRawText();Assert.DoesNotContain("phone",schema,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("branch",schema,StringComparison.OrdinalIgnoreCase);}
 [Fact]public async Task CancelDraft_IsIdempotent(){await using var db=Db();var s=Service(db);await s.GetOrCreate(new(1,1,CustomerId:4),default);var tool=new CancelOrderDraftAgentTool(s,db);using var json=JsonDocument.Parse("{}");Assert.True((await tool.ExecuteAsync(new(1,1),json.RootElement,default)).Success);Assert.True((await tool.ExecuteAsync(new(1,1),json.RootElement,default)).Success);}
 private static ApplicationDbContext Db()=>new(new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
 private static WhatsAppDraftService Service(ApplicationDbContext db)=>new(db,new WhatsAppOrderDraftCalculator(db));
 private static void SeedProduct(ApplicationDbContext db,int id,int branch,int price){var category=new ProductCategory{Id=id,BranchId=branch,Name="Arroces"};db.ProductCategories.Add(category);db.Products.Add(new Product{Id=id,CategoryId=id,Category=category,Name="Arroz",Price=price,Active=true});}
}
