CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE branch (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        address character varying(200) NOT NULL,
        phone1 character varying(10) NOT NULL,
        phone2 character varying(10),
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_branch" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE expense_category (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_expense_category" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE supplier (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        name character varying(100) NOT NULL,
        phone character varying(10) NOT NULL,
        address character varying(200),
        email character varying(200),
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_supplier" PRIMARY KEY (id),
        CONSTRAINT "FK_supplier_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE bank (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        name character varying(150) NOT NULL,
        image_url character varying(200),
        active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_bank" PRIMARY KEY (id),
        CONSTRAINT "FK_bank_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE customer (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        name character varying(150) NOT NULL,
        phone1 character varying(10) NOT NULL,
        phone2 character varying(10),
        active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_customer" PRIMARY KEY (id),
        CONSTRAINT "FK_customer_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE loyalty_rule (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        description text NOT NULL,
        n_orders_needed integer NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_loyalty_rule" PRIMARY KEY (id),
        CONSTRAINT "FK_loyalty_rule_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE neighborhood (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        name character varying(150) NOT NULL,
        delivery_fee integer NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_neighborhood" PRIMARY KEY (id),
        CONSTRAINT "FK_neighborhood_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE product_category (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        name character varying(150) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_product_category" PRIMARY KEY (id),
        CONSTRAINT "FK_product_category_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE "user" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        role text DEFAULT 'deliveryman',
        name character varying(150) NOT NULL,
        email character varying(100) NOT NULL,
        phone character varying(10) NOT NULL,
        password_hash character varying(255) NOT NULL,
        active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_user" PRIMARY KEY (id),
        CONSTRAINT "FK_user_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE expense (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        category_id integer NOT NULL,
        unit character varying(50) NOT NULL DEFAULT 'unit',
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_expense" PRIMARY KEY (id),
        CONSTRAINT "FK_expense_expense_category_category_id" FOREIGN KEY (category_id) REFERENCES expense_category (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE expense_header (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        supplier_id integer NOT NULL,
        total integer,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_expense_header" PRIMARY KEY (id),
        CONSTRAINT "FK_expense_header_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_expense_header_supplier_supplier_id" FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE app (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        bank_id integer NOT NULL,
        name character varying(150) NOT NULL,
        image_url character varying(200),
        active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_app" PRIMARY KEY (id),
        CONSTRAINT "FK_app_bank_bank_id" FOREIGN KEY (bank_id) REFERENCES bank (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE address (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        customer_id integer NOT NULL,
        neighborhood_id integer NOT NULL,
        address character varying(200) NOT NULL,
        additional_info character varying(150),
        delivery_fee integer NOT NULL,
        latitude numeric(10,6),
        longitude numeric(10,6),
        is_primary boolean NOT NULL DEFAULT FALSE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_address" PRIMARY KEY (id),
        CONSTRAINT "FK_address_customer_customer_id" FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE,
        CONSTRAINT "FK_address_neighborhood_neighborhood_id" FOREIGN KEY (neighborhood_id) REFERENCES neighborhood (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE product (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        category_id integer NOT NULL,
        name character varying(150) NOT NULL,
        price integer NOT NULL,
        stock integer,
        active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_product" PRIMARY KEY (id),
        CONSTRAINT "FK_product_product_category_category_id" FOREIGN KEY (category_id) REFERENCES product_category (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE password_reset_token (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        token character varying(500) NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        is_used boolean NOT NULL DEFAULT FALSE,
        used_at timestamp with time zone,
        used_by_ip character varying(45),
        email character varying(100) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_password_reset_token" PRIMARY KEY (id),
        CONSTRAINT "FK_password_reset_token_user_user_id" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE refresh_token (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        token character varying(500) NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        is_revoked boolean NOT NULL DEFAULT FALSE,
        revoked_at timestamp with time zone,
        replaced_by_token character varying(500),
        revoked_by_ip character varying(45),
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_refresh_token" PRIMARY KEY (id),
        CONSTRAINT "FK_refresh_token_user_user_id" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE expense_bank_payment (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        bank_id integer NOT NULL,
        expense_header_id integer NOT NULL,
        amount numeric(12,2) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_expense_bank_payment" PRIMARY KEY (id),
        CONSTRAINT "FK_expense_bank_payment_bank_bank_id" FOREIGN KEY (bank_id) REFERENCES bank (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_expense_bank_payment_expense_header_expense_header_id" FOREIGN KEY (expense_header_id) REFERENCES expense_header (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE expense_detail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        header_id integer NOT NULL,
        expense_id integer NOT NULL,
        quantity integer NOT NULL DEFAULT 1,
        amount integer NOT NULL,
        total integer,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_expense_detail" PRIMARY KEY (id),
        CONSTRAINT "FK_expense_detail_expense_expense_id" FOREIGN KEY (expense_id) REFERENCES expense (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_expense_detail_expense_header_header_id" FOREIGN KEY (header_id) REFERENCES expense_header (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE "order" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        taken_by_id integer NOT NULL,
        customer_id integer,
        address_id integer,
        loyalty_rule_id integer,
        delivery_man_id integer,
        guestname character varying(100),
        type text NOT NULL DEFAULT 'delivery',
        delivery_fee integer,
        reserved_for timestamp with time zone,
        status text NOT NULL,
        status_times jsonb NOT NULL,
        subtotal integer NOT NULL DEFAULT 0,
        total integer NOT NULL DEFAULT 0,
        discount_total integer NOT NULL DEFAULT 0,
        notes character varying(200),
        cancelled_reason character varying(200),
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_order" PRIMARY KEY (id),
        CONSTRAINT "FK_order_address_address_id" FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE SET NULL,
        CONSTRAINT "FK_order_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_order_customer_customer_id" FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE SET NULL,
        CONSTRAINT "FK_order_loyalty_rule_loyalty_rule_id" FOREIGN KEY (loyalty_rule_id) REFERENCES loyalty_rule (id) ON DELETE SET NULL,
        CONSTRAINT "FK_order_user_delivery_man_id" FOREIGN KEY (delivery_man_id) REFERENCES "user" (id) ON DELETE SET NULL,
        CONSTRAINT "FK_order_user_taken_by_id" FOREIGN KEY (taken_by_id) REFERENCES "user" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE app_payment (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        order_id integer NOT NULL,
        app_id integer NOT NULL,
        amount numeric NOT NULL,
        is_setted boolean NOT NULL DEFAULT FALSE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_app_payment" PRIMARY KEY (id),
        CONSTRAINT "FK_app_payment_app_app_id" FOREIGN KEY (app_id) REFERENCES app (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_app_payment_order_order_id" FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE bank_payment (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        order_id integer NOT NULL,
        bank_id integer NOT NULL,
        amount numeric(12,2) NOT NULL,
        is_verified boolean NOT NULL DEFAULT FALSE,
        verified_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_bank_payment" PRIMARY KEY (id),
        CONSTRAINT "FK_bank_payment_bank_bank_id" FOREIGN KEY (bank_id) REFERENCES bank (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_bank_payment_order_order_id" FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE TABLE order_detail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        order_id integer NOT NULL,
        product_id integer NOT NULL,
        quantity integer NOT NULL DEFAULT 1,
        unit_price integer NOT NULL DEFAULT 0,
        discount integer NOT NULL DEFAULT 0,
        subtotal integer,
        notes text,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_order_detail" PRIMARY KEY (id),
        CONSTRAINT "FK_order_detail_order_order_id" FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE,
        CONSTRAINT "FK_order_detail_product_product_id" FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_address_customer ON address (customer_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_address_neighborhood ON address (neighborhood_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_app_bank_id" ON app (bank_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_app_payment_app_id" ON app_payment (app_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_app_payment_order_id" ON app_payment (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_bank_branch_id" ON bank (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
        CREATE INDEX idx_supplier_branch_name ON supplier (branch_id, name);
        END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_bank_payment_bank_id" ON bank_payment (bank_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_bank_payment_order_id" ON bank_payment (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_customer_active ON customer (active) WHERE active = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_customer_branch ON customer (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_customer_phone ON customer (phone1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_expense_category_id" ON expense (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_expense_bank_payment_bank_id" ON expense_bank_payment (bank_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_expense_bank_payment_expense_header_id" ON expense_bank_payment (expense_header_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_expense_detail_header ON expense_detail (header_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_expense_detail_expense_id" ON expense_detail (expense_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_expense_header_branch ON expense_header (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_expense_header_supplier ON expense_header (supplier_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_loyalty_rule_branch_id" ON loyalty_rule (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_neighborhood_branch_id" ON neighborhood (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_order_branch ON "order" (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_order_customer ON "order" (customer_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_order_date ON "order" (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_order_delivery_man ON "order" (delivery_man_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_order_status ON "order" (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_order_type ON "order" (type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_order_address_id" ON "order" (address_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_order_loyalty_rule_id" ON "order" (loyalty_rule_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_order_taken_by_id" ON "order" (taken_by_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_order_detail_order ON order_detail (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_order_detail_product ON order_detail (product_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_password_reset_token_email ON password_reset_token (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_password_reset_token_expires_at ON password_reset_token (expires_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE UNIQUE INDEX idx_password_reset_token_token ON password_reset_token (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_password_reset_token_user_id ON password_reset_token (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_password_reset_token_user_used ON password_reset_token (user_id, is_used);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_product_active ON product (active) WHERE active = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_product_category ON product (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX "IX_product_category_branch_id" ON product_category (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_refresh_token_expires_at ON refresh_token (expires_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE UNIQUE INDEX idx_refresh_token_token ON refresh_token (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_refresh_token_user_active ON refresh_token (user_id, is_revoked);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_refresh_token_user_id ON refresh_token (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_user_active ON "user" (active) WHERE active = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_user_branch ON "user" (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    CREATE INDEX idx_user_role ON "user" (role);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122122758_InitialSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251122122758_InitialSchema', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    CREATE OR REPLACE FUNCTION public.calculate_expense_detail_total() RETURNS trigger
                        LANGUAGE plpgsql
                        AS $$
                    BEGIN
                        NEW.total = NEW.quantity * NEW.amount;
                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    CREATE OR REPLACE FUNCTION public.calculate_order_detail_subtotal() RETURNS trigger
                        LANGUAGE plpgsql
                        AS $$
                    BEGIN
                        NEW.subtotal = (NEW.quantity * NEW.unit_price) - COALESCE(NEW.discount, 0);
                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    CREATE OR REPLACE FUNCTION public.update_expense_header_total() RETURNS trigger
                        LANGUAGE plpgsql
                        AS $$
                    DECLARE
                        header_total INTEGER;
                        target_header_id INTEGER;
                    BEGIN
                        IF TG_OP = 'DELETE' THEN
                            target_header_id = OLD.header_id;
                        ELSE
                            target_header_id = NEW.header_id;
                        END IF;
                        
                        SELECT COALESCE(SUM(total), 0)
                        INTO header_total
                        FROM expense_detail 
                        WHERE header_id = target_header_id;
                        
                        UPDATE expense_header 
                        SET 
                            total = header_total,
                            updated_at = NOW()
                        WHERE id = target_header_id;
                        
                        IF TG_OP = 'DELETE' THEN
                            RETURN OLD;
                        ELSE
                            RETURN NEW;
                        END IF;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    CREATE OR REPLACE FUNCTION public.update_order_total_on_delivery_fee_change() RETURNS trigger
                        LANGUAGE plpgsql
                        AS $$
                    BEGIN
                        IF OLD.delivery_fee IS DISTINCT FROM NEW.delivery_fee THEN
                            NEW.total = NEW.subtotal + COALESCE(NEW.delivery_fee, 0) - NEW.discount_total;
                        END IF;
                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    CREATE OR REPLACE FUNCTION public.update_order_totals() RETURNS trigger
                        LANGUAGE plpgsql
                        AS $$
                    DECLARE
                        order_subtotal INTEGER;
                        order_discount_total INTEGER;
                        order_delivery_fee INTEGER;
                    BEGIN
                        DECLARE
                            target_order_id INTEGER;
                        BEGIN
                            IF TG_OP = 'DELETE' THEN
                                target_order_id = OLD.order_id;
                            ELSE
                                target_order_id = NEW.order_id;
                            END IF;
                            
                            SELECT COALESCE(SUM(subtotal), 0)
                            INTO order_subtotal
                            FROM order_detail 
                            WHERE order_id = target_order_id;
                            
                            SELECT COALESCE(SUM(discount), 0)
                            INTO order_discount_total
                            FROM order_detail 
                            WHERE order_id = target_order_id;
                            
                            SELECT COALESCE(delivery_fee, 0)
                            INTO order_delivery_fee
                            FROM "order"
                            WHERE id = target_order_id;
                            
                            UPDATE "order" 
                            SET 
                                subtotal = order_subtotal,
                                discount_total = order_discount_total,
                                total = order_subtotal + order_delivery_fee - order_discount_total,
                                updated_at = NOW()
                            WHERE id = target_order_id;
                        END;
                        
                        IF TG_OP = 'DELETE' THEN
                            RETURN OLD;
                        ELSE
                            RETURN NEW;
                        END IF;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS trigger
                        LANGUAGE plpgsql
                        AS $$
                    BEGIN
                        NEW.updated_at = NOW();
                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    CREATE OR REPLACE FUNCTION public.update_bank_payment_verified_at() RETURNS trigger
                        LANGUAGE plpgsql
                        AS $$
                    BEGIN
                        -- Cuando se verifica el pago (is_verified cambia de false a true)
                        IF NEW.is_verified = true AND (OLD.is_verified = false OR OLD.is_verified IS NULL) THEN
                            NEW.verified_at := NOW();
                        -- Cuando se desverifica el pago (is_verified cambia de true a false)
                        ELSIF NEW.is_verified = false AND OLD.is_verified = true THEN
                            NEW.verified_at := NULL;
                        END IF;
                        
                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS calculate_expense_detail_total_trigger ON public.expense_detail;
                    CREATE TRIGGER calculate_expense_detail_total_trigger 
                        BEFORE INSERT OR UPDATE ON public.expense_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.calculate_expense_detail_total();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_expense_header_total_on_detail_insert ON public.expense_detail;
                    CREATE TRIGGER update_expense_header_total_on_detail_insert 
                        AFTER INSERT ON public.expense_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_expense_header_total();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_expense_header_total_on_detail_update ON public.expense_detail;
                    CREATE TRIGGER update_expense_header_total_on_detail_update 
                        AFTER UPDATE ON public.expense_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_expense_header_total();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_expense_header_total_on_detail_delete ON public.expense_detail;
                    CREATE TRIGGER update_expense_header_total_on_detail_delete 
                        AFTER DELETE ON public.expense_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_expense_header_total();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS calculate_order_detail_subtotal_trigger ON public.order_detail;
                    CREATE TRIGGER calculate_order_detail_subtotal_trigger 
                        BEFORE INSERT OR UPDATE ON public.order_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.calculate_order_detail_subtotal();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_order_totals_on_detail_insert ON public.order_detail;
                    CREATE TRIGGER update_order_totals_on_detail_insert 
                        AFTER INSERT ON public.order_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_order_totals();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_order_totals_on_detail_update ON public.order_detail;
                    CREATE TRIGGER update_order_totals_on_detail_update 
                        AFTER UPDATE ON public.order_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_order_totals();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_order_totals_on_detail_delete ON public.order_detail;
                    CREATE TRIGGER update_order_totals_on_detail_delete 
                        AFTER DELETE ON public.order_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_order_totals();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_order_total_on_delivery_fee_change_trigger ON public."order";
                    CREATE TRIGGER update_order_total_on_delivery_fee_change_trigger 
                        BEFORE UPDATE ON public."order" 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_order_total_on_delivery_fee_change();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_order_updated_at ON public."order";
                    CREATE TRIGGER update_order_updated_at 
                        BEFORE UPDATE ON public."order" 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS trigger_bank_payment_verified_at ON public.bank_payment;
                    CREATE TRIGGER trigger_bank_payment_verified_at 
                        BEFORE UPDATE ON public.bank_payment 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_bank_payment_verified_at();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_address_updated_at ON public.address;
                    CREATE TRIGGER update_address_updated_at 
                        BEFORE UPDATE ON public.address 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_branch_updated_at ON public.branch;
                    CREATE TRIGGER update_branch_updated_at 
                        BEFORE UPDATE ON public.branch 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_customer_updated_at ON public.customer;
                    CREATE TRIGGER update_customer_updated_at 
                        BEFORE UPDATE ON public.customer 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_neighborhood_updated_at ON public.neighborhood;
                    CREATE TRIGGER update_neighborhood_updated_at 
                        BEFORE UPDATE ON public.neighborhood 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_order_detail_updated_at ON public.order_detail;
                    CREATE TRIGGER update_order_detail_updated_at 
                        BEFORE UPDATE ON public.order_detail 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_password_reset_token_updated_at ON public.password_reset_token;
                    CREATE TRIGGER update_password_reset_token_updated_at 
                        BEFORE UPDATE ON public.password_reset_token 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_product_category_updated_at ON public.product_category;
                    CREATE TRIGGER update_product_category_updated_at 
                        BEFORE UPDATE ON public.product_category 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_product_updated_at ON public.product;
                    CREATE TRIGGER update_product_updated_at 
                        BEFORE UPDATE ON public.product 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_refresh_token_updated_at ON public.refresh_token;
                    CREATE TRIGGER update_refresh_token_updated_at 
                        BEFORE UPDATE ON public.refresh_token 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN

                    DROP TRIGGER IF EXISTS update_user_updated_at ON public."user";
                    CREATE TRIGGER update_user_updated_at 
                        BEFORE UPDATE ON public."user" 
                        FOR EACH ROW 
                        EXECUTE FUNCTION public.update_updated_at_column();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123044_CreateDatabaseFunctionsAndTriggers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251122123044_CreateDatabaseFunctionsAndTriggers', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123208_SeedInitialData') THEN

                    DO $$
                    DECLARE
                        branch_id_var INTEGER;
                    BEGIN
                        -- Insertar sucursal si no existe
                        INSERT INTO branch (name, address, phone1, phone2) 
                        VALUES ('Santander', 'calle 108a # 77d-30', '0000000000', NULL)
                        ON CONFLICT DO NOTHING;
                        
                        -- Obtener ID de la sucursal
                        SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
                        
                        -- 2. USUARIOS
                        INSERT INTO "user" (branch_id, role, name, email, phone, password_hash, active)
                        VALUES 
                            (branch_id_var, 'superadmin', 'Santiago', 'santyvano@outlook.com', '0000000000', '$2a$11$5ERmxaaUoW.MLkirB/l22eyaZxF1OCK2kjtN9DtYo14k.o2XmkyBy', true),
                            (branch_id_var, 'admin', 'Daniel Alvarez', 'daniel@daniel.com', '3125486596', '$2a$12$FR0XMK.2RulbbSgH5un0Uu8fZ/KcfXMZdGtng4N8jIiaxe/nbkanS', true),
                            (branch_id_var, 'deliveryman', 'Abelardo', 'abelardo@abelardo.com', '3226474857', '$2a$12$QRFDuTrE7HfTefR5syYkV.6JQ62bGYheR56Qhs9TCuhAVzr0FnGGy', true),
                            (branch_id_var, 'deliveryman', 'Maikol Martinez Serna', 'maikol@maikol.com', '3021563245', '$2a$12$9wl/bOW4736yr3ssYHweUekgRch7RnafYTKHo2RVKcUH1kYJlSVbG', true),
                            (branch_id_var, 'kitchen', 'juan', 'juan@juan.com', '3256325695', '$2a$12$oPImGwKsmXYVhlY1spD3ROyNZXDGchLNnIYl9B97KY1Sok9Cb6Wna', true)
                        ON CONFLICT DO NOTHING;
                        
                        -- 3. BARRIOS DEL NORTE DE MEDELLIN
                        INSERT INTO neighborhood (branch_id, name, delivery_fee)
                        VALUES 
                            (branch_id_var, 'Castilla', 3000),
                            (branch_id_var, 'Santander', 4000),
                            (branch_id_var, 'Pedregal', 2500),
                            (branch_id_var, 'Florencia', 3500),
                            (branch_id_var, 'Picacho', 5000)
                        ON CONFLICT DO NOTHING;
                        
                        -- 4. BANCO
                        INSERT INTO bank (branch_id, name, image_url, active)
                        VALUES (branch_id_var, 'Bancolombia', NULL, true)
                        ON CONFLICT DO NOTHING;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123208_SeedInitialData') THEN

                    DO $$
                    DECLARE
                        branch_id_var INTEGER;
                        bank_id_var INTEGER;
                    BEGIN
                        SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
                        SELECT id INTO bank_id_var FROM bank WHERE name = 'Bancolombia' AND branch_id = branch_id_var LIMIT 1;
                        
                        IF bank_id_var IS NOT NULL THEN
                            INSERT INTO app (bank_id, name, image_url, active)
                            VALUES (bank_id_var, 'Didi', NULL, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123208_SeedInitialData') THEN

                    DO $$
                    DECLARE
                        branch_id_var INTEGER;
                    BEGIN
                        SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
                        
                        INSERT INTO product_category (branch_id, name)
                        VALUES 
                            (branch_id_var, 'Bebidas'),
                            (branch_id_var, 'Entradas'),
                            (branch_id_var, 'Platos Principales'),
                            (branch_id_var, 'Postres'),
                            (branch_id_var, 'Acompanamientos')
                        ON CONFLICT DO NOTHING;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123208_SeedInitialData') THEN

                    DO $$
                    DECLARE
                        branch_id_var INTEGER;
                        bebidas_cat_id INTEGER;
                        entradas_cat_id INTEGER;
                        platos_cat_id INTEGER;
                        postres_cat_id INTEGER;
                        acompanamientos_cat_id INTEGER;
                    BEGIN
                        SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
                        SELECT id INTO bebidas_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Bebidas' LIMIT 1;
                        SELECT id INTO entradas_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Entradas' LIMIT 1;
                        SELECT id INTO platos_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Platos Principales' LIMIT 1;
                        SELECT id INTO postres_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Postres' LIMIT 1;
                        SELECT id INTO acompanamientos_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Acompanamientos' LIMIT 1;
                        
                        -- Bebidas
                        INSERT INTO product (category_id, name, price, stock, active)
                        SELECT bebidas_cat_id, name, price, stock, active
                        FROM (VALUES
                            ('Coca Cola', 3000, 100, true),
                            ('Agua', 2000, 100, true),
                            ('Jugo Natural', 4000, 50, true),
                            ('Limonada', 3500, 50, true),
                            ('Gaseosa Personal', 2500, 100, true)
                        ) AS v(name, price, stock, active)
                        WHERE NOT EXISTS (
                            SELECT 1 FROM product p
                            INNER JOIN product_category pc ON p.category_id = pc.id
                            WHERE pc.branch_id = branch_id_var 
                            AND pc.name = 'Bebidas'
                            AND p.name = v.name
                        );
                        
                        -- Entradas
                        INSERT INTO product (category_id, name, price, stock, active)
                        SELECT entradas_cat_id, name, price, stock, active
                        FROM (VALUES
                            ('Patacones con Hogao', 8000, 30, true),
                            ('Arepas con Queso', 6000, 40, true),
                            ('Empanadas (3 unidades)', 7000, 50, true),
                            ('Chicharron', 10000, 25, true),
                            ('Ensalada de la Casa', 9000, 20, true)
                        ) AS v(name, price, stock, active)
                        WHERE NOT EXISTS (
                            SELECT 1 FROM product p
                            INNER JOIN product_category pc ON p.category_id = pc.id
                            WHERE pc.branch_id = branch_id_var 
                            AND pc.name = 'Entradas'
                            AND p.name = v.name
                        );
                        
                        -- Platos Principales
                        INSERT INTO product (category_id, name, price, stock, active)
                        SELECT platos_cat_id, name, price, stock, active
                        FROM (VALUES
                            ('Arroz con Pollo', 15000, 20, true),
                            ('Bandeja Paisa', 18000, 15, true),
                            ('Sancocho', 12000, 25, true),
                            ('Ajiaco', 14000, 20, true),
                            ('Pechuga a la Plancha', 16000, 18, true),
                            ('Pescado Frito', 17000, 12, true),
                            ('Carne Asada', 19000, 15, true),
                            ('Chuleta de Cerdo', 17500, 10, true)
                        ) AS v(name, price, stock, active)
                        WHERE NOT EXISTS (
                            SELECT 1 FROM product p
                            INNER JOIN product_category pc ON p.category_id = pc.id
                            WHERE pc.branch_id = branch_id_var 
                            AND pc.name = 'Platos Principales'
                            AND p.name = v.name
                        );
                        
                        -- Postres
                        INSERT INTO product (category_id, name, price, stock, active)
                        SELECT postres_cat_id, name, price, stock, active
                        FROM (VALUES
                            ('Flan de Caramelo', 6000, 15, true),
                            ('Tres Leches', 7000, 12, true),
                            ('Helado', 5000, 20, true),
                            ('Brownie con Helado', 8000, 10, true),
                            ('Mazamorra', 4000, 25, true)
                        ) AS v(name, price, stock, active)
                        WHERE NOT EXISTS (
                            SELECT 1 FROM product p
                            INNER JOIN product_category pc ON p.category_id = pc.id
                            WHERE pc.branch_id = branch_id_var 
                            AND pc.name = 'Postres'
                            AND p.name = v.name
                        );
                        
                        -- Acompanamientos
                        INSERT INTO product (category_id, name, price, stock, active)
                        SELECT acompanamientos_cat_id, name, price, stock, active
                        FROM (VALUES
                            ('Arroz', 2000, 100, true),
                            ('Frijoles', 3000, 80, true),
                            ('Papas Fritas', 4000, 60, true),
                            ('Ensalada', 3000, 50, true),
                            ('Platano Maduro', 2500, 70, true)
                        ) AS v(name, price, stock, active)
                        WHERE NOT EXISTS (
                            SELECT 1 FROM product p
                            INNER JOIN product_category pc ON p.category_id = pc.id
                            WHERE pc.branch_id = branch_id_var 
                            AND pc.name = 'Acompanamientos'
                            AND p.name = v.name
                        );
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123208_SeedInitialData') THEN

                    DO $$
                    DECLARE
                        branch_id_var INTEGER;
                        castilla_id INTEGER;
                        santander_id INTEGER;
                        pedregal_id INTEGER;
                        florencia_id INTEGER;
                        picacho_id INTEGER;
                        customer1_id INTEGER;
                        customer2_id INTEGER;
                        customer3_id INTEGER;
                        customer4_id INTEGER;
                        customer5_id INTEGER;
                        customer6_id INTEGER;
                        customer7_id INTEGER;
                        customer8_id INTEGER;
                    BEGIN
                        SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
                        SELECT id INTO castilla_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Castilla' LIMIT 1;
                        SELECT id INTO santander_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Santander' LIMIT 1;
                        SELECT id INTO pedregal_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Pedregal' LIMIT 1;
                        SELECT id INTO florencia_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Florencia' LIMIT 1;
                        SELECT id INTO picacho_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Picacho' LIMIT 1;
                        
                        -- Cliente 1: Maria Gonzalez - Castilla
                        INSERT INTO customer (branch_id, name, phone1, phone2, active)
                        VALUES (branch_id_var, 'Maria Gonzalez', '3001234567', NULL, true)
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO customer1_id;
                        
                        IF customer1_id IS NULL THEN
                            SELECT id INTO customer1_id FROM customer WHERE branch_id = branch_id_var AND phone1 = '3001234567' LIMIT 1;
                        END IF;
                        
                        IF customer1_id IS NOT NULL AND castilla_id IS NOT NULL THEN
                            INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary)
                            VALUES (customer1_id, castilla_id, 'Calle 65 #45-20, Castilla', NULL, 3000, 6.2810, -75.5710, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                        
                        -- Cliente 2: Carlos Ramirez - Santander
                        INSERT INTO customer (branch_id, name, phone1, phone2, active)
                        VALUES (branch_id_var, 'Carlos Ramirez', '3102345678', NULL, true)
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO customer2_id;
                        
                        IF customer2_id IS NULL THEN
                            SELECT id INTO customer2_id FROM customer WHERE branch_id = branch_id_var AND phone1 = '3102345678' LIMIT 1;
                        END IF;
                        
                        IF customer2_id IS NOT NULL AND santander_id IS NOT NULL THEN
                            INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary)
                            VALUES (customer2_id, santander_id, 'Carrera 50 #30-15, Santander', NULL, 4000, 6.2910, -75.5610, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                        
                        -- Cliente 3: Ana Martinez - Pedregal
                        INSERT INTO customer (branch_id, name, phone1, phone2, active)
                        VALUES (branch_id_var, 'Ana Martinez', '3203456789', NULL, true)
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO customer3_id;
                        
                        IF customer3_id IS NULL THEN
                            SELECT id INTO customer3_id FROM customer WHERE branch_id = branch_id_var AND phone1 = '3203456789' LIMIT 1;
                        END IF;
                        
                        IF customer3_id IS NOT NULL AND pedregal_id IS NOT NULL THEN
                            INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary)
                            VALUES (customer3_id, pedregal_id, 'Calle 70 #55-30, Pedregal', NULL, 2500, 6.3010, -75.5510, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                        
                        -- Cliente 4: Luis Perez - Florencia
                        INSERT INTO customer (branch_id, name, phone1, phone2, active)
                        VALUES (branch_id_var, 'Luis Perez', '3154567890', NULL, true)
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO customer4_id;
                        
                        IF customer4_id IS NULL THEN
                            SELECT id INTO customer4_id FROM customer WHERE branch_id = branch_id_var AND phone1 = '3154567890' LIMIT 1;
                        END IF;
                        
                        IF customer4_id IS NOT NULL AND florencia_id IS NOT NULL THEN
                            INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary)
                            VALUES (customer4_id, florencia_id, 'Carrera 45 #25-10, Florencia', NULL, 3500, 6.2710, -75.5810, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                        
                        -- Cliente 5: Sofia Rodriguez - Picacho
                        INSERT INTO customer (branch_id, name, phone1, phone2, active)
                        VALUES (branch_id_var, 'Sofia Rodriguez', '3005678901', NULL, true)
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO customer5_id;
                        
                        IF customer5_id IS NULL THEN
                            SELECT id INTO customer5_id FROM customer WHERE branch_id = branch_id_var AND phone1 = '3005678901' LIMIT 1;
                        END IF;
                        
                        IF customer5_id IS NOT NULL AND picacho_id IS NOT NULL THEN
                            INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary)
                            VALUES (customer5_id, picacho_id, 'Calle 80 #60-40, Picacho', NULL, 5000, 6.3110, -75.5410, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                        
                        -- Cliente 6: Diego Torres - Castilla
                        INSERT INTO customer (branch_id, name, phone1, phone2, active)
                        VALUES (branch_id_var, 'Diego Torres', '3106789012', NULL, true)
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO customer6_id;
                        
                        IF customer6_id IS NULL THEN
                            SELECT id INTO customer6_id FROM customer WHERE branch_id = branch_id_var AND phone1 = '3106789012' LIMIT 1;
                        END IF;
                        
                        IF customer6_id IS NOT NULL AND castilla_id IS NOT NULL THEN
                            INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary)
                            VALUES (customer6_id, castilla_id, 'Carrera 55 #35-25, Castilla', NULL, 3000, 6.2820, -75.5720, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                        
                        -- Cliente 7: Laura Sanchez - Santander
                        INSERT INTO customer (branch_id, name, phone1, phone2, active)
                        VALUES (branch_id_var, 'Laura Sanchez', '3207890123', NULL, true)
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO customer7_id;
                        
                        IF customer7_id IS NULL THEN
                            SELECT id INTO customer7_id FROM customer WHERE branch_id = branch_id_var AND phone1 = '3207890123' LIMIT 1;
                        END IF;
                        
                        IF customer7_id IS NOT NULL AND santander_id IS NOT NULL THEN
                            INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary)
                            VALUES (customer7_id, santander_id, 'Calle 75 #50-35, Santander', NULL, 4000, 6.2920, -75.5620, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                        
                        -- Cliente 8: Andres Lopez - Pedregal
                        INSERT INTO customer (branch_id, name, phone1, phone2, active)
                        VALUES (branch_id_var, 'Andres Lopez', '3158901234', NULL, true)
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO customer8_id;
                        
                        IF customer8_id IS NULL THEN
                            SELECT id INTO customer8_id FROM customer WHERE branch_id = branch_id_var AND phone1 = '3158901234' LIMIT 1;
                        END IF;
                        
                        IF customer8_id IS NOT NULL AND pedregal_id IS NOT NULL THEN
                            INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary)
                            VALUES (customer8_id, pedregal_id, 'Carrera 60 #40-20, Pedregal', NULL, 2500, 6.3020, -75.5520, true)
                            ON CONFLICT DO NOTHING;
                        END IF;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122123208_SeedInitialData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251122123208_SeedInitialData', '9.0.8');
    END IF;
END $EF$;
COMMIT;

