-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    neighborhood_id integer NOT NULL,
    address character varying(200) COLLATE pg_catalog."default" NOT NULL,
    additional_info character varying(150) COLLATE pg_catalog."default",
    delivery_fee integer NOT NULL,
    latitude numeric(10, 6),
    longitude numeric(10, 6),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT address_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.app
(
    id serial NOT NULL,
    bank_id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    image_url character varying(200) COLLATE pg_catalog."default",
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    CONSTRAINT app_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.app_payment
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    app_id integer NOT NULL,
    amount integer NOT NULL,
    is_setted boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT app_payment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bank
(
    id serial NOT NULL,
    branch_id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    image_url character varying(200) COLLATE pg_catalog."default",
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT bank_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bank_payment
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    bank_id integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    is_verified boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT bank_payment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.branch
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address character varying(200) COLLATE pg_catalog."default" NOT NULL,
    phone1 character varying(10) COLLATE pg_catalog."default" NOT NULL,
    phone2 character varying(10) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT branch_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id serial NOT NULL,
    branch_id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    phone1 character varying(10) COLLATE pg_catalog."default" NOT NULL,
    phone2 character varying(10) COLLATE pg_catalog."default",
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.expense
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category_id integer NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'unit'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT expense_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.expense_bank_payment
(
    id serial NOT NULL,
    bank_id integer NOT NULL,
    expense_header_id integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT expense_bank_payment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.expense_category
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT expense_category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.expense_detail
(
    id serial NOT NULL,
    header_id integer NOT NULL,
    expense_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    amount integer NOT NULL,
    total integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT expense_detail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.expense_header
(
    id serial NOT NULL,
    branch_id integer NOT NULL,
    supplier_id integer NOT NULL,
    total integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT expense_header_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.loyalty_rule
(
    id serial NOT NULL,
    branch_id integer NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    n_orders_needed integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT loyalty_rule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.neighborhood
(
    id serial NOT NULL,
    branch_id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    delivery_fee integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT neighborhood_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    id serial NOT NULL,
    branch_id integer NOT NULL,
    taken_by_id integer NOT NULL,
    customer_id integer,
    address_id integer,
    loyalty_rule_id integer,
    delivery_man_id integer,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    delivery_fee integer,
    reserved_for timestamp without time zone,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    status_times jsonb,
    subtotal integer NOT NULL DEFAULT 0,
    total integer NOT NULL DEFAULT 0,
    discount_total integer NOT NULL DEFAULT 0,
    notes character varying(200) COLLATE pg_catalog."default",
    cancelled_reason character varying(200) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_detail
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer DEFAULT 1,
    unit_price integer DEFAULT 0,
    discount integer DEFAULT 0,
    subtotal integer,
    notes character varying COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT order_detail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id serial NOT NULL,
    category_id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    stock integer,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_category
(
    id serial NOT NULL,
    branch_id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT product_category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.refresh_token
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    token character varying(500) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    is_revoked boolean DEFAULT false,
    revoked_at timestamp without time zone,
    replaced_by_token character varying(500) COLLATE pg_catalog."default",
    revoked_by_ip character varying(45) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT refresh_token_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_token_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.supplier
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(10) COLLATE pg_catalog."default" NOT NULL,
    address character varying(200) COLLATE pg_catalog."default",
    email character varying(200) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT supplier_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    branch_id integer NOT NULL,
    role character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(10) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT address_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_address_customer
    ON public.address(customer_id);


ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT address_neighborhood_id_fkey FOREIGN KEY (neighborhood_id)
    REFERENCES public.neighborhood (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_address_neighborhood
    ON public.address(neighborhood_id);


ALTER TABLE IF EXISTS public.app
    ADD CONSTRAINT app_bank_id_fkey FOREIGN KEY (bank_id)
    REFERENCES public.bank (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.app_payment
    ADD CONSTRAINT app_payment_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.app (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.app_payment
    ADD CONSTRAINT app_payment_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bank
    ADD CONSTRAINT bank_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bank_payment
    ADD CONSTRAINT bank_payment_bank_id_fkey FOREIGN KEY (bank_id)
    REFERENCES public.bank (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bank_payment
    ADD CONSTRAINT bank_payment_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT customer_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_customer_branch
    ON public.customer(branch_id);


ALTER TABLE IF EXISTS public.expense
    ADD CONSTRAINT expense_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.expense_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.expense_bank_payment
    ADD CONSTRAINT expense_bank_payment_bank_id_fkey FOREIGN KEY (bank_id)
    REFERENCES public.bank (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.expense_bank_payment
    ADD CONSTRAINT expense_bank_payment_expense_header_id_fkey FOREIGN KEY (expense_header_id)
    REFERENCES public.expense_header (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.expense_detail
    ADD CONSTRAINT expense_detail_expense_id_fkey FOREIGN KEY (expense_id)
    REFERENCES public.expense (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.expense_detail
    ADD CONSTRAINT expense_detail_header_id_fkey FOREIGN KEY (header_id)
    REFERENCES public.expense_header (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_expense_detail_header
    ON public.expense_detail(header_id);


ALTER TABLE IF EXISTS public.expense_header
    ADD CONSTRAINT expense_header_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_expense_header_branch
    ON public.expense_header(branch_id);


ALTER TABLE IF EXISTS public.expense_header
    ADD CONSTRAINT expense_header_supplier_id_fkey FOREIGN KEY (supplier_id)
    REFERENCES public.supplier (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_expense_header_supplier
    ON public.expense_header(supplier_id);


ALTER TABLE IF EXISTS public.loyalty_rule
    ADD CONSTRAINT loyalty_rule_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.neighborhood
    ADD CONSTRAINT neighborhood_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_address_id_fkey FOREIGN KEY (address_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_branch
    ON public."order"(branch_id);


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_customer
    ON public."order"(customer_id);


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_delivery_man_id_fkey FOREIGN KEY (delivery_man_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_delivery_man
    ON public."order"(delivery_man_id);


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_loyalty_rule_id_fkey FOREIGN KEY (loyalty_rule_id)
    REFERENCES public.loyalty_rule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_taken_by_id_fkey FOREIGN KEY (taken_by_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_detail
    ADD CONSTRAINT order_detail_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_detail_order
    ON public.order_detail(order_id);


ALTER TABLE IF EXISTS public.order_detail
    ADD CONSTRAINT order_detail_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_detail_product
    ON public.order_detail(product_id);


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.product_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_product_category
    ON public.product(category_id);


ALTER TABLE IF EXISTS public.product_category
    ADD CONSTRAINT product_category_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refresh_token
    ADD CONSTRAINT refresh_token_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id
    ON public.refresh_token(user_id);


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT user_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_user_branch
    ON public."user"(branch_id);

END;