using System.Text.Json;using Microsoft.EntityFrameworkCore;using SenorArroz.Application.Common.Interfaces;using SenorArroz.Application.Common.Models;using SenorArroz.Domain.Entities;using SenorArroz.Infrastructure.Data;
namespace SenorArroz.Infrastructure.Services;
internal static class AgentPhone{public static string Normalize(string value){var d=new string(value.Where(char.IsDigit).ToArray());return d.Length>10?d[^10..]:d;}}
public class FindCustomerByPhoneAgentTool(ApplicationDbContext db):IAgentTool
{
 public string Name=>"find_customer_by_phone";public string Description=>"Busca exclusivamente al cliente del número de la conversación.";public string Category=>"customers";public JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{},"additionalProperties":false}""").RootElement.Clone();
 public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var phone=AgentPhone.Normalize(c.PhoneNumber??string.Empty);var rows=await db.Customers.AsNoTracking().Include(x=>x.Addresses).ThenInclude(x=>x.Neighborhood).Where(x=>x.Active).ToListAsync(ct);var matches=rows.Where(x=>AgentPhone.Normalize(x.Phone1)==phone||(!string.IsNullOrWhiteSpace(x.Phone2)&&AgentPhone.Normalize(x.Phone2)==phone)).OrderByDescending(x=>x.BranchId==c.BranchId).ToList();if(matches.Count==0)return new(true,new{found=false},null,"customer_not_found","No existe un cliente asociado al número de la conversación.",true,"¿Cuál es tu nombre para registrarte?");var preferred=matches.Where(x=>x.BranchId==c.BranchId).ToList();if(preferred.Count!=1&&matches.Count>1)return new(false,new{found=false,matchCount=matches.Count},null,"customer_ambiguous","El teléfono está asociado a varios clientes y requiere revisión.",false,null,true);var x=preferred.SingleOrDefault()??matches[0];return new(true,new{found=true,customerId=x.Id,x.Name,phoneNumber=phone,addressCount=x.Addresses.Count,addresses=x.Addresses.Take(5).Select(y=>new{addressId=y.Id,address=y.AddressText,neighborhood=y.Neighborhood.Name,y.IsPrimary})},null,"customer_found");}
}
public class CreateCustomerAgentTool(ApplicationDbContext db):IAgentTool
{
 public string Name=>"create_customer";public string Description=>"Crea el cliente de la conversación usando su teléfono real; nunca acepta otro teléfono ni sucursal.";public string Category=>"customers";public bool ModifiesData=>true;public string RiskLevel=>"medium";public JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{"name":{"type":"string","minLength":2,"maxLength":150}},"required":["name"],"additionalProperties":false}""").RootElement.Clone();
 public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var name=a.GetProperty("name").GetString()?.Trim();if(string.IsNullOrWhiteSpace(name)||name.Length>150)return new(false,null,"Nombre inválido.","invalid_arguments");var phone=AgentPhone.Normalize(c.PhoneNumber??string.Empty);var existing=(await db.Customers.Where(x=>x.BranchId==c.BranchId).ToListAsync(ct)).FirstOrDefault(x=>AgentPhone.Normalize(x.Phone1)==phone);var conversation=await db.WhatsAppConversations.FirstAsync(x=>x.Id==c.ConversationId,ct);if(existing!=null){conversation.CustomerId=existing.Id;await db.SaveChangesAsync(ct);return new(true,new{customerId=existing.Id,existing.Name},null,"customer_exists","El cliente ya existía y fue asociado a la conversación.");}var customer=new Customer{BranchId=c.BranchId,Name=name,Phone1=phone,Active=true};db.Customers.Add(customer);await db.SaveChangesAsync(ct);conversation.CustomerId=customer.Id;await db.SaveChangesAsync(ct);return new(true,new{customerId=customer.Id,customer.Name,phoneNumber=phone},null,"customer_created","Cliente creado.");}
}
public class UpdateCustomerAgentTool(ApplicationDbContext db):IAgentTool
{
 public string Name=>"update_customer";public string Description=>"Actualiza únicamente el nombre del cliente asociado a la conversación.";public string Category=>"customers";public bool ModifiesData=>true;public string RiskLevel=>"medium";public JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{"name":{"type":"string","minLength":2,"maxLength":150}},"required":["name"],"additionalProperties":false}""").RootElement.Clone();
 public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){if(!c.CustomerId.HasValue)return new(false,null,"La conversación no tiene cliente asociado.","customer_not_found");var name=a.GetProperty("name").GetString()?.Trim();if(string.IsNullOrWhiteSpace(name)||name.Length>150)return new(false,null,"Nombre inválido.","invalid_arguments");var customer=await db.Customers.FirstOrDefaultAsync(x=>x.Id==c.CustomerId&&x.Active,ct);if(customer==null)return new(false,null,"Cliente no encontrado.","customer_not_found");customer.Name=name;await db.SaveChangesAsync(ct);return new(true,new{customerId=customer.Id,customer.Name},null,"customer_updated","Cliente actualizado.");}
}
public class ListCustomerAddressesAgentTool(ApplicationDbContext db,IWhatsAppAutomaticMessageSender? sender=null):IAgentTool
{
 public string Name=>"list_customer_addresses";public string Description=>"Lista únicamente direcciones del cliente asociado a la conversación.";public string Category=>"addresses";public JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{},"additionalProperties":false}""").RootElement.Clone();
 public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){if(!c.CustomerId.HasValue)return new(false,null,"Se requiere cliente.","customer_not_found");var rows=await db.Addresses.AsNoTracking().Include(x=>x.Neighborhood).Where(x=>x.CustomerId==c.CustomerId).OrderByDescending(x=>x.IsPrimary).ThenBy(x=>x.Id).Take(3).Select(x=>new{addressId=x.Id,address=x.AddressText,x.AdditionalInfo,neighborhood=x.Neighborhood.Name,x.IsPrimary,hasCoverage=x.Neighborhood.Active&&x.Neighborhood.BranchId==c.BranchId}).ToListAsync(ct);if(sender is not null&&rows.Count>1){var buttons=rows.Select(x=>new WhatsAppReplyButton($"address:{x.addressId}",$"{x.addressId}: {x.address}")).ToList();await sender.SendAgentReplyButtonsAsync(c.ConversationId,$"{c.ExecutionId??$"msg-{c.IncomingMessageId}"}:addresses","�En cu�l direcci�n entregamos?",buttons,ct);}return new(true,new{addresses=rows,selectionButtonsSent=rows.Count>1,suggestedAddressId=rows.FirstOrDefault(x=>x.IsPrimary&&x.hasCoverage)?.addressId??(rows.Count(x=>x.hasCoverage)==1?rows.First(x=>x.hasCoverage).addressId:(int?)null)},null,rows.Count==0?"address_required":"addresses_found",rows.Count==0?"El cliente no tiene direcciones.":null,rows.Count==0,rows.Count==0?"¿Cuál es la dirección del domicilio?":null);}
}
public class CreateCustomerAddressAgentTool(ApplicationDbContext db,RegisteredNeighborhoodResolver resolver):IAgentTool
{
 public string Name=>"create_customer_address";public string Description=>"Crea una dirección solo después de validar el barrio registrado; cliente, sucursal y domicilio se resuelven internamente.";public string Category=>"addresses";public bool ModifiesData=>true;public string RiskLevel=>"medium";public JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{"address":{"type":"string","maxLength":500},"neighborhood":{"type":"string","maxLength":150},"additionalInfo":{"type":"string","maxLength":500},"latitude":{"type":"number"},"longitude":{"type":"number"}},"required":["address","neighborhood"],"additionalProperties":false}""").RootElement.Clone();
 public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){if(!c.CustomerId.HasValue)return new(false,null,"Se requiere cliente.","customer_not_found");var address=a.GetProperty("address").GetString()?.Trim();var neighborhood=a.GetProperty("neighborhood").GetString()?.Trim();if(string.IsNullOrWhiteSpace(address)||string.IsNullOrWhiteSpace(neighborhood))return new(false,null,"Dirección y barrio son requeridos.","invalid_arguments");var coverage=await resolver.Resolve(neighborhood,c.BranchId,ct);if(!coverage.Matched)return new(false,new{options=coverage.Options.Select(x=>x.Name)},null,coverage.RequiresConfirmation?"confirmation_required":"address_out_of_coverage",coverage.RequiresConfirmation?"El barrio es ambiguo.":"El barrio no está registrado.",coverage.RequiresConfirmation,coverage.SuggestedQuestion);if(coverage.Match!.RequiresBranchReassignment)return new(false,new{coverage.Match.Name,coverage.Match.BranchName},null,"branch_reassignment_required","La dirección corresponde a otra sucursal.",true,$"Tu dirección corresponde a {coverage.Match.BranchName}. ¿Deseas continuar?");var duplicate=await db.Addresses.AnyAsync(x=>x.CustomerId==c.CustomerId&&x.NeighborhoodId==coverage.Match.Id&&x.AddressText.ToLower()==address.ToLower(),ct);if(duplicate)return new(false,null,"La dirección ya existe.","address_exists");decimal? lat=a.TryGetProperty("latitude",out var la)&&la.TryGetDecimal(out var lav)?lav:null;decimal? lng=a.TryGetProperty("longitude",out var lo)&&lo.TryGetDecimal(out var lov)?lov:null;var row=new Address{CustomerId=c.CustomerId.Value,NeighborhoodId=coverage.Match.Id,AddressText=address,AdditionalInfo=a.TryGetProperty("additionalInfo",out var ai)?ai.GetString()?.Trim():null,Latitude=lat,Longitude=lng,DeliveryFee=coverage.Match.DeliveryFee,IsPrimary=!await db.Addresses.AnyAsync(x=>x.CustomerId==c.CustomerId,ct)};db.Addresses.Add(row);await db.SaveChangesAsync(ct);return new(true,new{addressId=row.Id,address=row.AddressText,neighborhood=coverage.Match.Name,deliveryFee=coverage.Match.DeliveryFee,row.IsPrimary},null,"address_created","Dirección creada.");}
}
public class SaveValidatedCustomerAddressAgentTool(ApplicationDbContext db,RegisteredNeighborhoodResolver resolver,GoogleAddressGeocoder geocoder,WhatsAppDraftService drafts,IClock clock):IAgentTool
{
 public string Name=>"save_validated_customer_address";public string Description=>"Valida con Maps y barrios activos, guarda la dirección del cliente de la conversación y la asocia al borrador.";public string Category=>"addresses";public bool ModifiesData=>true;public string RiskLevel=>"medium";public JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{"originalAddress":{"type":"string","maxLength":500},"latitude":{"type":"number"},"longitude":{"type":"number"},"additionalInfo":{"type":"string","maxLength":150},"instructions":{"type":"string","maxLength":500}},"required":["originalAddress"],"additionalProperties":false}""").RootElement.Clone();
 public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){if(!c.CustomerId.HasValue)return new(false,null,"Cliente requerido.","customer_not_found");var original=a.GetProperty("originalAddress").GetString()?.Trim();decimal? lat=a.TryGetProperty("latitude",out var la)&&la.TryGetDecimal(out var lav)?lav:null;decimal? lng=a.TryGetProperty("longitude",out var lo)&&lo.TryGetDecimal(out var lov)?lov:null;var(g,error)=await geocoder.Resolve(original,lat,lng,ct);if(g==null)return new(false,null,error,"address_not_validated");if(string.IsNullOrWhiteSpace(g.Neighborhood))return new(false,null,"Maps no identificó un barrio.","address_out_of_coverage");var coverage=await resolver.Resolve(g.Neighborhood,c.BranchId,ct);if(!coverage.Matched)return new(false,new{options=coverage.Options.Select(x=>x.Name)},null,coverage.RequiresConfirmation?"confirmation_required":"address_out_of_coverage",coverage.RequiresConfirmation?"Confirma el barrio.":"El barrio detectado no está habilitado.",coverage.RequiresConfirmation,coverage.SuggestedQuestion);if(coverage.Match!.RequiresBranchReassignment)return new(false,new{coverage.Match.Name,coverage.Match.BranchName},null,"branch_reassignment_required","La dirección corresponde a otra sucursal.",true,$"La dirección corresponde a {coverage.Match.BranchName}. ¿Deseas reasignar la conversación?");var normalized=g.FormattedAddress.Trim();var duplicate=await db.Addresses.FirstOrDefaultAsync(x=>x.CustomerId==c.CustomerId&&x.NeighborhoodId==coverage.Match.Id&&(x.NormalizedAddressText==normalized||x.AddressText==normalized),ct);var row=duplicate??new Address{CustomerId=c.CustomerId.Value,NeighborhoodId=coverage.Match.Id,IsPrimary=!await db.Addresses.AnyAsync(x=>x.CustomerId==c.CustomerId,ct)};row.OriginalAddressText=original;row.NormalizedAddressText=normalized;row.AddressText=normalized;row.Latitude=g.Latitude;row.Longitude=g.Longitude;row.AdditionalInfo=a.TryGetProperty("additionalInfo",out var ai)?ai.GetString()?.Trim():null;row.Instructions=a.TryGetProperty("instructions",out var ins)?ins.GetString()?.Trim():null;row.ValidationSource="google_maps";row.ValidatedAt=clock.UtcNow;row.DeliveryFee=coverage.Match.DeliveryFee;if(duplicate==null)db.Addresses.Add(row);await db.SaveChangesAsync(ct);var draft=await drafts.GetOrCreate(c,ct);draft.CustomerId=c.CustomerId;draft.AddressId=row.Id;draft.BranchId=c.BranchId;draft.OrderType=SenorArroz.Domain.Enums.OrderType.Delivery;await db.SaveChangesAsync(ct);draft=await drafts.Recalculate(draft.Id,ct);return new(true,new{addressId=row.Id,address=normalized,neighborhood=coverage.Match.Name,deliveryFee=coverage.Match.DeliveryFee,draftId=draft.Id},null,duplicate==null?"address_created":"address_updated","Dirección validada y asociada al borrador.");}
}
