using System.Text.Json;using Microsoft.EntityFrameworkCore;using SenorArroz.Application.Common.Interfaces;using SenorArroz.Application.Common.Models;using SenorArroz.Domain.Enums;using SenorArroz.Infrastructure.Data;
namespace SenorArroz.Infrastructure.Services;
public class SelectCustomerAddressAgentTool(WhatsAppDraftService drafts,ApplicationDbContext db):DraftToolBase(drafts)
{
 public override string Name=>"select_customer_address";public override string Description=>"Selecciona en el borrador una dirección válida del cliente de la conversación.";public override JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{"addressId":{"type":"integer"}},"additionalProperties":false}""").RootElement.Clone();
 public override async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct)
 {
  if(!c.CustomerId.HasValue)return new(false,null,"Cliente requerido.","customer_not_found");
  int? addressId=a.TryGetProperty("addressId",out var requested)&&requested.TryGetInt32(out var parsed)?parsed:null;
  var incoming=c.IncomingMessageId.HasValue?await db.WhatsAppMessages.AsNoTracking().Where(x=>x.Id==c.IncomingMessageId&&x.ConversationId==c.ConversationId).Select(x=>x.TextBody).FirstOrDefaultAsync(ct):null;
  if(!addressId.HasValue)
  {
   var normalized=SenorArroz.Application.Common.Services.WhatsAppConversationPolicy.Normalize(incoming);
   var buttonMatch=System.Text.RegularExpressions.Regex.Match(normalized,@"^(?:(?:seleccionar )?direccion|address) (?<id>\d+)$");
   if(buttonMatch.Success)addressId=int.Parse(buttonMatch.Groups["id"].Value);
   else if(normalized is "si" or "si ese" or "esa" or "ahi")
   {
    var valid=await db.Addresses.Include(x=>x.Neighborhood).Where(x=>x.CustomerId==c.CustomerId&&x.Neighborhood.Active&&x.Neighborhood.BranchId==c.BranchId).OrderByDescending(x=>x.IsPrimary).ThenBy(x=>x.Id).Take(3).ToListAsync(ct);
    addressId=valid.FirstOrDefault(x=>x.IsPrimary)?.Id??(valid.Count==1?valid[0].Id:null);
   }
   if(!addressId.HasValue)return new(false,null,"El cliente debe elegir una dirección válida.","address_clarification_required");
  }
  var address=await db.Addresses.Include(x=>x.Neighborhood).FirstOrDefaultAsync(x=>x.Id==addressId&&x.CustomerId==c.CustomerId&&x.Neighborhood.Active&&x.Neighborhood.BranchId==c.BranchId,ct);
  if(address==null)return new(false,null,"La dirección no es válida para este cliente y sucursal.","address_not_found");
  var d=await Drafts.GetOrCreate(c,ct);d.CustomerId=c.CustomerId;d.AddressId=address.Id;d.OrderType=OrderType.Delivery;await db.SaveChangesAsync(ct);d=await Drafts.Recalculate(d.Id,ct);return new(true,WhatsAppDraftService.Summary(d),null,"draft_updated");
 }
}
public class CalculateDeliveryFeeAgentTool(WhatsAppDraftService drafts):DraftToolBase(drafts){public override string Name=>"calculate_delivery_fee";public override string Description=>"Recalcula el domicilio exclusivamente desde el barrio de la dirección seleccionada.";public override bool ModifiesData=>false;public override JsonElement ParametersSchema=>GetOrCreateOrderDraftAgentTool.Empty;public override async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var d=await Drafts.ActiveDraft(c.ConversationId,ct);if(d==null)return new(false,null,"Borrador no encontrado.","draft_not_found");d=await Drafts.Recalculate(d.Id,ct);return d.OrderType==OrderType.Delivery&&d.AddressId==null?new(false,null,"Dirección requerida.","address_required"):new(true,new{cost=d.DeliveryFee,isFree=d.DeliveryFee==0,reason=d.OrderType==OrderType.Delivery?"Tarifa actual del barrio registrado.":"La recogida no tiene domicilio.",ruleApplied=d.DeliveryFee==0?"no_delivery":"registered_neighborhood_fee"},null,"delivery_fee_calculated");}}
public class ListPaymentMethodsAgentTool(ApplicationDbContext db):IAgentTool{public string Name=>"list_payment_methods";public string Description=>"Lista efectivo y cuentas activas reales de la sucursal.";public string Category=>"payments";public JsonElement ParametersSchema=>GetOrCreateOrderDraftAgentTool.Empty;public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var banks=await db.Banks.AsNoTracking().Where(x=>x.BranchId==c.BranchId&&x.Active&&x.Type==BankType.Normal).Select(x=>new{paymentMethodId=x.Id,name=x.Name,type="bank_transfer"}).ToListAsync(ct);var methods=new List<object>{new{paymentMethodId=0,name="Efectivo",type="cash"}};methods.AddRange(banks);return new(true,methods,null,"payment_methods_found");}}
public class SetPaymentMethodAgentTool(WhatsAppDraftService drafts,ApplicationDbContext db):DraftToolBase(drafts){public override string Name=>"set_payment_method";public override string Description=>"Guarda un método real por identificador; cero representa efectivo.";public override JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{"paymentMethodId":{"type":"integer","minimum":0}},"required":["paymentMethodId"],"additionalProperties":false}""").RootElement.Clone();public override async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var id=a.GetProperty("paymentMethodId").GetInt32();if(id!=0&&!await db.Banks.AnyAsync(x=>x.Id==id&&x.BranchId==c.BranchId&&x.Active&&x.Type==BankType.Normal,ct))return new(false,null,"Método no disponible para la sucursal.","payment_method_not_found");var d=await Drafts.GetOrCreate(c,ct);d.PaymentMethod=id==0?"cash":"bank_transfer";d.PaymentMethodId=id==0?null:id;if(id!=0){d.CashReceived=null;d.ChangeAmount=null;}await db.SaveChangesAsync(ct);d=await Drafts.Recalculate(d.Id,ct);return new(true,WhatsAppDraftService.Summary(d),null,"draft_updated");}}
public class CalculateCashChangeAgentTool(WhatsAppDraftService drafts,ApplicationDbContext db):DraftToolBase(drafts){public override string Name=>"calculate_cash_change";public override string Description=>"Calcula el cambio usando el total actual del backend; solo para efectivo.";public override JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{"cashReceived":{"type":"integer","minimum":0}},"required":["cashReceived"],"additionalProperties":false}""").RootElement.Clone();public override async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var d=await Drafts.ActiveDraft(c.ConversationId,ct);if(d==null)return new(false,null,"Borrador no encontrado.","draft_not_found");if(d.PaymentMethod!="cash")return new(false,null,"El cambio solo aplica a efectivo.","payment_method_invalid");d=await Drafts.Recalculate(d.Id,ct);var received=a.GetProperty("cashReceived").GetInt32();if(received<d.Total)return new(false,new{d.Total,cashReceived=received},null,"cash_insufficient","El efectivo entregado es inferior al total.",true,"¿Con cuánto vas a pagar?");d.CashReceived=received;d.ChangeAmount=received-d.Total;d.Version++;await db.SaveChangesAsync(ct);return new(true,new{d.Total,cashReceived=received,change=d.ChangeAmount},null,"cash_change_calculated");}}
public class GetOrderConfirmationSummaryAgentTool(WhatsAppDraftService drafts):DraftToolBase(drafts){public override string Name=>"get_order_confirmation_summary";public override string Description=>"Recalcula y devuelve el resumen; nunca confirma el pedido.";public override bool ModifiesData=>false;public override JsonElement ParametersSchema=>GetOrCreateOrderDraftAgentTool.Empty;public override async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var d=await Drafts.ActiveDraft(c.ConversationId,ct);if(d==null)return new(false,null,"Borrador no encontrado.","draft_not_found");d=await Drafts.Recalculate(d.Id,ct);return new(true,new{summary=WhatsAppDraftService.Summary(d),requiresExplicitConfirmation=true},null,"confirmation_required",null,true,"¿Confirmas que deseas realizar este pedido?");}}
public class MarkDraftReadyAgentTool(WhatsAppDraftService drafts,ApplicationDbContext db):DraftToolBase(drafts){public override string Name=>"mark_draft_ready_for_confirmation";public override string Description=>"Marca listo solo si todos los datos y productos actuales son válidos.";public override JsonElement ParametersSchema=>GetOrCreateOrderDraftAgentTool.Empty;public override async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var d=await Drafts.ActiveDraft(c.ConversationId,ct);if(d==null)return new(false,null,"Borrador no encontrado.","draft_not_found");d=await Drafts.Recalculate(d.Id,ct);var missing=WhatsAppDraftService.Missing(d);if(missing.Length>0)return new(false,new{missing},null,"draft_incomplete","Faltan datos para confirmar.",true);if(d.Items.Any(x=>!x.Product.Active||(x.Product.Stock.HasValue&&x.Product.Stock<x.Quantity)))return new(false,null,"Un producto ya no está disponible.","product_unavailable");d.Status=WhatsAppOrderDraftStatus.ReadyForConfirmation;d.Version++;await db.SaveChangesAsync(ct);return new(true,new{summary=WhatsAppDraftService.Summary(d),requiresExplicitConfirmation=true},null,"confirmation_required",null,true,"¿Confirmas el pedido?");}}
