using System.Text.Json;using Microsoft.EntityFrameworkCore;using SenorArroz.Application.Common.Interfaces;using SenorArroz.Application.Common.Models;using SenorArroz.Application.Common.Services;using SenorArroz.Infrastructure.Data;
namespace SenorArroz.Infrastructure.Services;
public class SendProductDetailsAgentTool(ApplicationDbContext db,IWhatsAppAutomaticMessageSender sender):IAgentTool
{
 public string Name=>"send_product_details";public string Description=>"Envía al cliente la foto y ficha real de un producto de la sucursal, sin cambiar a atención humana.";public string Category=>"messaging";public bool ModifiesData=>true;public string RiskLevel=>"medium";public JsonElement ParametersSchema=>JsonDocument.Parse("""{"type":"object","properties":{"productId":{"type":"integer"}},"required":["productId"],"additionalProperties":false}""").RootElement.Clone();
 public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var id=a.GetProperty("productId").GetInt32();var p=await db.Products.AsNoTracking().Include(x=>x.Category).Include(x=>x.CommercialProfile).FirstOrDefaultAsync(x=>x.Id==id&&x.Category.BranchId==c.BranchId,ct);if(p==null)return new(false,null,"Producto no encontrado.","product_not_found");var available=p.Active&&(!p.Stock.HasValue||p.Stock>0);if(!available)return new(false,new{productId=p.Id,p.Name},"Producto no disponible.","product_unavailable");var serves=p.ServesPeopleMin==p.ServesPeopleMax&&p.ServesPeopleMin.HasValue?$"{p.ServesPeopleMin} {(p.ServesPeopleMin==1?"persona":"personas")}":p.ServesPeopleMin.HasValue?$"{p.ServesPeopleMin}-{p.ServesPeopleMax} personas":null;var text=string.Join("\n",new[]{p.Name,p.CommercialProfile?.Description,string.IsNullOrWhiteSpace(p.CommercialProfile?.Ingredients)?null:$"Ingredientes: {p.CommercialProfile.Ingredients}",serves==null?null:$"Rinde para {serves}",$"Precio: ${p.Price:N0}","Disponible"}.Where(x=>!string.IsNullOrWhiteSpace(x)));var key=Key(c,$"product:{p.Id}");var sent=await sender.SendAgentContentAsync(c.ConversationId,key,text,p.CommercialProfile?.PhotoUrl,ct);return sent.Success?new(true,new{sent=true,productId=p.Id,withImage=!string.IsNullOrWhiteSpace(p.CommercialProfile?.PhotoUrl)},null,"product_details_sent","La ficha ya fue enviada al cliente."):new(false,null,sent.Error,"message_send_failed",Retryable:sent.TransientFailure);}
 internal static string Key(AgentToolExecutionContext c,string suffix)=>$"{c.ExecutionId??$"msg-{c.IncomingMessageId??0}"}:{suffix}";
}
public class SendMenuAgentTool(ApplicationDbContext db,IWhatsAppAutomaticMessageSender sender):IAgentTool
{
 public string Name=>"send_menu";public string Description=>"Envía las imágenes de carta configuradas para la sucursal, sin inventar enlaces ni cambiar el modo de atención.";public string Category=>"messaging";public bool ModifiesData=>true;public string RiskLevel=>"medium";public JsonElement ParametersSchema=>AgentToolSchemas.EmptyObject;
 public async Task<AgentToolExecutionResult> ExecuteAsync(AgentToolExecutionContext c,JsonElement a,CancellationToken ct){var branch=await db.Branches.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==c.BranchId,ct);if(branch==null)return new(false,null,"Sucursal no encontrada.","branch_not_found");var images=new[]{branch.MenuImageUrl1,branch.MenuImageUrl2}.Where(x=>!string.IsNullOrWhiteSpace(x)).Cast<string>().ToList();if(images.Count==0)return new(false,null,"Esta sucursal no tiene carta configurada.","menu_not_configured");var sent=0;for(var i=0;i<images.Count;i++){var caption=i==0?"Nuestra carta actual":"Carta (continuación)";var result=await sender.SendAgentContentAsync(c.ConversationId,SendProductDetailsAgentTool.Key(c,$"menu:{i+1}"),caption,images[i],ct);if(!result.Success)return new(false,new{sentImages=sent,totalImages=images.Count},result.Error,"message_send_failed",Retryable:result.TransientFailure,Warnings:sent>0?["La carta se envió parcialmente."]:null);sent++;}return new(true,new{sent=true,imageCount=sent},null,"menu_sent","La carta ya fue enviada al cliente.");}
}
