using Microsoft.EntityFrameworkCore;
using SenorArroz.Application.Common.Interfaces;
using SenorArroz.Application.Common.Models;
using SenorArroz.Application.Common.Services;
using SenorArroz.Infrastructure.Data;
namespace SenorArroz.Infrastructure.Services;
public class WhatsAppProductMatcher(ApplicationDbContext db):IWhatsAppProductMatcher
{
 private static readonly HashSet<string> Ignored=new(["hola","dame","quiero","necesito","agrega","agregame","por","favor","uno","una","un","el","la","los","las","para","persona","personas","arroz","voy","a","pedir","ponme","mandame","me","si","lo","venden"],StringComparer.Ordinal);
 public async Task<WhatsAppProductMatchResult> MatchAsync(int branchId,string? query,int? servesPeople,int limit=10,CancellationToken ct=default){var normalized=WhatsAppConversationPolicy.Normalize(query);servesPeople??=InferPeople(normalized);var browseAll=normalized is "si lo venden" or "si venden";var terms=normalized.Split(' ',StringSplitOptions.RemoveEmptyEntries).Where(x=>!Ignored.Contains(x)&&!int.TryParse(x,out _)).Select(Singular).Distinct().ToArray();var cleaned=string.Join(' ',terms);var rows=await db.Products.AsNoTracking().Include(x=>x.Category).Include(x=>x.CommercialProfile).Where(x=>x.Category.BranchId==branchId).ToListAsync(ct);if(servesPeople.HasValue){rows=rows.Where(x=>x.ServesPeopleMin.HasValue&&x.ServesPeopleMax.HasValue&&x.ServesPeopleMin<=servesPeople&&x.ServesPeopleMax>=servesPeople).ToList();if(rows.Count==0)return new(cleaned,servesPeople,false,false,false,[],true);}var candidates=rows.Select(x=>Score(x,cleaned,terms,servesPeople)).Where(x=>browseAll||x.Score>=.35||servesPeople.HasValue&&terms.Length==0).OrderByDescending(x=>x.Score).ThenByDescending(x=>x.Available).ThenBy(x=>x.Name).Take(Math.Clamp(limit,1,3)).ToList();var exact=candidates.Count>0&&candidates[0].MatchType is "exact_name" or "exact_commercial_profile";var clear=candidates.Count==1&&candidates[0].Score>=.72||candidates.Count>1&&candidates[0].Score>=.82&&candidates[0].Score-candidates[1].Score>=.18;return new(cleaned,servesPeople,exact,!exact&&candidates.Count>0,!clear&&candidates.Count>1,candidates);}
 private static WhatsAppProductMatchCandidate Score(Domain.Entities.Product p,string query,string[] terms,int? people){var name=WhatsAppConversationPolicy.Normalize(p.Name);var profile=WhatsAppConversationPolicy.Normalize(p.CommercialProfile?.Name);var nameTerms=name.Split(' ',StringSplitOptions.RemoveEmptyEntries).Select(Singular).ToArray();string type;double score;if(query.Length>0&&query==string.Join(' ',nameTerms)){type="exact_name";score=1;}else if(query.Length>0&&query==string.Join(' ',profile.Split(' ',StringSplitOptions.RemoveEmptyEntries).Select(Singular))){type="exact_commercial_profile";score=.97;}else{var profileTerms=profile.Split(' ',StringSplitOptions.RemoveEmptyEntries).Select(Singular).ToArray();var matched=terms.Count(t=>nameTerms.Any(n=>n==t||Similarity(n,t)>=.78)||profileTerms.Any(n=>n==t||Similarity(n,t)>=.78));var coverage=terms.Length==0?0:(double)matched/terms.Length;var ordered=query.Length==0?0:Similarity(string.Join(' ',nameTerms),query);score=Math.Max(coverage*.82,ordered*.7);type=coverage==1&&terms.Length>0?"all_terms":"partial";}if(people.HasValue&&p.ServesPeopleMin<=people&&p.ServesPeopleMax>=people){score=Math.Min(1,score+.22);if(type=="partial"&&terms.Length==0)type="serves_people";}return new(p.Id,p.Name,p.Price,p.Active&&(!p.Stock.HasValue||p.Stock>0),p.ServesPeopleMin,p.ServesPeopleMax,type,Math.Round(score,3));}
 private static int? InferPeople(string value){if(value.Split(' ').Contains("2")||value.Contains("dos persona"))return 2;if(value.Split(' ').Contains("3")||value.Contains("tres persona"))return 3;if(value.Split(' ').Contains("4")||value.Contains("cuatro persona"))return 4;return null;}
 private static string Singular(string value)=>value.Length>4&&value.EndsWith("es",StringComparison.Ordinal)?value[..^2]:value.Length>3&&value.EndsWith('s')?value[..^1]:value;
 private static double Similarity(string a,string b){if(a==b)return 1;if(a.Length==0||b.Length==0)return 0;var d=new int[b.Length+1];for(var j=0;j<=b.Length;j++)d[j]=j;for(var i=1;i<=a.Length;i++){var previous=d[0];d[0]=i;for(var j=1;j<=b.Length;j++){var old=d[j];d[j]=Math.Min(Math.Min(d[j]+1,d[j-1]+1),previous+(a[i-1]==b[j-1]?0:1));previous=old;}}return 1-(double)d[b.Length]/Math.Max(a.Length,b.Length);}
}
