using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using SenorArroz.Application.Common.Interfaces;using SenorArroz.Domain.Entities;using SenorArroz.Shared.Models;
namespace SenorArroz.API.Controllers;
[ApiController,Authorize(Roles="Superadmin, Admin"),Route("api/branches/{branchId:int}/business-hours")]
public class BranchBusinessHoursController(IApplicationDbContext db,ICurrentUser currentUser,IBranchBusinessHoursService service):ControllerBase
{
 [HttpGet]public async Task<ActionResult<ApiResponse<IReadOnlyList<BranchBusinessHourDto>>>> Get(int branchId,CancellationToken ct){if(!Access(branchId))return Forbid();if(!await db.Branches.AnyAsync(x=>x.Id==branchId,ct))return NotFound();return Ok(ApiResponse<IReadOnlyList<BranchBusinessHourDto>>.SuccessResponse(await service.GetBusinessHours(branchId,ct)));}
 [HttpPut]public async Task<ActionResult<ApiResponse<IReadOnlyList<BranchBusinessHourDto>>>> Put(int branchId,[FromBody]List<BranchBusinessHourDto> values,CancellationToken ct){if(!Access(branchId))return Forbid();if(!await db.Branches.AnyAsync(x=>x.Id==branchId,ct))return NotFound();if(values.Count!=7||values.Any(x=>!Enum.IsDefined(x.DayOfWeek))||values.Select(x=>x.DayOfWeek).Distinct().Count()!=7)return BadRequest(ApiResponse<IReadOnlyList<BranchBusinessHourDto>>.ErrorResponse("El horario debe contener exactamente una vez cada día de domingo a sábado."));if(values.Any(x=>x.IsClosed&&(x.OpenTime!=null||x.CloseTime!=null)))return BadRequest(ApiResponse<IReadOnlyList<BranchBusinessHourDto>>.ErrorResponse("Los días cerrados no pueden incluir horas."));if(values.Any(x=>!x.IsClosed&&(x.OpenTime is null||x.CloseTime is null)))return BadRequest(ApiResponse<IReadOnlyList<BranchBusinessHourDto>>.ErrorResponse("Los días abiertos requieren apertura y cierre."));if(values.Any(x=>!x.IsClosed&&x.CloseTime<=x.OpenTime))return BadRequest(ApiResponse<IReadOnlyList<BranchBusinessHourDto>>.ErrorResponse("El cierre debe ser posterior a la apertura; no se admiten horarios que atraviesen medianoche."));var old=await db.BranchBusinessHours.Where(x=>x.BranchId==branchId).ToListAsync(ct);db.BranchBusinessHours.RemoveRange(old);foreach(var v in values){var order=v.DayOfWeek==DayOfWeek.Sunday?6:(int)v.DayOfWeek-1;db.BranchBusinessHours.Add(new BranchBusinessHour{BranchId=branchId,DayOfWeek=v.DayOfWeek,IsClosed=v.IsClosed,OpenTime=v.IsClosed?null:v.OpenTime,CloseTime=v.IsClosed?null:v.CloseTime,DisplayOrder=order});}await db.SaveChangesAsync(ct);return Ok(ApiResponse<IReadOnlyList<BranchBusinessHourDto>>.SuccessResponse(await service.GetBusinessHours(branchId,ct),"Horario semanal reemplazado."));}
 private bool Access(int id)=>Roles.IsSuperadmin(currentUser.Role)||(Roles.IsAdmin(currentUser.Role)&&currentUser.BranchId==id);
}
