BEGIN;

ALTER TABLE delivery_work_session
    ADD COLUMN IF NOT EXISTS stay_analysis_last_location_id bigint;

CREATE INDEX IF NOT EXISTS idx_dloc_work_session_id
    ON deliveryman_location(work_session_id, id);

CREATE TABLE IF NOT EXISTS delivery_stay (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deliveryman_id integer NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    work_session_id integer NOT NULL REFERENCES delivery_work_session(id) ON DELETE RESTRICT,
    delivery_route_id integer REFERENCES delivery_route(id) ON DELETE SET NULL,
    nearest_order_id integer REFERENCES "order"(id) ON DELETE SET NULL,
    first_location_id bigint NOT NULL,
    last_location_id bigint NOT NULL,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone NOT NULL,
    duration_seconds integer NOT NULL,
    center_latitude numeric(10,6) NOT NULL,
    center_longitude numeric(10,6) NOT NULL,
    radius_meters double precision NOT NULL,
    average_accuracy_meters double precision NOT NULL,
    distance_to_branch_meters double precision,
    distance_to_nearest_order_meters double precision,
    point_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_stay_duration CHECK (duration_seconds >= 0),
    CONSTRAINT ck_delivery_stay_radius CHECK (radius_meters >= 0),
    CONSTRAINT ck_delivery_stay_accuracy CHECK (average_accuracy_meters >= 0),
    CONSTRAINT ck_delivery_stay_points CHECK (point_count >= 3)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_stay_session_first_location
    ON delivery_stay(work_session_id, first_location_id);

CREATE INDEX IF NOT EXISTS idx_delivery_stay_session_started
    ON delivery_stay(work_session_id, started_at);

CREATE INDEX IF NOT EXISTS idx_delivery_stay_deliveryman_started
    ON delivery_stay(deliveryman_id, started_at);

CREATE INDEX IF NOT EXISTS idx_delivery_stay_route
    ON delivery_stay(delivery_route_id);

COMMIT;
