BEGIN;

CREATE TABLE IF NOT EXISTS delivery_routing_plan (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    generation_number bigint NOT NULL,
    status varchar(32) NOT NULL,
    generated_at_utc timestamptz NOT NULL,
    input_fingerprint varchar(128) NOT NULL,
    available_slot_count integer NOT NULL DEFAULT 0,
    soon_slot_count integer NOT NULL DEFAULT 0,
    solver_duration_ms integer NOT NULL DEFAULT 0,
    matrix_source varchar(32) NOT NULL DEFAULT 'approximate',
    warnings varchar(4000),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_routing_plan_generation
    ON delivery_routing_plan(branch_id, generation_number);
CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_routing_plan_active
    ON delivery_routing_plan(branch_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_delivery_routing_plan_branch_status
    ON delivery_routing_plan(branch_id, status);

CREATE TABLE IF NOT EXISTS delivery_route_proposal (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_routing_plan_id integer NOT NULL REFERENCES delivery_routing_plan(id) ON DELETE CASCADE,
    sequence integer NOT NULL,
    status varchar(32) NOT NULL,
    recommendation varchar(32) NOT NULL,
    expected_departure_at_utc timestamptz NOT NULL,
    wait_seconds integer NOT NULL DEFAULT 0,
    approximate_driving_duration_seconds integer NOT NULL DEFAULT 0,
    approximate_distance_meters integer NOT NULL DEFAULT 0,
    validated_driving_duration_seconds integer,
    validated_distance_meters integer,
    google_validation_status varchar(32) NOT NULL DEFAULT 'not_requested',
    last_delivery_seconds integer NOT NULL DEFAULT 0,
    worst_age_at_delivery_seconds integer NOT NULL DEFAULT 0,
    direction_spread_degrees double precision NOT NULL DEFAULT 0,
    score bigint NOT NULL DEFAULT 0,
    claimed_by_deliveryman_id integer REFERENCES "user"(id) ON DELETE RESTRICT,
    claimed_at_utc timestamptz,
    planning_warnings varchar(4000),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_delivery_route_proposal_sequence UNIQUE(delivery_routing_plan_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_delivery_route_proposal_plan_status
    ON delivery_route_proposal(delivery_routing_plan_id, status);

CREATE TABLE IF NOT EXISTS delivery_route_proposal_stop (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_routing_plan_id integer NOT NULL REFERENCES delivery_routing_plan(id) ON DELETE CASCADE,
    delivery_route_proposal_id integer REFERENCES delivery_route_proposal(id) ON DELETE CASCADE,
    order_id integer NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    stop_sequence integer,
    estimated_ready_at_utc timestamptz NOT NULL,
    estimated_arrival_at_utc timestamptz,
    travel_from_previous_seconds integer NOT NULL DEFAULT 0,
    service_seconds integer NOT NULL DEFAULT 0,
    bearing_from_branch_degrees double precision NOT NULL DEFAULT 0,
    was_ready_at_generation boolean NOT NULL DEFAULT false,
    is_suggested_wait boolean NOT NULL DEFAULT false,
    unrouted_reason varchar(256),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_delivery_route_proposal_stop_plan_order UNIQUE(delivery_routing_plan_id, order_id)
);

CREATE INDEX IF NOT EXISTS idx_delivery_route_proposal_stop_sequence
    ON delivery_route_proposal_stop(delivery_route_proposal_id, stop_sequence);

COMMIT;
