BEGIN;

CREATE TABLE IF NOT EXISTS public.business_document (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL,
    name varchar(200) NOT NULL,
    download_url varchar(2048) NOT NULL,
    storage_object_name varchar(512) NOT NULL,
    original_file_name varchar(255) NOT NULL,
    content_type varchar(100) NOT NULL DEFAULT 'application/pdf',
    file_size_bytes bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_business_document_file_size
        CHECK (file_size_bytes > 0 AND file_size_bytes <= 26214400)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_business_document_public_id
    ON public.business_document(public_id);
CREATE INDEX IF NOT EXISTS ix_business_document_name
    ON public.business_document(name);
CREATE INDEX IF NOT EXISTS ix_business_document_updated_at
    ON public.business_document(updated_at);

COMMIT;
