BEGIN;

CREATE TABLE IF NOT EXISTS delivery_tracking_alert (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id integer NOT NULL,
    deliveryman_id integer NOT NULL,
    work_session_id integer,
    incident_id bigint,
    source_device_event_id bigint,
    deduplication_key varchar(160) NOT NULL,
    alert_type varchar(50) NOT NULL,
    severity varchar(30) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    title varchar(160) NOT NULL,
    message varchar(1000) NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    last_occurred_at timestamp with time zone NOT NULL,
    occurrence_count integer NOT NULL DEFAULT 1,
    resolved_at timestamp with time zone,
    resolved_by_user_id integer,
    resolution_reason varchar(500),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_tracking_alert_type CHECK (alert_type IN (
        'gps_disabled', 'location_permission_revoked', 'no_communication',
        'unexpected_stay', 'offline_locations_queued', 'session_past_auto_close'
    )),
    CONSTRAINT ck_delivery_tracking_alert_severity CHECK (severity IN (
        'informational', 'warning', 'requires_review', 'critical'
    )),
    CONSTRAINT ck_delivery_tracking_alert_status CHECK (status IN ('active', 'resolved')),
    CONSTRAINT ck_delivery_tracking_alert_occurrence_count CHECK (occurrence_count > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_tracking_alert_dedup
    ON delivery_tracking_alert(deduplication_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_tracking_alert_device_event
    ON delivery_tracking_alert(source_device_event_id)
    WHERE source_device_event_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_tracking_alert_incident
    ON delivery_tracking_alert(incident_id)
    WHERE incident_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_delivery_tracking_alert_admin
    ON delivery_tracking_alert(branch_id, status, severity, occurred_at);
CREATE INDEX IF NOT EXISTS idx_delivery_tracking_alert_session
    ON delivery_tracking_alert(work_session_id, alert_type, status);

COMMIT;
