CREATE TABLE IF NOT EXISTS public.email_outbox_message (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    message_type character varying(100) NOT NULL,
    to_emails_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    subject character varying(500) NOT NULL,
    body text NOT NULL,
    is_html boolean NOT NULL DEFAULT true,
    status character varying(50) NOT NULL DEFAULT 'pending',
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 5,
    last_attempted_at timestamp with time zone,
    next_attempt_at timestamp with time zone,
    sent_at timestamp with time zone,
    last_error character varying(4000),
    related_entity_type character varying(100),
    related_entity_id integer,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_email_outbox_message" PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_email_outbox_message_status_next_attempt
    ON public.email_outbox_message (status, next_attempt_at);

CREATE INDEX IF NOT EXISTS ix_email_outbox_message_related
    ON public.email_outbox_message (related_entity_type, related_entity_id);

CREATE INDEX IF NOT EXISTS ix_email_outbox_message_created_at
    ON public.email_outbox_message (created_at);
