BEGIN;

CREATE TABLE IF NOT EXISTS storefront_analytics_daily (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    event_date date NOT NULL,
    event_name varchar(64) NOT NULL,
    path varchar(160) NOT NULL DEFAULT '',
    utm_source varchar(80) NOT NULL DEFAULT '',
    utm_medium varchar(80) NOT NULL DEFAULT '',
    utm_campaign varchar(120) NOT NULL DEFAULT '',
    utm_content varchar(120) NOT NULL DEFAULT '',
    utm_term varchar(120) NOT NULL DEFAULT '',
    branch_id integer NOT NULL DEFAULT 0,
    fulfillment_type varchar(24) NOT NULL DEFAULT '',
    payment_type varchar(24) NOT NULL DEFAULT '',
    status_code integer NOT NULL DEFAULT 0,
    coverage_state smallint NOT NULL DEFAULT 0,
    event_count bigint NOT NULL DEFAULT 0,
    value_sum numeric(18,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_storefront_analytics_daily_dimensions
ON storefront_analytics_daily (
    tenant_id, event_date, event_name, path,
    utm_source, utm_medium, utm_campaign, utm_content, utm_term,
    branch_id, fulfillment_type, payment_type, status_code, coverage_state
);

CREATE INDEX IF NOT EXISTS ix_storefront_analytics_daily_event
ON storefront_analytics_daily (tenant_id, event_date, event_name);

ALTER TABLE storefront_analytics_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE storefront_analytics_daily FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON storefront_analytics_daily;
DROP POLICY IF EXISTS tenant_select_policy ON storefront_analytics_daily;
DROP POLICY IF EXISTS tenant_insert_policy ON storefront_analytics_daily;
DROP POLICY IF EXISTS tenant_update_policy ON storefront_analytics_daily;
DROP POLICY IF EXISTS tenant_delete_policy ON storefront_analytics_daily;

CREATE POLICY tenant_select_policy ON storefront_analytics_daily
FOR SELECT USING (app.is_system_scope() OR tenant_id = app.current_tenant_id());

CREATE POLICY tenant_insert_policy ON storefront_analytics_daily
FOR INSERT WITH CHECK (app.is_system_scope() OR tenant_id = app.current_tenant_id());

CREATE POLICY tenant_update_policy ON storefront_analytics_daily
FOR UPDATE USING (app.is_system_scope() OR tenant_id = app.current_tenant_id())
WITH CHECK (app.is_system_scope() OR tenant_id = app.current_tenant_id());

CREATE POLICY tenant_delete_policy ON storefront_analytics_daily
FOR DELETE USING (app.is_system_scope() OR tenant_id = app.current_tenant_id());

COMMIT;
