BEGIN;

CREATE TABLE IF NOT EXISTS commercial_profile (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE CASCADE,
    name varchar(150) NOT NULL,
    description varchar(2000) NULL,
    ingredients varchar(2000) NULL,
    photo_url varchar(2000) NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_commercial_profile_branch_name
    ON commercial_profile(branch_id, name);

ALTER TABLE product ADD COLUMN IF NOT EXISTS commercial_profile_id integer NULL;
ALTER TABLE product ADD COLUMN IF NOT EXISTS serves_people_min integer NULL;
ALTER TABLE product ADD COLUMN IF NOT EXISTS serves_people_max integer NULL;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS menu_image_url_1 varchar(2000) NULL;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS menu_image_url_2 varchar(2000) NULL;

DO $$ BEGIN
    ALTER TABLE product ADD CONSTRAINT fk_product_commercial_profile
        FOREIGN KEY (commercial_profile_id) REFERENCES commercial_profile(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE product ADD CONSTRAINT ck_product_serves_people
        CHECK ((serves_people_min IS NULL AND serves_people_max IS NULL)
            OR (serves_people_min > 0 AND serves_people_max >= serves_people_min));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS ix_product_commercial_profile_id ON product(commercial_profile_id);
COMMIT;
