BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS tenant (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    display_name varchar(160) NOT NULL,
    slug varchar(100) NOT NULL,
    contact_name varchar(160) NOT NULL,
    contact_email varchar(254) NOT NULL,
    contact_phone varchar(32),
    legal_name varchar(200),
    tax_id varchar(64),
    billing_address varchar(500),
    status varchar(20) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'Active', 'Suspended', 'Cancelled')),
    status_reason varchar(500),
    access_version bigint NOT NULL DEFAULT 1,
    suspended_at timestamptz,
    cancelled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenant_public_id UNIQUE (public_id),
    CONSTRAINT uq_tenant_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS platform_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    email varchar(254) NOT NULL,
    password_hash varchar(255) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_user_email_ci ON platform_user (lower(email));

CREATE TABLE IF NOT EXISTS platform_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_user_id integer NOT NULL REFERENCES platform_user(id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL UNIQUE,
    csrf_token_hash varchar(64) NOT NULL,
    ip_address varchar(64) NOT NULL DEFAULT '',
    user_agent varchar(500) NOT NULL DEFAULT '',
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_platform_session_user_active ON platform_session(platform_user_id, expires_at) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS platform_otp_challenge (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    platform_user_id integer NOT NULL REFERENCES platform_user(id) ON DELETE CASCADE,
    code_hash varchar(255) NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 5,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    ip_address varchar(64) NOT NULL DEFAULT '',
    user_agent varchar(500) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS platform_trusted_device (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    platform_user_id integer NOT NULL REFERENCES platform_user(id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL UNIQUE,
    name varchar(120) NOT NULL,
    user_agent varchar(500) NOT NULL DEFAULT '',
    ip_address varchar(64) NOT NULL DEFAULT '',
    expires_at timestamptz NOT NULL,
    last_used_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS platform_setting (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key varchar(120) NOT NULL UNIQUE,
    value_json jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS saas_module (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(80) NOT NULL UNIQUE,
    name varchar(160) NOT NULL,
    description varchar(500) NOT NULL DEFAULT '',
    category varchar(80) NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS saas_addon (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(80) NOT NULL UNIQUE,
    name varchar(160) NOT NULL,
    description varchar(500) NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS saas_plan (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(80) NOT NULL UNIQUE,
    name varchar(160) NOT NULL,
    description varchar(500) NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS saas_plan_version (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES saas_plan(id) ON DELETE RESTRICT,
    version_number integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'Published', 'Retired')),
    currency varchar(3) NOT NULL DEFAULT 'COP',
    monthly_price numeric(18,2),
    annual_price numeric(18,2),
    branch_limit integer CHECK (branch_limit IS NULL OR branch_limit > 0),
    user_limit integer CHECK (user_limit IS NULL OR user_limit > 0),
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_saas_plan_version UNIQUE (plan_id, version_number)
);

CREATE TABLE IF NOT EXISTS saas_plan_version_module (
    plan_version_id integer NOT NULL REFERENCES saas_plan_version(id) ON DELETE CASCADE,
    module_id integer NOT NULL REFERENCES saas_module(id) ON DELETE RESTRICT,
    PRIMARY KEY (plan_version_id, module_id)
);

CREATE TABLE IF NOT EXISTS tenant_subscription (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    plan_version_id integer NOT NULL REFERENCES saas_plan_version(id) ON DELETE RESTRICT,
    status varchar(20) NOT NULL CHECK (status IN ('Active', 'Ended')),
    starts_at timestamptz NOT NULL,
    ends_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_active_subscription ON tenant_subscription(tenant_id) WHERE status = 'Active';

CREATE TABLE IF NOT EXISTS tenant_addon (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    addon_id integer NOT NULL REFERENCES saas_addon(id) ON DELETE RESTRICT,
    active boolean NOT NULL DEFAULT false,
    enabled_at timestamptz,
    disabled_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenant_addon UNIQUE (tenant_id, addon_id)
);

CREATE TABLE IF NOT EXISTS tenant_invitation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    branch_id integer NOT NULL,
    user_id integer NOT NULL,
    email varchar(254) NOT NULL,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS platform_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_user_id integer REFERENCES platform_user(id) ON DELETE RESTRICT,
    actor_identifier varchar(254) NOT NULL DEFAULT '',
    action varchar(120) NOT NULL,
    entity_type varchar(120) NOT NULL,
    entity_id varchar(120) NOT NULL,
    before_json jsonb NOT NULL DEFAULT 'null',
    after_json jsonb NOT NULL DEFAULT 'null',
    ip_address varchar(64) NOT NULL DEFAULT '',
    correlation_id varchar(100) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_platform_audit_created ON platform_audit_log(created_at DESC);
ALTER TABLE platform_audit_log ALTER COLUMN platform_user_id DROP NOT NULL;
ALTER TABLE platform_audit_log ADD COLUMN IF NOT EXISTS actor_identifier varchar(254) NOT NULL DEFAULT '';
UPDATE platform_audit_log audit SET actor_identifier = platform.email
FROM platform_user platform
WHERE audit.platform_user_id = platform.id AND audit.actor_identifier = '';

CREATE TABLE IF NOT EXISTS tenant_usage_monthly (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    month date NOT NULL,
    orders bigint NOT NULL DEFAULT 0,
    storage_bytes bigint NOT NULL DEFAULT 0,
    ai_input_tokens bigint NOT NULL DEFAULT 0,
    ai_output_tokens bigint NOT NULL DEFAULT 0,
    ai_estimated_cost_usd numeric(18,6) NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenant_usage_month UNIQUE (tenant_id, month)
);

INSERT INTO tenant (display_name, slug, contact_name, contact_email, status)
VALUES ('Señor Arroz', 'senor-arroz', 'Señor Arroz', 'santyvano@outlook.com', 'Active')
ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, updated_at = now();

INSERT INTO saas_module (code, name, category, display_order) VALUES
('pos', 'POS, pedidos y reservas', 'operación', 10),
('customers', 'Clientes y direcciones', 'operación', 20),
('catalog', 'Productos, categorías y stock', 'operación', 30),
('kitchen', 'Cocina', 'operación', 40),
('users', 'Usuarios y roles', 'administración', 50),
('basic_payments', 'Pagos básicos', 'finanzas', 60),
('printing', 'Impresión', 'operación', 70),
('loyalty', 'Promociones y fidelización', 'comercial', 80),
('basic_settings', 'Configuración básica', 'administración', 90),
('basic_dashboard', 'Dashboard operativo básico', 'analítica', 100),
('multi_branch', 'Multi-sucursal', 'administración', 110),
('expenses', 'Gastos y proveedores', 'finanzas', 120),
('cash_register', 'Caja, transferencias y conciliación', 'finanzas', 130),
('delivery_operations', 'Domiciliarios y app móvil', 'operación', 140),
('business_documents', 'Documentos empresariales', 'administración', 150),
('advanced_dashboard', 'Dashboard avanzado', 'analítica', 160),
('delivery_routing', 'Enrutamiento optimizado', 'logística', 170),
('delivery_tracking', 'GPS, alertas e incidentes', 'logística', 180),
('advanced_audit', 'Auditoría monetaria y operativa', 'auditoría', 190),
('cost_attribution', 'Imputación y análisis de costos', 'finanzas', 200),
('full_analytics', 'Analítica completa', 'analítica', 210)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, display_order = EXCLUDED.display_order;

INSERT INTO saas_addon (code, name, description, display_order) VALUES
('whatsapp_ai', 'WhatsApp e IA', 'Habilita WhatsApp y automatización con IA; no incluye costos externos.', 10),
('rappi', 'Integración Rappi', 'Habilita la integración operativa con Rappi; no incluye costos externos.', 20)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, display_order = EXCLUDED.display_order;

INSERT INTO saas_plan (code, name, description) VALUES
('essential', 'Esencial', 'Operación esencial para una sucursal.'),
('professional', 'Profesional', 'Operación financiera y multi-sucursal.'),
('unlimited', 'Ilimitado', 'Capacidades completas sin límite de sucursales ni usuarios.')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, updated_at = now();

INSERT INTO saas_plan_version (plan_id, version_number, status, currency, branch_limit, user_limit, published_at)
SELECT id, 1, 'Published', 'COP', CASE code WHEN 'essential' THEN 1 WHEN 'professional' THEN 3 ELSE NULL END,
       CASE code WHEN 'essential' THEN 10 WHEN 'professional' THEN 30 ELSE NULL END, now()
FROM saas_plan
ON CONFLICT (plan_id, version_number) DO NOTHING;

INSERT INTO saas_plan_version_module (plan_version_id, module_id)
SELECT version.id, module.id
FROM saas_plan_version version
JOIN saas_plan plan ON plan.id = version.plan_id AND version.version_number = 1
JOIN saas_module module ON
    module.code IN ('pos','customers','catalog','kitchen','users','basic_payments','printing','loyalty','basic_settings','basic_dashboard')
    OR plan.code IN ('professional','unlimited') AND module.code IN ('multi_branch','expenses','cash_register','delivery_operations','business_documents','advanced_dashboard')
    OR plan.code = 'unlimited' AND module.code IN ('delivery_routing','delivery_tracking','advanced_audit','cost_attribution','full_analytics')
ON CONFLICT DO NOTHING;

INSERT INTO tenant_subscription (tenant_id, plan_version_id, status, starts_at)
SELECT tenant.id, version.id, 'Active', now()
FROM tenant
JOIN saas_plan plan ON plan.code = 'unlimited'
JOIN saas_plan_version version ON version.plan_id = plan.id AND version.version_number = 1
WHERE tenant.slug = 'senor-arroz'
ON CONFLICT (tenant_id) WHERE status = 'Active' DO NOTHING;

DO $$
DECLARE
    initial_tenant_id integer;
    item record;
    excluded_tables text[] := ARRAY[
        'tenant','platform_user','platform_session','platform_otp_challenge','platform_trusted_device','platform_setting',
        'saas_module','saas_addon','saas_plan','saas_plan_version','saas_plan_version_module','tenant_subscription',
        'tenant_addon','tenant_invitation','platform_audit_log','tenant_usage_monthly','__EFMigrationsHistory','spatial_ref_sys'
    ];
BEGIN
    SELECT id INTO initial_tenant_id FROM tenant WHERE slug = 'senor-arroz';
    FOR item IN
        SELECT tablename FROM pg_tables
        WHERE schemaname = 'public' AND NOT (tablename = ANY(excluded_tables))
    LOOP
        EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS tenant_id integer', item.tablename);
        EXECUTE format('UPDATE public.%I SET tenant_id = $1 WHERE tenant_id IS NULL', item.tablename) USING initial_tenant_id;
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN tenant_id SET NOT NULL', item.tablename);
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conrelid = format('public.%I', item.tablename)::regclass AND conname = left('fk_mt_' || item.tablename || '_tenant', 63)
        ) THEN
            EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE RESTRICT NOT VALID', item.tablename, left('fk_mt_' || item.tablename || '_tenant', 63));
        END IF;
        EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I (tenant_id)', left('idx_mt_' || item.tablename || '_tenant', 63), item.tablename);
    END LOOP;
END $$;

DO $$
DECLARE item record;
BEGIN
    FOR item IN
        SELECT ns.nspname AS schema_name, relation.relname AS table_name, constraint_row.conname AS constraint_name
        FROM pg_constraint constraint_row
        JOIN pg_class relation ON relation.oid = constraint_row.conrelid
        JOIN pg_namespace ns ON ns.oid = relation.relnamespace
        WHERE ns.nspname = 'public' AND constraint_row.contype = 'f' AND NOT constraint_row.convalidated
          AND constraint_row.conname LIKE 'fk_mt_%'
    LOOP
        EXECUTE format('ALTER TABLE %I.%I VALIDATE CONSTRAINT %I', item.schema_name, item.table_name, item.constraint_name);
    END LOOP;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_branch_id_tenant ON branch(id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_id_tenant ON "user"(id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email_ci ON "user"(lower(email));
CREATE INDEX IF NOT EXISTS idx_branch_tenant_name ON branch(tenant_id, lower(name));
CREATE INDEX IF NOT EXISTS idx_user_tenant_branch ON "user"(tenant_id, branch_id);

DO $$
DECLARE
    fk record;
    constraint_name text;
BEGIN
    FOR fk IN
        SELECT source_ns.nspname AS schema_name, source.relname AS table_name, source_column.attname AS column_name,
               target.relname AS target_table
        FROM pg_constraint constraint_row
        JOIN pg_class source ON source.oid = constraint_row.conrelid
        JOIN pg_namespace source_ns ON source_ns.oid = source.relnamespace
        JOIN pg_class target ON target.oid = constraint_row.confrelid
        JOIN pg_attribute source_column ON source_column.attrelid = source.oid AND source_column.attnum = constraint_row.conkey[1]
        WHERE constraint_row.contype = 'f' AND array_length(constraint_row.conkey, 1) = 1
          AND source_ns.nspname = 'public' AND target.relname IN ('branch', 'user')
          AND source.relname NOT IN ('tenant_invitation')
    LOOP
        constraint_name := left('fk_mt_' || fk.table_name || '_' || fk.column_name || '_tenant', 63);
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = format('%I.%I', fk.schema_name, fk.table_name)::regclass AND conname = constraint_name) THEN
            EXECUTE format('ALTER TABLE %I.%I ADD CONSTRAINT %I FOREIGN KEY (%I, tenant_id) REFERENCES public.%I(id, tenant_id) ON DELETE RESTRICT NOT VALID',
                fk.schema_name, fk.table_name, constraint_name, fk.column_name, fk.target_table);
        END IF;
    END LOOP;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tenant_invitation_branch_tenant' AND conrelid = 'tenant_invitation'::regclass) THEN
        ALTER TABLE tenant_invitation ADD CONSTRAINT fk_tenant_invitation_branch_tenant FOREIGN KEY (branch_id, tenant_id) REFERENCES branch(id, tenant_id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tenant_invitation_user_tenant' AND conrelid = 'tenant_invitation'::regclass) THEN
        ALTER TABLE tenant_invitation ADD CONSTRAINT fk_tenant_invitation_user_tenant FOREIGN KEY (user_id, tenant_id) REFERENCES "user"(id, tenant_id) ON DELETE RESTRICT;
    END IF;
END $$;

DO $$
DECLARE item record;
BEGIN
    FOR item IN
        SELECT ns.nspname AS schema_name, relation.relname AS table_name, constraint_row.conname AS constraint_name
        FROM pg_constraint constraint_row
        JOIN pg_class relation ON relation.oid = constraint_row.conrelid
        JOIN pg_namespace ns ON ns.oid = relation.relnamespace
        WHERE ns.nspname = 'public' AND constraint_row.contype = 'f' AND NOT constraint_row.convalidated
          AND constraint_row.conname LIKE 'fk_mt_%'
    LOOP
        EXECUTE format('ALTER TABLE %I.%I VALIDATE CONSTRAINT %I', item.schema_name, item.table_name, item.constraint_name);
    END LOOP;
END $$;

INSERT INTO platform_user (name, email, password_hash)
SELECT source.name, lower(source.email), source.password_hash
FROM "user" source
WHERE lower(source.email) = 'santyvano@outlook.com'
  AND NOT EXISTS (SELECT 1 FROM platform_user platform WHERE lower(platform.email) = lower(source.email))
ORDER BY source.id
LIMIT 1;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM platform_user WHERE lower(email) = 'santyvano@outlook.com') THEN
        RAISE EXCEPTION 'No se encontrÃ³ el usuario operativo santyvano@outlook.com para copiar su hash.';
    END IF;
END $$;

DO $$
DECLARE has_rows boolean;
BEGIN
    IF to_regclass('public.whatsapp_branch_setting') IS NOT NULL THEN
        EXECUTE 'SELECT EXISTS (SELECT 1 FROM public.whatsapp_branch_setting WHERE is_active AND is_verified)' INTO has_rows;
    END IF;
    IF COALESCE(has_rows, false) THEN
        INSERT INTO tenant_addon (tenant_id, addon_id, active, enabled_at, updated_at)
        SELECT tenant.id, addon.id, true, now(), now() FROM tenant CROSS JOIN saas_addon addon
        WHERE tenant.slug = 'senor-arroz' AND addon.code = 'whatsapp_ai'
        ON CONFLICT (tenant_id, addon_id) DO UPDATE SET active = true, enabled_at = COALESCE(tenant_addon.enabled_at, now()), disabled_at = NULL, updated_at = now();
    END IF;
    has_rows := false;
    IF to_regclass('public.delivery_app_connection') IS NOT NULL THEN
        EXECUTE $query$SELECT EXISTS (
            SELECT 1
            FROM public.delivery_app_connection
            WHERE is_active
              AND is_verified
              AND lower(provider) = 'rappi'
        )$query$ INTO has_rows;
    END IF;
    IF COALESCE(has_rows, false) THEN
        INSERT INTO tenant_addon (tenant_id, addon_id, active, enabled_at, updated_at)
        SELECT tenant.id, addon.id, true, now(), now() FROM tenant CROSS JOIN saas_addon addon
        WHERE tenant.slug = 'senor-arroz' AND addon.code = 'rappi'
        ON CONFLICT (tenant_id, addon_id) DO UPDATE SET active = true, enabled_at = COALESCE(tenant_addon.enabled_at, now()), disabled_at = NULL, updated_at = now();
    END IF;
END $$;

CREATE OR REPLACE FUNCTION enforce_tenant_plan_quota() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    allowed integer;
    current_count integer;
BEGIN
    PERFORM pg_advisory_xact_lock(NEW.tenant_id, CASE WHEN TG_TABLE_NAME = 'branch' THEN 1 ELSE 2 END);
    IF TG_TABLE_NAME = 'branch' THEN
        SELECT version.branch_limit INTO allowed FROM tenant_subscription subscription
        JOIN saas_plan_version version ON version.id = subscription.plan_version_id
        WHERE subscription.tenant_id = NEW.tenant_id AND subscription.status = 'Active';
        SELECT count(*) INTO current_count FROM branch WHERE tenant_id = NEW.tenant_id;
    ELSE
        SELECT version.user_limit INTO allowed FROM tenant_subscription subscription
        JOIN saas_plan_version version ON version.id = subscription.plan_version_id
        WHERE subscription.tenant_id = NEW.tenant_id AND subscription.status = 'Active';
        SELECT count(*) INTO current_count FROM "user" WHERE tenant_id = NEW.tenant_id;
    END IF;
    IF allowed IS NOT NULL AND current_count >= allowed THEN
        RAISE EXCEPTION 'Se alcanzó la cuota de % del plan.', TG_TABLE_NAME USING ERRCODE = 'P0001';
    END IF;
    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_branch_tenant_quota ON branch;
CREATE TRIGGER trg_branch_tenant_quota BEFORE INSERT ON branch FOR EACH ROW EXECUTE FUNCTION enforce_tenant_plan_quota();
DROP TRIGGER IF EXISTS trg_user_tenant_quota ON "user";
CREATE TRIGGER trg_user_tenant_quota BEFORE INSERT ON "user" FOR EACH ROW EXECUTE FUNCTION enforce_tenant_plan_quota();

CREATE OR REPLACE FUNCTION measure_tenant_order_usage() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO tenant_usage_monthly(tenant_id, month, orders, updated_at)
    VALUES (NEW.tenant_id, date_trunc('month', now())::date, 1, now())
    ON CONFLICT (tenant_id, month) DO UPDATE SET orders = tenant_usage_monthly.orders + 1, updated_at = now();
    RETURN NEW;
END $$;

DO $$ BEGIN
    IF to_regclass('public.order') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS trg_measure_tenant_order_usage ON public."order"';
        EXECUTE 'CREATE TRIGGER trg_measure_tenant_order_usage AFTER INSERT ON public."order" FOR EACH ROW EXECUTE FUNCTION measure_tenant_order_usage()';
    END IF;
END $$;

CREATE OR REPLACE FUNCTION measure_tenant_ai_usage() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO tenant_usage_monthly(tenant_id, month, ai_input_tokens, ai_output_tokens, ai_estimated_cost_usd, updated_at)
    VALUES (NEW.tenant_id, date_trunc('month', now())::date, COALESCE(NEW.input_tokens, 0), COALESCE(NEW.output_tokens, 0), COALESCE(NEW.estimated_cost_usd, 0), now())
    ON CONFLICT (tenant_id, month) DO UPDATE SET
        ai_input_tokens = tenant_usage_monthly.ai_input_tokens + EXCLUDED.ai_input_tokens,
        ai_output_tokens = tenant_usage_monthly.ai_output_tokens + EXCLUDED.ai_output_tokens,
        ai_estimated_cost_usd = tenant_usage_monthly.ai_estimated_cost_usd + EXCLUDED.ai_estimated_cost_usd,
        updated_at = now();
    RETURN NEW;
END $$;

DO $$ BEGIN
    IF to_regclass('public.whatsapp_ai_invocation') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS trg_measure_tenant_ai_usage ON public.whatsapp_ai_invocation';
        EXECUTE 'CREATE TRIGGER trg_measure_tenant_ai_usage AFTER INSERT ON public.whatsapp_ai_invocation FOR EACH ROW EXECUTE FUNCTION measure_tenant_ai_usage()';
    END IF;
END $$;

DO $$
DECLARE item record;
BEGIN
    FOR item IN
        SELECT table_schema, table_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND column_name = 'tenant_id'
          AND table_name NOT IN ('tenant_subscription','tenant_addon','tenant_invitation','tenant_usage_monthly')
    LOOP
        EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY', item.table_schema, item.table_name);
        EXECUTE format('ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY', item.table_schema, item.table_name);
        EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I.%I', item.table_schema, item.table_name);
        EXECUTE format(
            'CREATE POLICY tenant_isolation ON %I.%I USING (current_setting(''app.tenant_bypass'', true) = ''true'' OR tenant_id = NULLIF(current_setting(''app.current_tenant_id'', true), '''')::integer) WITH CHECK (current_setting(''app.tenant_bypass'', true) = ''true'' OR tenant_id = NULLIF(current_setting(''app.current_tenant_id'', true), '''')::integer)',
            item.table_schema, item.table_name);
    END LOOP;
END $$;

INSERT INTO platform_setting(key, value_json) VALUES
('support_email', '"santyvano@outlook.com"'::jsonb),
('default_currency', '"COP"'::jsonb),
('default_timezone', '"America/Bogota"'::jsonb),
('otp_expiration_minutes', '"10"'::jsonb),
('invitation_expiration_hours', '"72"'::jsonb),
('trusted_device_days', '"30"'::jsonb)
ON CONFLICT (key) DO NOTHING;

COMMIT;
