BEGIN;

ALTER TABLE expense ADD COLUMN IF NOT EXISTS tracks_inventory boolean NOT NULL DEFAULT false;
ALTER TABLE expense ADD COLUMN IF NOT EXISTS inventory_active boolean NOT NULL DEFAULT false;
ALTER TABLE expense ADD COLUMN IF NOT EXISTS inventory_base_unit varchar(20) NOT NULL DEFAULT 'unit';
ALTER TABLE product ADD COLUMN IF NOT EXISTS inventory_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE product ADD COLUMN IF NOT EXISTS inventory_control_mode varchar(20) NOT NULL DEFAULT 'estimated';
UPDATE product p
SET inventory_control_mode = 'strict'
FROM product_category c
WHERE p.category_id = c.id AND c.storefront_role = 'beverage' AND p.inventory_enabled = false;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS inventory_issue varchar(500);
ALTER TABLE expense_header ADD COLUMN IF NOT EXISTS inventory_operation_key varchar(120);
CREATE UNIQUE INDEX IF NOT EXISTS ux_expense_header_inventory_operation ON expense_header(tenant_id, inventory_operation_key) WHERE inventory_operation_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS expense_unit_conversion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    expense_id integer NOT NULL REFERENCES expense(id) ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    base_quantity numeric(18,4) NOT NULL CHECK (base_quantity > 0),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_expense_unit_conversion_name ON expense_unit_conversion(tenant_id, expense_id, name);

ALTER TABLE expense_detail ADD COLUMN IF NOT EXISTS inventory_conversion_id integer REFERENCES expense_unit_conversion(id) ON DELETE RESTRICT;
ALTER TABLE expense_detail ADD COLUMN IF NOT EXISTS inventory_base_quantity numeric(18,4);
ALTER TABLE expense_detail ADD COLUMN IF NOT EXISTS inventory_unit_cost numeric(18,6);

CREATE TABLE IF NOT EXISTS product_expense_requirement (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    product_id integer NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    expense_id integer NOT NULL REFERENCES expense(id) ON DELETE RESTRICT,
    base_quantity numeric(18,4) NOT NULL CHECK (base_quantity > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_product_expense_requirement ON product_expense_requirement(tenant_id, product_id, expense_id);

CREATE TABLE IF NOT EXISTS inventory_balance (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    expense_id integer NOT NULL REFERENCES expense(id) ON DELETE RESTRICT,
    quantity_on_hand numeric(18,4) NOT NULL DEFAULT 0,
    quantity_reserved numeric(18,4) NOT NULL DEFAULT 0,
    average_unit_cost numeric(18,6) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE inventory_balance DROP CONSTRAINT IF EXISTS ck_inventory_balance_reserved_nonnegative;
ALTER TABLE inventory_balance ADD CONSTRAINT ck_inventory_balance_reserved_nonnegative CHECK (quantity_reserved >= 0);
ALTER TABLE inventory_balance DROP CONSTRAINT IF EXISTS ck_inventory_balance_average_cost;
ALTER TABLE inventory_balance ADD CONSTRAINT ck_inventory_balance_average_cost CHECK (average_unit_cost >= 0);
ALTER TABLE inventory_balance DROP CONSTRAINT IF EXISTS ck_inventory_balance_reserved;
ALTER TABLE inventory_balance ADD CONSTRAINT ck_inventory_balance_reserved CHECK (quantity_reserved <= GREATEST(quantity_on_hand, 0));
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_balance_scope ON inventory_balance(tenant_id, branch_id, expense_id);

CREATE TABLE IF NOT EXISTS inventory_transfer (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    source_branch_id integer NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    destination_branch_id integer NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    operation_key varchar(160) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'draft',
    created_by_id integer NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    dispatched_by_id integer REFERENCES "user"(id) ON DELETE RESTRICT,
    dispatched_at timestamptz,
    received_by_id integer REFERENCES "user"(id) ON DELETE RESTRICT,
    received_at timestamptz,
    difference_reason varchar(500),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_inventory_transfer_branches CHECK (source_branch_id <> destination_branch_id),
    CONSTRAINT ck_inventory_transfer_status CHECK (status IN ('draft','dispatched','received','received_with_difference'))
);
ALTER TABLE inventory_transfer ADD COLUMN IF NOT EXISTS operation_key varchar(160);
UPDATE inventory_transfer SET operation_key = 'legacy-transfer:' || id WHERE operation_key IS NULL;
ALTER TABLE inventory_transfer ALTER COLUMN operation_key SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_transfer_operation ON inventory_transfer(tenant_id, operation_key);
CREATE INDEX IF NOT EXISTS ix_inventory_transfer_pending ON inventory_transfer(tenant_id, destination_branch_id, status);

CREATE TABLE IF NOT EXISTS inventory_transfer_line (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    transfer_id integer NOT NULL REFERENCES inventory_transfer(id) ON DELETE CASCADE,
    expense_id integer NOT NULL REFERENCES expense(id) ON DELETE RESTRICT,
    quantity numeric(18,4) NOT NULL CHECK (quantity > 0),
    received_quantity numeric(18,4),
    unit_cost numeric(18,6) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_transfer_line ON inventory_transfer_line(tenant_id, transfer_id, expense_id);

CREATE TABLE IF NOT EXISTS inventory_count (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    status varchar(20) NOT NULL DEFAULT 'draft',
    created_by_id integer NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    confirmed_by_id integer REFERENCES "user"(id) ON DELETE RESTRICT,
    confirmed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_inventory_count_status CHECK (status IN ('draft','confirmed'))
);
CREATE INDEX IF NOT EXISTS ix_inventory_count_branch ON inventory_count(tenant_id, branch_id, status);

CREATE TABLE IF NOT EXISTS inventory_count_line (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    inventory_count_id integer NOT NULL REFERENCES inventory_count(id) ON DELETE CASCADE,
    expense_id integer NOT NULL REFERENCES expense(id) ON DELETE RESTRICT,
    expected_quantity numeric(18,4) NOT NULL,
    counted_quantity numeric(18,4),
    difference numeric(18,4),
    average_unit_cost numeric(18,6) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_count_line ON inventory_count_line(tenant_id, inventory_count_id, expense_id);

CREATE TABLE IF NOT EXISTS order_inventory_allocation (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    order_id integer NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
    expense_id integer NOT NULL REFERENCES expense(id) ON DELETE RESTRICT,
    control_mode varchar(20) NOT NULL,
    base_quantity numeric(18,4) NOT NULL CHECK (base_quantity > 0),
    reserved_quantity numeric(18,4) NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    consumed_quantity numeric(18,4) NOT NULL DEFAULT 0 CHECK (consumed_quantity >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_order_inventory_control_mode CHECK (control_mode IN ('estimated','strict'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_order_inventory_allocation ON order_inventory_allocation(tenant_id, order_id, product_id, expense_id);

CREATE TABLE IF NOT EXISTS inventory_movement (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    expense_id integer NOT NULL REFERENCES expense(id) ON DELETE RESTRICT,
    type varchar(40) NOT NULL,
    on_hand_delta numeric(18,4) NOT NULL DEFAULT 0,
    reserved_delta numeric(18,4) NOT NULL DEFAULT 0,
    unit_cost numeric(18,6) NOT NULL DEFAULT 0,
    order_id integer REFERENCES "order"(id) ON DELETE RESTRICT,
    expense_header_id integer REFERENCES expense_header(id) ON DELETE RESTRICT,
    expense_detail_id integer REFERENCES expense_detail(id) ON DELETE RESTRICT,
    transfer_id integer REFERENCES inventory_transfer(id) ON DELETE RESTRICT,
    inventory_count_id integer REFERENCES inventory_count(id) ON DELETE RESTRICT,
    created_by_id integer NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    operation_key varchar(160) NOT NULL,
    reason varchar(500),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE inventory_movement ADD COLUMN IF NOT EXISTS expense_header_id integer REFERENCES expense_header(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_movement_operation ON inventory_movement(tenant_id, operation_key, expense_id, type);
CREATE INDEX IF NOT EXISTS ix_inventory_movement_branch_created ON inventory_movement(tenant_id, branch_id, created_at DESC);

DO $inventory_rls$
DECLARE
    table_name text;
    policy_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY['expense_unit_conversion','product_expense_requirement','inventory_balance','inventory_movement','order_inventory_allocation','inventory_transfer','inventory_transfer_line','inventory_count','inventory_count_line'] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
        EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_policy ON %I', table_name);
        FOREACH policy_name IN ARRAY ARRAY['tenant_select_policy','tenant_insert_policy','tenant_update_policy','tenant_delete_policy'] LOOP
            EXECUTE format('DROP POLICY IF EXISTS %I ON %I', policy_name, table_name);
        END LOOP;
        EXECUTE format('CREATE POLICY tenant_select_policy ON %I FOR SELECT USING (app.is_system_scope() OR tenant_id = app.current_tenant_id())', table_name);
        EXECUTE format('CREATE POLICY tenant_insert_policy ON %I FOR INSERT WITH CHECK (app.is_system_scope() OR tenant_id = app.current_tenant_id())', table_name);
        EXECUTE format('CREATE POLICY tenant_update_policy ON %I FOR UPDATE USING (app.is_system_scope() OR tenant_id = app.current_tenant_id()) WITH CHECK (app.is_system_scope() OR tenant_id = app.current_tenant_id())', table_name);
        EXECUTE format('CREATE POLICY tenant_delete_policy ON %I FOR DELETE USING (app.is_system_scope() OR tenant_id = app.current_tenant_id())', table_name);
    END LOOP;
END $inventory_rls$;

COMMIT;
