CREATE TABLE IF NOT EXISTS public.entity_audit_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id integer NOT NULL REFERENCES public.branch (id) ON DELETE RESTRICT,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    operation_type character varying(50) NOT NULL,
    business_date date NOT NULL,
    changed_at timestamp with time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer NULL REFERENCES public."user" (id) ON DELETE SET NULL,
    changed_by_name_snapshot character varying(200) NULL,
    summary_text character varying(500) NOT NULL,
    money_delta_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    before_json jsonb NULL,
    after_json jsonb NULL,
    metadata_json jsonb NULL
);

CREATE TABLE IF NOT EXISTS public.daily_audit_dispatch (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id integer NOT NULL REFERENCES public.branch (id) ON DELETE RESTRICT,
    business_date date NOT NULL,
    cash_register_closure_id integer NOT NULL REFERENCES public.cash_register_closure (id) ON DELETE RESTRICT,
    dispatched_at timestamp with time zone NULL,
    dispatched_by_user_id integer NULL REFERENCES public."user" (id) ON DELETE RESTRICT,
    dispatch_status character varying(50) NOT NULL,
    dispatch_error character varying(2000) NULL,
    recipient_emails_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    summary_json jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_daily_audit_dispatch_branch_business_date
    ON public.daily_audit_dispatch (branch_id, business_date);
CREATE INDEX IF NOT EXISTS ix_daily_audit_dispatch_closure_id
    ON public.daily_audit_dispatch (cash_register_closure_id);
CREATE INDEX IF NOT EXISTS ix_entity_audit_log_branch_id
    ON public.entity_audit_log (branch_id);
CREATE INDEX IF NOT EXISTS ix_entity_audit_log_business_date
    ON public.entity_audit_log (business_date);
CREATE INDEX IF NOT EXISTS ix_entity_audit_log_changed_at
    ON public.entity_audit_log (changed_at);
CREATE INDEX IF NOT EXISTS ix_entity_audit_log_entity
    ON public.entity_audit_log (entity_type, entity_id);

CREATE OR REPLACE FUNCTION public.audit_current_user_id() RETURNS integer
LANGUAGE plpgsql AS $$
DECLARE
    raw_value text;
BEGIN
    raw_value := current_setting('app.current_user_id', true);
    IF raw_value IS NULL OR btrim(raw_value) = '' THEN
        RETURN NULL;
    END IF;
    RETURN raw_value::integer;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_current_user_name() RETURNS text
LANGUAGE plpgsql AS $$
DECLARE
    raw_value text;
BEGIN
    raw_value := current_setting('app.current_user_name', true);
    IF raw_value IS NULL OR btrim(raw_value) = '' THEN
        RETURN NULL;
    END IF;
    RETURN raw_value;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_business_date(p_changed_at timestamp with time zone) RETURNS date
LANGUAGE sql
AS $$
    SELECT ((p_changed_at AT TIME ZONE 'America/Bogota')::date);
$$;

CREATE OR REPLACE FUNCTION public.audit_order_snapshot(p_order_id integer) RETURNS jsonb
LANGUAGE sql
AS $$
    SELECT jsonb_build_object(
        'id', o.id,
        'status', o.status,
        'total', o.total,
        'subtotal', o.subtotal,
        'discount_total', o.discount_total,
        'delivery_fee', COALESCE(o.delivery_fee, 0),
        'paid_in_store_cash_amount', COALESCE(o.paid_in_store_cash_amount, 0),
        'lines', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'product_id', od.product_id,
                    'quantity', od.quantity,
                    'unit_price', od.unit_price,
                    'discount', COALESCE(od.discount, 0),
                    'subtotal', COALESCE(od.subtotal, 0)
                )
                ORDER BY od.id
            )
            FROM public.order_detail od
            WHERE od.order_id = o.id
        ), '[]'::jsonb)
    )
    FROM public."order" o
    WHERE o.id = p_order_id;
$$;

CREATE OR REPLACE FUNCTION public.audit_expense_snapshot(p_header_id integer) RETURNS jsonb
LANGUAGE sql
AS $$
    SELECT jsonb_build_object(
        'id', eh.id,
        'created_at', eh.created_at,
        'supplier_id', eh.supplier_id,
        'supplier_name', s.name,
        'created_by_id', eh.created_by_id,
        'created_by_name', creator.name,
        'deliveryman_id', eh.deliveryman_id,
        'deliveryman_name', deliveryman.name,
        'total', COALESCE(eh.total, 0),
        'vat_amount', COALESCE(eh.vat_amount, 0),
        'notes', eh.notes,
        'lines', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'expense_id', ed.expense_id,
                    'expense_name', e.name,
                    'category_name', ec.name,
                    'unit', e.unit,
                    'quantity', ed.quantity,
                    'amount', ed.amount,
                    'total', COALESCE(ed.total, 0),
                    'notes', ed.notes
                )
                ORDER BY ed.id
            )
            FROM public.expense_detail ed
            JOIN public.expense e ON e.id = ed.expense_id
            JOIN public.expense_category ec ON ec.id = e.category_id
            WHERE ed.header_id = eh.id
        ), '[]'::jsonb),
        'payments', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'bank_id', ebp.bank_id,
                    'bank_name', b.name,
                    'amount', ebp.amount
                )
                ORDER BY ebp.id
            )
            FROM public.expense_bank_payment ebp
            JOIN public.bank b ON b.id = ebp.bank_id
            WHERE ebp.expense_header_id = eh.id
        ), '[]'::jsonb),
        'linked_deliveryman_advances', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', da.id,
                    'amount', da.amount,
                    'payment_method', da.payment_method,
                    'notes', da.notes,
                    'created_at', da.created_at
                )
                ORDER BY da.id
            )
            FROM public.deliveryman_advance da
            WHERE da.expense_header_id = eh.id
        ), '[]'::jsonb)
    )
    FROM public.expense_header eh
    JOIN public.supplier s ON s.id = eh.supplier_id
    JOIN public."user" creator ON creator.id = eh.created_by_id
    LEFT JOIN public."user" deliveryman ON deliveryman.id = eh.deliveryman_id
    WHERE eh.id = p_header_id;
$$;

CREATE OR REPLACE FUNCTION public.audit_insert_log(
    p_branch_id integer,
    p_entity_type text,
    p_entity_id integer,
    p_operation_type text,
    p_changed_at timestamp with time zone,
    p_summary_text text,
    p_money_delta jsonb,
    p_before_json jsonb,
    p_after_json jsonb,
    p_metadata_json jsonb
) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    v_user_id integer;
    v_name text;
BEGIN
    v_user_id := public.audit_current_user_id();
    v_name := COALESCE(public.audit_current_user_name(), (SELECT u.name FROM public."user" u WHERE u.id = v_user_id));

    INSERT INTO public.entity_audit_log (
        branch_id,
        entity_type,
        entity_id,
        operation_type,
        business_date,
        changed_at,
        changed_by_user_id,
        changed_by_name_snapshot,
        summary_text,
        money_delta_json,
        before_json,
        after_json,
        metadata_json
    )
    VALUES (
        p_branch_id,
        p_entity_type,
        p_entity_id,
        p_operation_type,
        public.audit_business_date(p_changed_at),
        p_changed_at,
        v_user_id,
        v_name,
        p_summary_text,
        COALESCE(p_money_delta, '{}'::jsonb),
        p_before_json,
        p_after_json,
        p_metadata_json
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_order_row_changes() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_changed_at timestamp with time zone := NOW();
    v_before jsonb;
    v_after jsonb;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_before := jsonb_build_object(
            'id', OLD.id,
            'status', OLD.status,
            'total', OLD.total,
            'subtotal', OLD.subtotal,
            'discount_total', OLD.discount_total,
            'delivery_fee', COALESCE(OLD.delivery_fee, 0),
            'paid_in_store_cash_amount', COALESCE(OLD.paid_in_store_cash_amount, 0),
            'lines', '[]'::jsonb
        );

        PERFORM public.audit_insert_log(
            OLD.branch_id, 'order', OLD.id, 'deleted', v_changed_at,
            format('Pedido #%s eliminado. Total anterior: %s', OLD.id, to_char(COALESCE(OLD.total, 0), 'FM999G999G999G990')),
            jsonb_build_object('total_before', COALESCE(OLD.total, 0), 'total_after', 0, 'difference', -COALESCE(OLD.total, 0), 'lines_affected', '[]'::jsonb),
            v_before, NULL, jsonb_build_object('trigger', TG_NAME, 'operation_id', txid_current()::text)
        );
        RETURN OLD;
    END IF;

    v_after := public.audit_order_snapshot(NEW.id);
    v_before := jsonb_build_object('id', OLD.id, 'status', OLD.status, 'total', OLD.total, 'subtotal', OLD.subtotal, 'discount_total', OLD.discount_total, 'delivery_fee', COALESCE(OLD.delivery_fee, 0), 'paid_in_store_cash_amount', COALESCE(OLD.paid_in_store_cash_amount, 0));

    IF OLD.status IS DISTINCT FROM NEW.status AND NEW.status = 'cancelled' THEN
        PERFORM public.audit_insert_log(
            NEW.branch_id, 'order', NEW.id, 'cancelled', v_changed_at,
            format('Pedido #%s cancelado. Total afectado: %s', NEW.id, to_char(COALESCE(OLD.total, 0), 'FM999G999G999G990')),
            jsonb_build_object('total_before', COALESCE(OLD.total, 0), 'total_after', COALESCE(NEW.total, 0), 'difference', COALESCE(NEW.total, 0) - COALESCE(OLD.total, 0), 'lines_affected', '[]'::jsonb, 'impact_type', 'removed_from_sales'),
            v_before, v_after, jsonb_build_object('trigger', TG_NAME, 'operation_id', txid_current()::text, 'cancelled_reason', NEW.cancelled_reason)
        );
        RETURN NEW;
    END IF;

    IF OLD.delivery_fee IS DISTINCT FROM NEW.delivery_fee
       OR OLD.paid_in_store_cash_amount IS DISTINCT FROM NEW.paid_in_store_cash_amount
       OR OLD.subtotal IS DISTINCT FROM NEW.subtotal
       OR OLD.discount_total IS DISTINCT FROM NEW.discount_total
       OR OLD.total IS DISTINCT FROM NEW.total
       OR OLD.cancelled_reason IS DISTINCT FROM NEW.cancelled_reason THEN
        PERFORM public.audit_insert_log(
            NEW.branch_id, 'order', NEW.id, 'modified', v_changed_at,
            format('Pedido #%s modificado monetariamente. %s -> %s', NEW.id, COALESCE(OLD.total, 0), COALESCE(NEW.total, 0)),
            jsonb_build_object('total_before', COALESCE(OLD.total, 0), 'total_after', COALESCE(NEW.total, 0), 'difference', COALESCE(NEW.total, 0) - COALESCE(OLD.total, 0), 'lines_affected', '[]'::jsonb),
            v_before, v_after, jsonb_build_object('trigger', TG_NAME, 'operation_id', txid_current()::text)
        );
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_order_detail_changes() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_order_id integer;
    v_branch_id integer;
    v_changed_at timestamp with time zone := NOW();
    v_after jsonb;
    v_before_total numeric;
    v_after_total numeric;
    v_old_subtotal numeric := 0;
    v_new_subtotal numeric := 0;
    v_summary text;
BEGIN
    v_order_id := COALESCE(NEW.order_id, OLD.order_id);
    SELECT o.branch_id INTO v_branch_id FROM public."order" o WHERE o.id = v_order_id;
    v_after := public.audit_order_snapshot(v_order_id);
    IF TG_OP <> 'INSERT' THEN
        v_old_subtotal := COALESCE(OLD.subtotal, 0);
    END IF;
    IF TG_OP <> 'DELETE' THEN
        v_new_subtotal := COALESCE(NEW.subtotal, 0);
    END IF;
    v_after_total := COALESCE((v_after ->> 'total')::numeric, 0);
    v_before_total := v_after_total - v_new_subtotal + v_old_subtotal;

    IF TG_OP = 'INSERT' THEN
        v_summary := format('Pedido #%s: producto %s agregado. Cantidad %s, subtotal %s', v_order_id, NEW.product_id, NEW.quantity, COALESCE(NEW.subtotal, 0));
    ELSIF TG_OP = 'DELETE' THEN
        v_summary := format('Pedido #%s: producto %s eliminado. Cantidad %s, subtotal %s', v_order_id, OLD.product_id, OLD.quantity, COALESCE(OLD.subtotal, 0));
    ELSIF OLD.product_id IS DISTINCT FROM NEW.product_id THEN
        v_summary := format('Pedido #%s: producto %s cambiado por %s', v_order_id, OLD.product_id, NEW.product_id);
    ELSIF OLD.quantity IS DISTINCT FROM NEW.quantity THEN
        v_summary := format('Pedido #%s: producto %s cambio cantidad %s->%s', v_order_id, NEW.product_id, OLD.quantity, NEW.quantity);
    ELSIF OLD.unit_price IS DISTINCT FROM NEW.unit_price THEN
        v_summary := format('Pedido #%s: producto %s cambio valor %s->%s', v_order_id, NEW.product_id, OLD.unit_price, NEW.unit_price);
    ELSIF OLD.discount IS DISTINCT FROM NEW.discount THEN
        v_summary := format('Pedido #%s: producto %s cambio descuento %s->%s', v_order_id, NEW.product_id, COALESCE(OLD.discount, 0), COALESCE(NEW.discount, 0));
    ELSE
        v_summary := format('Pedido #%s: producto %s modifico subtotal %s->%s', v_order_id, COALESCE(NEW.product_id, OLD.product_id), v_old_subtotal, v_new_subtotal);
    END IF;

    PERFORM public.audit_insert_log(
        v_branch_id, 'order', v_order_id, 'modified', v_changed_at, v_summary,
        jsonb_build_object(
            'total_before', v_before_total,
            'total_after', v_after_total,
            'difference', v_after_total - v_before_total,
            'lines_affected', jsonb_build_array(jsonb_strip_nulls(jsonb_build_object(
                'product_id', COALESCE(NEW.product_id, OLD.product_id),
                'product_id_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.product_id END,
                'product_id_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.product_id END,
                'quantity_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.quantity END,
                'quantity_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.quantity END,
                'unit_price_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.unit_price END,
                'unit_price_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.unit_price END,
                'discount_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.discount END,
                'discount_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.discount END,
                'subtotal_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.subtotal END,
                'subtotal_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.subtotal END
            )))
        ),
        jsonb_build_object('id', v_order_id, 'total', v_before_total),
        v_after,
        jsonb_build_object('trigger', TG_NAME, 'operation_id', txid_current()::text, 'detail_operation', TG_OP)
    );

    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_expense_header_changes() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_changed_at timestamp with time zone := NOW();
    v_before jsonb;
    v_after jsonb;
BEGIN
    IF TG_OP = 'DELETE' THEN
        -- This function runs BEFORE DELETE so related lines and bank payments
        -- are still available for the immutable audit snapshot.
        v_before := public.audit_expense_snapshot(OLD.id);
        PERFORM public.audit_insert_log(
            OLD.branch_id, 'expense_header', OLD.id, 'deleted', v_changed_at,
            format('Gasto #%s eliminado. Total anterior: %s', OLD.id, to_char(COALESCE(OLD.total, 0), 'FM999G999G999G990')),
            jsonb_build_object('total_before', COALESCE(OLD.total, 0), 'total_after', 0, 'difference', -COALESCE(OLD.total, 0), 'lines_affected', '[]'::jsonb),
            v_before, NULL, jsonb_build_object('trigger', TG_NAME)
        );
        -- The linked expense-offset advance belongs to this invoice. Removing
        -- it here keeps the deletion atomic and satisfies the restrictive FK;
        -- its identifying data is already preserved in v_before.
        DELETE FROM public.deliveryman_advance
        WHERE expense_header_id = OLD.id;
        RETURN OLD;
    END IF;

    IF OLD.total IS DISTINCT FROM NEW.total OR OLD.vat_amount IS DISTINCT FROM NEW.vat_amount THEN
        v_after := public.audit_expense_snapshot(NEW.id);
        v_before := jsonb_build_object('id', OLD.id, 'total', COALESCE(OLD.total, 0), 'vat_amount', COALESCE(OLD.vat_amount, 0));
        PERFORM public.audit_insert_log(
            NEW.branch_id, 'expense_header', NEW.id, 'modified', v_changed_at,
            format('Gasto #%s modificado monetariamente. %s -> %s', NEW.id, COALESCE(OLD.total, 0), COALESCE(NEW.total, 0)),
            jsonb_build_object('total_before', COALESCE(OLD.total, 0), 'total_after', COALESCE(NEW.total, 0), 'difference', COALESCE(NEW.total, 0) - COALESCE(OLD.total, 0), 'lines_affected', '[]'::jsonb),
            v_before, v_after, jsonb_build_object('trigger', TG_NAME)
        );
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_expense_detail_changes() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_header_id integer;
    v_branch_id integer;
    v_changed_at timestamp with time zone := NOW();
    v_after jsonb;
    v_before_total numeric;
    v_after_total numeric;
    v_old_total numeric := 0;
    v_new_total numeric := 0;
    v_summary text;
BEGIN
    -- Ignore child deletes caused by deleting the header. The complete
    -- header snapshot is already stored by audit_expense_header_changes.
    IF TG_OP = 'DELETE' AND pg_trigger_depth() > 1 THEN
        RETURN OLD;
    END IF;

    v_header_id := COALESCE(NEW.header_id, OLD.header_id);
    SELECT eh.branch_id INTO v_branch_id FROM public.expense_header eh WHERE eh.id = v_header_id;
    v_after := public.audit_expense_snapshot(v_header_id);
    IF TG_OP <> 'INSERT' THEN
        v_old_total := COALESCE(OLD.total, 0);
    END IF;
    IF TG_OP <> 'DELETE' THEN
        v_new_total := COALESCE(NEW.total, 0);
    END IF;
    v_after_total := COALESCE((v_after ->> 'total')::numeric, 0);
    v_before_total := v_after_total - v_new_total + v_old_total;

    IF TG_OP = 'INSERT' THEN
        v_summary := format('Gasto #%s: linea %s agregada. Cantidad %s, total %s', v_header_id, NEW.expense_id, NEW.quantity, COALESCE(NEW.total, 0));
    ELSIF TG_OP = 'DELETE' THEN
        v_summary := format('Gasto #%s: linea %s eliminada. Cantidad %s, total %s', v_header_id, OLD.expense_id, OLD.quantity, COALESCE(OLD.total, 0));
    ELSIF OLD.quantity IS DISTINCT FROM NEW.quantity THEN
        v_summary := format('Gasto #%s: linea %s cambio cantidad %s->%s', v_header_id, NEW.expense_id, OLD.quantity, NEW.quantity);
    ELSIF OLD.amount IS DISTINCT FROM NEW.amount THEN
        v_summary := format('Gasto #%s: linea %s cambio valor %s->%s', v_header_id, NEW.expense_id, OLD.amount, NEW.amount);
    ELSE
        v_summary := format('Gasto #%s: linea %s cambio total %s->%s', v_header_id, COALESCE(NEW.expense_id, OLD.expense_id), v_old_total, v_new_total);
    END IF;

    PERFORM public.audit_insert_log(
        v_branch_id, 'expense_header', v_header_id, 'modified', v_changed_at, v_summary,
        jsonb_build_object(
            'total_before', v_before_total,
            'total_after', v_after_total,
            'difference', v_after_total - v_before_total,
            'lines_affected', jsonb_build_array(jsonb_strip_nulls(jsonb_build_object(
                'expense_id', COALESCE(NEW.expense_id, OLD.expense_id),
                'quantity_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.quantity END,
                'quantity_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.quantity END,
                'amount_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.amount END,
                'amount_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.amount END,
                'total_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.total END,
                'total_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.total END
            )))
        ),
        jsonb_build_object('id', v_header_id, 'total', v_before_total),
        v_after,
        jsonb_build_object('trigger', TG_NAME, 'detail_operation', TG_OP)
    );

    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_expense_bank_payment_changes() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_header_id integer;
    v_branch_id integer;
    v_changed_at timestamp with time zone := NOW();
    v_after jsonb;
    v_total numeric;
    v_summary text;
BEGIN
    -- Ignore child deletes caused by deleting the header. The complete
    -- header snapshot is already stored by audit_expense_header_changes.
    IF TG_OP = 'DELETE' AND pg_trigger_depth() > 1 THEN
        RETURN OLD;
    END IF;

    v_header_id := COALESCE(NEW.expense_header_id, OLD.expense_header_id);
    SELECT eh.branch_id, COALESCE(eh.total, 0) INTO v_branch_id, v_total FROM public.expense_header eh WHERE eh.id = v_header_id;
    v_after := public.audit_expense_snapshot(v_header_id);

    IF TG_OP = 'UPDATE'
       AND OLD.amount IS NOT DISTINCT FROM NEW.amount
       AND OLD.bank_id IS NOT DISTINCT FROM NEW.bank_id THEN
        RETURN NEW;
    END IF;

    IF TG_OP = 'INSERT' THEN
        v_summary := format('Gasto #%s: pago banco %s agregado por %s', v_header_id, NEW.bank_id, NEW.amount);
    ELSIF TG_OP = 'DELETE' THEN
        v_summary := format('Gasto #%s: pago banco %s eliminado por %s', v_header_id, OLD.bank_id, OLD.amount);
    ELSE
        v_summary := format('Gasto #%s: pago banco %s modificado %s->%s', v_header_id, COALESCE(NEW.bank_id, OLD.bank_id), COALESCE(OLD.amount, 0), COALESCE(NEW.amount, 0));
    END IF;

    PERFORM public.audit_insert_log(
        v_branch_id, 'expense_header', v_header_id, 'modified', v_changed_at, v_summary,
        jsonb_build_object(
            'total_before', v_total,
            'total_after', v_total,
            'difference', 0,
            'lines_affected', jsonb_build_array(jsonb_strip_nulls(jsonb_build_object(
                'bank_id_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.bank_id END,
                'bank_id_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.bank_id END,
                'amount_before', CASE WHEN TG_OP <> 'INSERT' THEN OLD.amount END,
                'amount_after', CASE WHEN TG_OP <> 'DELETE' THEN NEW.amount END
            )))
        ),
        jsonb_build_object('id', v_header_id, 'total', v_total),
        v_after,
        jsonb_build_object('trigger', TG_NAME, 'payment_operation', TG_OP)
    );

    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS zz_audit_order_on_update ON public."order";
CREATE TRIGGER zz_audit_order_on_update AFTER UPDATE ON public."order" FOR EACH ROW EXECUTE FUNCTION public.audit_order_row_changes();
DROP TRIGGER IF EXISTS zz_audit_order_on_delete ON public."order";
CREATE TRIGGER zz_audit_order_on_delete AFTER DELETE ON public."order" FOR EACH ROW EXECUTE FUNCTION public.audit_order_row_changes();
DROP TRIGGER IF EXISTS zz_audit_order_detail_on_insert ON public.order_detail;
CREATE TRIGGER zz_audit_order_detail_on_insert AFTER INSERT ON public.order_detail FOR EACH ROW EXECUTE FUNCTION public.audit_order_detail_changes();
DROP TRIGGER IF EXISTS zz_audit_order_detail_on_update ON public.order_detail;
CREATE TRIGGER zz_audit_order_detail_on_update AFTER UPDATE ON public.order_detail FOR EACH ROW EXECUTE FUNCTION public.audit_order_detail_changes();
DROP TRIGGER IF EXISTS zz_audit_order_detail_on_delete ON public.order_detail;
CREATE TRIGGER zz_audit_order_detail_on_delete AFTER DELETE ON public.order_detail FOR EACH ROW EXECUTE FUNCTION public.audit_order_detail_changes();
DROP TRIGGER IF EXISTS zz_audit_expense_header_on_update ON public.expense_header;
CREATE TRIGGER zz_audit_expense_header_on_update AFTER UPDATE ON public.expense_header FOR EACH ROW EXECUTE FUNCTION public.audit_expense_header_changes();
DROP TRIGGER IF EXISTS zz_audit_expense_header_on_delete ON public.expense_header;
CREATE TRIGGER zz_audit_expense_header_on_delete BEFORE DELETE ON public.expense_header FOR EACH ROW EXECUTE FUNCTION public.audit_expense_header_changes();
DROP TRIGGER IF EXISTS zz_audit_expense_detail_on_insert ON public.expense_detail;
CREATE TRIGGER zz_audit_expense_detail_on_insert AFTER INSERT ON public.expense_detail FOR EACH ROW EXECUTE FUNCTION public.audit_expense_detail_changes();
DROP TRIGGER IF EXISTS zz_audit_expense_detail_on_update ON public.expense_detail;
CREATE TRIGGER zz_audit_expense_detail_on_update AFTER UPDATE ON public.expense_detail FOR EACH ROW EXECUTE FUNCTION public.audit_expense_detail_changes();
DROP TRIGGER IF EXISTS zz_audit_expense_detail_on_delete ON public.expense_detail;
CREATE TRIGGER zz_audit_expense_detail_on_delete AFTER DELETE ON public.expense_detail FOR EACH ROW EXECUTE FUNCTION public.audit_expense_detail_changes();
DROP TRIGGER IF EXISTS zz_audit_expense_bank_payment_on_insert ON public.expense_bank_payment;
CREATE TRIGGER zz_audit_expense_bank_payment_on_insert AFTER INSERT ON public.expense_bank_payment FOR EACH ROW EXECUTE FUNCTION public.audit_expense_bank_payment_changes();
DROP TRIGGER IF EXISTS zz_audit_expense_bank_payment_on_update ON public.expense_bank_payment;
CREATE TRIGGER zz_audit_expense_bank_payment_on_update AFTER UPDATE ON public.expense_bank_payment FOR EACH ROW EXECUTE FUNCTION public.audit_expense_bank_payment_changes();
DROP TRIGGER IF EXISTS zz_audit_expense_bank_payment_on_delete ON public.expense_bank_payment;
CREATE TRIGGER zz_audit_expense_bank_payment_on_delete AFTER DELETE ON public.expense_bank_payment FOR EACH ROW EXECUTE FUNCTION public.audit_expense_bank_payment_changes();
