CREATE TABLE IF NOT EXISTS wompi_payment_integration (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE CASCADE,
    financial_app_id integer NOT NULL REFERENCES app(id) ON DELETE RESTRICT,
    active_environment character varying(20) NOT NULL DEFAULT 'sandbox',
    is_enabled boolean NOT NULL DEFAULT false,
    estimated_commission_rate numeric(8,6) NOT NULL DEFAULT 0,
    sandbox_public_key character varying(160),
    sandbox_encrypted_integrity_secret text,
    sandbox_encrypted_events_secret text,
    production_public_key character varying(160),
    production_encrypted_integrity_secret text,
    production_encrypted_events_secret text,
    last_sandbox_webhook_at timestamp with time zone,
    last_production_webhook_at timestamp with time zone,
    last_tested_at timestamp with time zone,
    last_error character varying(1000),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_wompi_payment_integration_environment CHECK (active_environment IN ('sandbox', 'production')),
    CONSTRAINT ck_wompi_payment_integration_commission CHECK (estimated_commission_rate BETWEEN 0 AND 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_wompi_payment_integration_tenant_branch
    ON wompi_payment_integration (tenant_id, branch_id);

CREATE TABLE IF NOT EXISTS wompi_payment_attempt (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    order_id integer NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    integration_id integer NOT NULL REFERENCES wompi_payment_integration(id) ON DELETE RESTRICT,
    reference character varying(100) NOT NULL,
    environment character varying(20) NOT NULL,
    public_key_snapshot character varying(160) NOT NULL,
    integrity_signature character varying(64) NOT NULL,
    encrypted_events_secret_snapshot text NOT NULL,
    expected_amount_in_cents bigint NOT NULL,
    currency character varying(3) NOT NULL DEFAULT 'COP',
    status character varying(30) NOT NULL DEFAULT 'Pending',
    expires_at timestamp with time zone NOT NULL,
    approved_at timestamp with time zone,
    requires_manual_review boolean NOT NULL DEFAULT false,
    manual_review_reason character varying(500),
    reviewed_at timestamp with time zone,
    reviewed_by_user_id integer REFERENCES "user"(id) ON DELETE RESTRICT,
    app_payment_id integer REFERENCES app_payment(id) ON DELETE RESTRICT,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

ALTER TABLE wompi_payment_attempt
    ADD COLUMN IF NOT EXISTS encrypted_events_secret_snapshot text;
UPDATE wompi_payment_attempt attempt
SET encrypted_events_secret_snapshot = CASE
    WHEN attempt.environment = 'production' THEN integration.production_encrypted_events_secret
    ELSE integration.sandbox_encrypted_events_secret
END
FROM wompi_payment_integration integration
WHERE attempt.integration_id = integration.id
  AND attempt.encrypted_events_secret_snapshot IS NULL;
ALTER TABLE wompi_payment_attempt
    ALTER COLUMN encrypted_events_secret_snapshot SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_wompi_payment_attempt_reference
    ON wompi_payment_attempt (reference);
CREATE INDEX IF NOT EXISTS ix_wompi_payment_attempt_tenant_order
    ON wompi_payment_attempt (tenant_id, order_id);
CREATE INDEX IF NOT EXISTS ix_wompi_payment_attempt_integration_status
    ON wompi_payment_attempt (integration_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS ux_wompi_payment_attempt_app_payment
    ON wompi_payment_attempt (app_payment_id) WHERE app_payment_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS wompi_provider_transaction (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_attempt_id integer NOT NULL REFERENCES wompi_payment_attempt(id) ON DELETE CASCADE,
    provider_transaction_id character varying(120) NOT NULL,
    status character varying(30) NOT NULL DEFAULT 'PENDING',
    payment_method character varying(40),
    amount_in_cents bigint NOT NULL,
    currency character varying(3) NOT NULL DEFAULT 'COP',
    payload_hash character varying(64) NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_wompi_provider_transaction_id
    ON wompi_provider_transaction (provider_transaction_id);

CREATE TABLE IF NOT EXISTS wompi_webhook_event (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    integration_id integer NOT NULL REFERENCES wompi_payment_integration(id) ON DELETE RESTRICT,
    environment character varying(20) NOT NULL,
    event_fingerprint character varying(64) NOT NULL,
    payload_hash character varying(64) NOT NULL,
    provider_transaction_id character varying(120),
    status character varying(30) NOT NULL,
    last_error character varying(1000),
    processed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_wompi_webhook_event_fingerprint
    ON wompi_webhook_event (event_fingerprint);

CREATE TABLE IF NOT EXISTS payment_notification_outbox (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE CASCADE,
    order_id integer NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    event_type character varying(60) NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'pending',
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamp with time zone,
    processed_at timestamp with time zone,
    last_error character varying(1000),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_payment_notification_outbox_pending
    ON payment_notification_outbox (status, next_attempt_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_notification_outbox_order_event
    ON payment_notification_outbox (order_id, event_type);

CREATE TABLE IF NOT EXISTS wompi_integration_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE CASCADE,
    integration_id integer NOT NULL REFERENCES wompi_payment_integration(id) ON DELETE CASCADE,
    action character varying(50) NOT NULL,
    user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_wompi_integration_audit_branch_created
    ON wompi_integration_audit (branch_id, created_at DESC);
