ALTER TABLE branch
    ADD COLUMN IF NOT EXISTS storefront_taken_by_user_id integer;

ALTER TABLE "order"
    ADD COLUMN IF NOT EXISTS storefront_idempotency_key character varying(80);

CREATE UNIQUE INDEX IF NOT EXISTS ux_order_storefront_idempotency_key
    ON "order" (storefront_idempotency_key)
    WHERE storefront_idempotency_key IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_branch_storefront_taken_by_user'
    ) THEN
        ALTER TABLE branch
            ADD CONSTRAINT fk_branch_storefront_taken_by_user
            FOREIGN KEY (storefront_taken_by_user_id) REFERENCES "user" (id) ON DELETE SET NULL;
    END IF;
END $$;

ALTER TABLE address
    ADD COLUMN IF NOT EXISTS label character varying(60);

ALTER TABLE address
    ALTER COLUMN neighborhood_id DROP NOT NULL;

CREATE TABLE IF NOT EXISTS storefront_customer_auth_challenge (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    public_id uuid NOT NULL,
    phone character varying(10) NOT NULL,
    code_hmac character varying(64) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    resend_available_at timestamp with time zone NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 5,
    sent_at timestamp with time zone,
    consumed_at timestamp with time zone,
    session_token_hash character varying(64),
    session_expires_at timestamp with time zone,
    request_ip_hash character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_storefront_customer_auth_challenge_public_id
    ON storefront_customer_auth_challenge (public_id);
CREATE INDEX IF NOT EXISTS idx_storefront_customer_auth_challenge_phone
    ON storefront_customer_auth_challenge (tenant_id, phone, created_at);
CREATE INDEX IF NOT EXISTS idx_storefront_customer_auth_challenge_ip
    ON storefront_customer_auth_challenge (tenant_id, request_ip_hash, created_at);
CREATE INDEX IF NOT EXISTS idx_storefront_customer_auth_challenge_session
    ON storefront_customer_auth_challenge (session_token_hash)
    WHERE session_token_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_customer_phone2
    ON customer (phone2)
    WHERE phone2 IS NOT NULL;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'update_updated_at_column')
       AND NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_storefront_customer_auth_challenge_updated_at') THEN
        CREATE TRIGGER update_storefront_customer_auth_challenge_updated_at
            BEFORE UPDATE ON storefront_customer_auth_challenge
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;
