BEGIN;

CREATE TABLE IF NOT EXISTS whatsapp_channel_setting (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL DEFAULT 1 CHECK (tenant_id = 1),
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    phone_number_id varchar(64) NOT NULL,
    business_account_id varchar(64) NOT NULL,
    display_phone_number varchar(32) NOT NULL,
    access_token text NOT NULL,
    webhook_verify_token varchar(255) NOT NULL,
    app_secret varchar(255),
    flow_id varchar(64),
    flow_json_version varchar(16) NOT NULL DEFAULT '7.1',
    is_active boolean NOT NULL DEFAULT false,
    is_verified boolean NOT NULL DEFAULT false,
    flow_enabled boolean NOT NULL DEFAULT false,
    last_verified_at timestamptz,
    away_message_enabled boolean NOT NULL DEFAULT false,
    away_message_text varchar(3500),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_channel_setting_public_id ON whatsapp_channel_setting(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_channel_setting_phone_number ON whatsapp_channel_setting(phone_number_id);
CREATE INDEX IF NOT EXISTS ix_whatsapp_channel_setting_tenant_active ON whatsapp_channel_setting(tenant_id, is_active);

INSERT INTO whatsapp_channel_setting (
    tenant_id, phone_number_id, business_account_id, display_phone_number, access_token,
    webhook_verify_token, app_secret, is_active, is_verified, last_verified_at,
    away_message_enabled, away_message_text)
SELECT 1, phone_number_id, business_account_id, display_phone_number, access_token,
       webhook_verify_token, app_secret, false, is_verified, last_verified_at,
       away_message_enabled, away_message_text
FROM whatsapp_branch_setting
WHERE branch_id = 1
  AND NOT EXISTS (
      SELECT 1 FROM whatsapp_channel_setting channel
      WHERE channel.phone_number_id = whatsapp_branch_setting.phone_number_id
  );

CREATE TABLE IF NOT EXISTS tenant_ai_setting (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL DEFAULT 1 CHECK (tenant_id = 1),
    provider varchar(40) NOT NULL,
    model varchar(120) NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    temperature double precision,
    max_context_messages integer NOT NULL DEFAULT 20,
    last_tested_at timestamptz,
    is_verified boolean NOT NULL DEFAULT false,
    assistant_name varchar(200) NOT NULL DEFAULT '',
    prompt_objective varchar(4000),
    prompt_personality varchar(2000),
    prompt_required_rules varchar(8000),
    prompt_fixed_branch_info varchar(8000),
    prompt_additional_instructions varchar(8000),
    transfer_message varchar(1000) NOT NULL DEFAULT 'Un asesor continuará con tu atención.',
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tenant_ai_setting_tenant ON tenant_ai_setting(tenant_id);

INSERT INTO tenant_ai_setting (
    tenant_id, provider, model, is_active, temperature, max_context_messages,
    last_tested_at, is_verified, assistant_name, prompt_objective, prompt_personality,
    prompt_required_rules, prompt_fixed_branch_info, prompt_additional_instructions,
    transfer_message)
SELECT 1, provider, model, is_active, temperature, max_context_messages,
       last_tested_at, is_verified, assistant_name, prompt_objective, prompt_personality,
       prompt_required_rules, prompt_fixed_branch_info, prompt_additional_instructions,
       transfer_message
FROM branch_ai_setting
WHERE branch_id = 1
  AND NOT EXISTS (SELECT 1 FROM tenant_ai_setting WHERE tenant_id = 1);

CREATE TABLE IF NOT EXISTS whatsapp_commerce_session (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL DEFAULT 1 CHECK (tenant_id = 1),
    correlation_id uuid NOT NULL DEFAULT gen_random_uuid(),
    channel_setting_id integer NOT NULL REFERENCES whatsapp_channel_setting(id) ON DELETE RESTRICT,
    conversation_id integer NOT NULL REFERENCES whatsapp_conversation(id) ON DELETE CASCADE,
    branch_id integer REFERENCES branch(id) ON DELETE SET NULL,
    customer_id integer REFERENCES customer(id) ON DELETE SET NULL,
    flow_token_hash varchar(64) NOT NULL,
    state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    status varchar(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','abandoned','expired')),
    version integer NOT NULL DEFAULT 1,
    idempotency_key varchar(80) NOT NULL,
    expires_at timestamptz NOT NULL,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

ALTER TABLE whatsapp_commerce_session ADD COLUMN IF NOT EXISTS correlation_id uuid NOT NULL DEFAULT gen_random_uuid();
CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_commerce_session_flow_token ON whatsapp_commerce_session(flow_token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_commerce_session_correlation ON whatsapp_commerce_session(correlation_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_commerce_session_idempotency ON whatsapp_commerce_session(idempotency_key);
CREATE INDEX IF NOT EXISTS ix_whatsapp_commerce_session_resume ON whatsapp_commerce_session(conversation_id, status, expires_at DESC);

CREATE TABLE IF NOT EXISTS whatsapp_commerce_session_token (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL DEFAULT 1 CHECK (tenant_id = 1),
    session_id integer NOT NULL REFERENCES whatsapp_commerce_session(id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_commerce_session_token_hash ON whatsapp_commerce_session_token(token_hash);
CREATE INDEX IF NOT EXISTS ix_whatsapp_commerce_session_token_active ON whatsapp_commerce_session_token(session_id, expires_at);

INSERT INTO whatsapp_commerce_session_token (tenant_id, session_id, token_hash, expires_at, created_at, updated_at)
SELECT tenant_id, id, flow_token_hash, expires_at, created_at, updated_at
FROM whatsapp_commerce_session
WHERE flow_token_hash IS NOT NULL AND flow_token_hash <> ''
ON CONFLICT (token_hash) DO NOTHING;

CREATE TABLE IF NOT EXISTS whatsapp_flow_exchange (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES whatsapp_commerce_session(id) ON DELETE CASCADE,
    request_fingerprint varchar(64) NOT NULL,
    response_json jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_flow_exchange_request ON whatsapp_flow_exchange(session_id, request_fingerprint);

CREATE TABLE IF NOT EXISTS whatsapp_commerce_outbox (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL DEFAULT 1 CHECK (tenant_id = 1),
    channel_setting_id integer NOT NULL REFERENCES whatsapp_channel_setting(id) ON DELETE RESTRICT,
    conversation_id integer NOT NULL REFERENCES whatsapp_conversation(id) ON DELETE CASCADE,
    event_key varchar(160) NOT NULL,
    body varchar(4096) NOT NULL,
    button_text varchar(40),
    url varchar(2000),
    status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','sent','failed')),
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT NOW(),
    sent_at timestamptz,
    last_error varchar(1000),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_commerce_outbox_event ON whatsapp_commerce_outbox(event_key);
CREATE INDEX IF NOT EXISTS ix_whatsapp_commerce_outbox_pending ON whatsapp_commerce_outbox(status, next_attempt_at);

CREATE TABLE IF NOT EXISTS whatsapp_commerce_event (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL DEFAULT 1 CHECK (tenant_id = 1),
    session_id integer NOT NULL REFERENCES whatsapp_commerce_session(id) ON DELETE CASCADE,
    conversation_id integer NOT NULL REFERENCES whatsapp_conversation(id) ON DELETE CASCADE,
    branch_id integer REFERENCES branch(id) ON DELETE SET NULL,
    event_key varchar(180) NOT NULL,
    event_name varchar(80) NOT NULL,
    screen varchar(40),
    reference_id varchar(100),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_commerce_event_key ON whatsapp_commerce_event(event_key);
CREATE INDEX IF NOT EXISTS ix_whatsapp_commerce_event_metrics ON whatsapp_commerce_event(tenant_id, event_name, created_at);
CREATE INDEX IF NOT EXISTS ix_whatsapp_commerce_event_session ON whatsapp_commerce_event(session_id, created_at);

ALTER TABLE whatsapp_conversation ADD COLUMN IF NOT EXISTS tenant_id integer NOT NULL DEFAULT 1;
ALTER TABLE whatsapp_conversation ADD COLUMN IF NOT EXISTS channel_setting_id integer REFERENCES whatsapp_channel_setting(id) ON DELETE SET NULL;
ALTER TABLE whatsapp_conversation ADD COLUMN IF NOT EXISTS operational_branch_id integer REFERENCES branch(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_whatsapp_conversation_tenant_channel ON whatsapp_conversation(tenant_id, channel_setting_id);
CREATE INDEX IF NOT EXISTS ix_whatsapp_conversation_operational_branch ON whatsapp_conversation(operational_branch_id);

DROP INDEX IF EXISTS idx_whatsapp_conversation_branch_phone;
CREATE UNIQUE INDEX idx_whatsapp_conversation_branch_phone ON whatsapp_conversation(branch_id, phone_number)
    WHERE channel_setting_id IS NULL AND phone_number IS NOT NULL AND phone_number <> '';
DROP INDEX IF EXISTS uq_whatsapp_conversation_branch_user_id;
CREATE UNIQUE INDEX uq_whatsapp_conversation_branch_user_id ON whatsapp_conversation(branch_id, whatsapp_user_id)
    WHERE channel_setting_id IS NULL AND whatsapp_user_id IS NOT NULL AND whatsapp_user_id <> '';
CREATE UNIQUE INDEX IF NOT EXISTS uq_whatsapp_conversation_channel_phone ON whatsapp_conversation(channel_setting_id, phone_number)
    WHERE channel_setting_id IS NOT NULL AND phone_number IS NOT NULL AND phone_number <> '';
CREATE UNIQUE INDEX IF NOT EXISTS uq_whatsapp_conversation_channel_user_id ON whatsapp_conversation(channel_setting_id, whatsapp_user_id)
    WHERE channel_setting_id IS NOT NULL AND whatsapp_user_id IS NOT NULL AND whatsapp_user_id <> '';

ALTER TABLE storefront_checkout ADD COLUMN IF NOT EXISTS whatsapp_conversation_id integer REFERENCES whatsapp_conversation(id) ON DELETE SET NULL;
ALTER TABLE storefront_checkout ADD COLUMN IF NOT EXISTS order_source varchar(40) NOT NULL DEFAULT 'web';
CREATE INDEX IF NOT EXISTS ix_storefront_checkout_whatsapp_conversation ON storefront_checkout(whatsapp_conversation_id);

ALTER TABLE "order" ADD COLUMN IF NOT EXISTS whatsapp_conversation_id integer REFERENCES whatsapp_conversation(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_order_whatsapp_conversation ON "order"(whatsapp_conversation_id);

COMMIT;
