BEGIN;

CREATE TABLE IF NOT EXISTS delivery_device_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deliveryman_id integer NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    work_session_id integer NOT NULL REFERENCES delivery_work_session(id) ON DELETE RESTRICT,
    client_event_id uuid,
    event_type varchar(50) NOT NULL,
    battery_level_percent integer,
    internet_available boolean,
    gps_enabled boolean,
    location_permission_granted boolean,
    details varchar(500),
    recorded_at timestamp with time zone NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_device_event_battery
        CHECK (battery_level_percent IS NULL OR battery_level_percent BETWEEN 0 AND 100)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_device_event_client_id
    ON delivery_device_event(client_event_id)
    WHERE client_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_delivery_device_event_session_recorded
    ON delivery_device_event(work_session_id, recorded_at);

CREATE INDEX IF NOT EXISTS idx_delivery_device_event_deliveryman_recorded
    ON delivery_device_event(deliveryman_id, recorded_at);

COMMIT;
