BEGIN;

CREATE UNIQUE INDEX IF NOT EXISTS ux_branch_informal_loan_tenant_id_id
    ON public.branch_informal_loan (tenant_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_tenant_id_id
    ON public."user" (tenant_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_expense_header_tenant_id_id
    ON public.expense_header (tenant_id, id);

CREATE TABLE IF NOT EXISTS public.branch_informal_loan_payment (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    tenant_id integer NOT NULL,
    loan_id integer NOT NULL,
    kind integer NOT NULL,
    amount numeric(12,2) NOT NULL,
    balance_before numeric(12,2) NOT NULL,
    balance_after numeric(12,2) NOT NULL,
    notes character varying(500),
    created_by_id integer NOT NULL,
    expense_header_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_branch_informal_loan_payment" PRIMARY KEY (id),
    CONSTRAINT "CK_branch_informal_loan_payment_kind" CHECK (kind IN (0, 1)),
    CONSTRAINT "CK_branch_informal_loan_payment_amount" CHECK (amount > 0),
    CONSTRAINT "CK_branch_informal_loan_payment_balances" CHECK (balance_before >= amount AND balance_after = balance_before - amount),
    CONSTRAINT "FK_branch_informal_loan_payment_tenant" FOREIGN KEY (tenant_id) REFERENCES public.tenant (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_branch_informal_loan_payment_loan" FOREIGN KEY (tenant_id, loan_id) REFERENCES public.branch_informal_loan (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT "FK_branch_informal_loan_payment_user" FOREIGN KEY (tenant_id, created_by_id) REFERENCES public."user" (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT "FK_branch_informal_loan_payment_expense" FOREIGN KEY (tenant_id, expense_header_id) REFERENCES public.expense_header (tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_branch_informal_loan_payment_tenant_id"
    ON public.branch_informal_loan_payment (tenant_id);
CREATE INDEX IF NOT EXISTS "IX_branch_informal_loan_payment_loan_created"
    ON public.branch_informal_loan_payment (loan_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_branch_informal_loan_payment_expense_header"
    ON public.branch_informal_loan_payment (expense_header_id)
    WHERE expense_header_id IS NOT NULL;

ALTER TABLE public.branch_informal_loan_payment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_informal_loan_payment FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_select_policy ON public.branch_informal_loan_payment;
DROP POLICY IF EXISTS tenant_insert_policy ON public.branch_informal_loan_payment;
DROP POLICY IF EXISTS tenant_update_policy ON public.branch_informal_loan_payment;
DROP POLICY IF EXISTS tenant_delete_policy ON public.branch_informal_loan_payment;

CREATE POLICY tenant_select_policy ON public.branch_informal_loan_payment
    FOR SELECT USING (app.is_system_scope() OR tenant_id = app.current_tenant_id());
CREATE POLICY tenant_insert_policy ON public.branch_informal_loan_payment
    FOR INSERT WITH CHECK (app.is_system_scope() OR tenant_id = app.current_tenant_id());
CREATE POLICY tenant_update_policy ON public.branch_informal_loan_payment
    FOR UPDATE USING (app.is_system_scope() OR tenant_id = app.current_tenant_id())
    WITH CHECK (app.is_system_scope() OR tenant_id = app.current_tenant_id());
CREATE POLICY tenant_delete_policy ON public.branch_informal_loan_payment
    FOR DELETE USING (app.is_system_scope() OR tenant_id = app.current_tenant_id());

COMMIT;
