BEGIN;

CREATE TABLE IF NOT EXISTS delivery_tracking_incident (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_type varchar(30) NOT NULL DEFAULT 'stay',
    branch_id integer NOT NULL,
    deliveryman_id integer NOT NULL,
    work_session_id integer NOT NULL,
    delivery_stay_id bigint,
    source_device_event_id bigint,
    delivery_route_id integer,
    order_id integer,
    stay_classification varchar(40),
    classification_reason varchar(300),
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone NOT NULL,
    duration_seconds integer NOT NULL,
    center_latitude numeric(10,6),
    center_longitude numeric(10,6),
    radius_meters double precision NOT NULL,
    average_accuracy_meters double precision NOT NULL,
    distance_to_branch_meters double precision,
    distance_to_order_meters double precision,
    order_address_snapshot varchar(500),
    order_latitude_snapshot numeric(10,6),
    order_longitude_snapshot numeric(10,6),
    order_status_snapshot varchar(50),
    source_updated_at timestamp with time zone NOT NULL,
    evidence_captured_at timestamp with time zone NOT NULL,
    evidence_complete boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_tracking_incident_type
        CHECK (incident_type IN ('stay', 'route_deviation', 'location_disabled')),
    CONSTRAINT ck_delivery_tracking_incident_classification
        CHECK (stay_classification IS NULL OR stay_classification IN (
            'branch', 'order_destination', 'authorized_place', 'traffic_or_route',
            'unexpected_place', 'gps_unreliable', 'pending_review'
        )),
    CONSTRAINT ck_delivery_tracking_incident_period CHECK (ended_at >= started_at),
    CONSTRAINT ck_delivery_tracking_incident_latitude CHECK (center_latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_delivery_tracking_incident_longitude CHECK (center_longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_delivery_tracking_incident_order_latitude
        CHECK (order_latitude_snapshot IS NULL OR order_latitude_snapshot BETWEEN -90 AND 90),
    CONSTRAINT ck_delivery_tracking_incident_order_longitude
        CHECK (order_longitude_snapshot IS NULL OR order_longitude_snapshot BETWEEN -180 AND 180)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_tracking_incident_stay
    ON delivery_tracking_incident(delivery_stay_id)
    WHERE delivery_stay_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_tracking_incident_device_event
    ON delivery_tracking_incident(source_device_event_id)
    WHERE source_device_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_delivery_tracking_incident_branch_started
    ON delivery_tracking_incident(branch_id, started_at);
CREATE INDEX IF NOT EXISTS idx_delivery_tracking_incident_session_started
    ON delivery_tracking_incident(work_session_id, started_at);

CREATE TABLE IF NOT EXISTS delivery_incident_location_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id bigint NOT NULL REFERENCES delivery_tracking_incident(id) ON DELETE CASCADE,
    source_location_id bigint NOT NULL,
    client_point_id uuid,
    is_core_point boolean NOT NULL,
    latitude numeric(10,6) NOT NULL,
    longitude numeric(10,6) NOT NULL,
    accuracy_meters double precision,
    heading_degrees double precision,
    battery_level_percent integer,
    internet_available boolean,
    gps_enabled boolean,
    tracking_mode varchar(30),
    recorded_at timestamp with time zone NOT NULL,
    synced_at timestamp with time zone,
    CONSTRAINT ck_delivery_incident_location_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_delivery_incident_location_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_delivery_incident_location_battery
        CHECK (battery_level_percent IS NULL OR battery_level_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_incident_location_tracking_mode
        CHECK (tracking_mode IS NULL OR tracking_mode IN ('light', 'active_delivery', 'offline', 'stopped'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_incident_location_source
    ON delivery_incident_location_evidence(incident_id, source_location_id);
CREATE INDEX IF NOT EXISTS idx_delivery_incident_location_recorded
    ON delivery_incident_location_evidence(incident_id, recorded_at);

CREATE TABLE IF NOT EXISTS delivery_incident_device_event_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id bigint NOT NULL REFERENCES delivery_tracking_incident(id) ON DELETE CASCADE,
    source_device_event_id bigint NOT NULL,
    client_event_id uuid,
    event_type varchar(50) NOT NULL,
    battery_level_percent integer,
    internet_available boolean,
    gps_enabled boolean,
    location_permission_granted boolean,
    details varchar(500),
    recorded_at timestamp with time zone NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_delivery_incident_device_event_battery
        CHECK (battery_level_percent IS NULL OR battery_level_percent BETWEEN 0 AND 100)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_incident_device_event_source
    ON delivery_incident_device_event_evidence(incident_id, source_device_event_id);
CREATE INDEX IF NOT EXISTS idx_delivery_incident_device_event_recorded
    ON delivery_incident_device_event_evidence(incident_id, recorded_at);

COMMIT;
