BEGIN;

CREATE TABLE IF NOT EXISTS delivery_work_session (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deliveryman_id integer NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    device_installation_id varchar(64) NOT NULL,
    device_platform varchar(30) NOT NULL,
    device_description varchar(300),
    app_version varchar(40),
    started_at timestamp with time zone NOT NULL,
    auto_close_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    end_reason varchar(40),
    status varchar(20) NOT NULL DEFAULT 'active',
    last_communication_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_work_session_active_deliveryman
    ON delivery_work_session(deliveryman_id, status)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_delivery_work_session_branch_status_close
    ON delivery_work_session(branch_id, status, auto_close_at);

ALTER TABLE deliveryman_location
    ADD COLUMN IF NOT EXISTS work_session_id integer REFERENCES delivery_work_session(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_dloc_work_session
    ON deliveryman_location(work_session_id);

COMMIT;
