BEGIN;

CREATE TABLE IF NOT EXISTS whatsapp_commerce_session_token (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL DEFAULT 1,
    session_id integer NOT NULL REFERENCES whatsapp_commerce_session(id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_whatsapp_commerce_session_token_hash
    ON whatsapp_commerce_session_token(token_hash);
CREATE INDEX IF NOT EXISTS ix_whatsapp_commerce_session_token_active
    ON whatsapp_commerce_session_token(session_id, expires_at);

INSERT INTO whatsapp_commerce_session_token (tenant_id, session_id, token_hash, expires_at, created_at, updated_at)
SELECT tenant_id, id, flow_token_hash, expires_at, created_at, updated_at
FROM whatsapp_commerce_session
WHERE flow_token_hash IS NOT NULL AND flow_token_hash <> ''
ON CONFLICT (token_hash) DO NOTHING;

COMMIT;
