BEGIN;

CREATE TABLE IF NOT EXISTS tenant (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    slug varchar(100) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_tenant_slug ON tenant(slug);
INSERT INTO tenant(id, name, slug) VALUES (1, 'Señor Arroz', 'senor-arroz')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('tenant','id'), GREATEST(1,(SELECT max(id) FROM tenant)), true);

ALTER TABLE branch ADD COLUMN IF NOT EXISTS tenant_id integer;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS tenant_id integer;
ALTER TABLE address ADD COLUMN IF NOT EXISTS tenant_id integer;
ALTER TABLE neighborhood ADD COLUMN IF NOT EXISTS tenant_id integer;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS tenant_id integer;

CREATE OR REPLACE FUNCTION customer_address_normalize(value text)
RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
    SELECT btrim(regexp_replace(
        regexp_replace(
            regexp_replace(
                regexp_replace(
                    regexp_replace(
                    regexp_replace(
                        lower(translate(coalesce(value,''),'áéíóúüñÁÉÍÓÚÜÑ','aeiouunAEIOUUN')),
                        '[^[:alnum:]]+',' ','g'),
                    '\m(carrera|cra|cr)\M','kr','g'),
                '\m(calle|cl)\M','cl','g'),
            '\m(avenida|av)\M','av','g'),
        '\m(numero|nro|no)\M',' ','g'),
    '\s+',' ','g'))
$$;

CREATE TABLE IF NOT EXISTS customer_phone (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    customer_id integer NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
    phone_normalized varchar(10) NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_customer_phone_colombia CHECK (phone_normalized ~ '^3[0-9]{9}$')
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_customer_phone_customer_phone
    ON customer_phone(customer_id, phone_normalized);
CREATE INDEX IF NOT EXISTS ix_customer_phone_tenant_phone_premerge
    ON customer_phone(tenant_id, phone_normalized);
CREATE INDEX IF NOT EXISTS ix_customer_phone_customer ON customer_phone(customer_id);

CREATE TABLE IF NOT EXISTS address_branch (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    address_id integer NOT NULL REFERENCES address(id) ON DELETE CASCADE,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    neighborhood_id integer NULL REFERENCES neighborhood(id) ON DELETE RESTRICT,
    delivery_fee integer NOT NULL CHECK (delivery_fee >= 0),
    is_covered boolean NOT NULL DEFAULT true,
    validated_at timestamptz NULL,
    last_used_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_address_branch_tenant_address_branch
    ON address_branch(tenant_id, address_id, branch_id);
CREATE INDEX IF NOT EXISTS ix_address_branch_address ON address_branch(address_id);
CREATE INDEX IF NOT EXISTS ix_address_branch_branch ON address_branch(branch_id);
CREATE INDEX IF NOT EXISTS ix_address_branch_tenant_branch ON address_branch(tenant_id, branch_id);

CREATE TABLE IF NOT EXISTS customer_merge_run (
    id uuid PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    status varchar(30) NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz NULL,
    summary jsonb NULL
);
CREATE TABLE IF NOT EXISTS customer_merge_conflict (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merge_run_id uuid NOT NULL REFERENCES customer_merge_run(id) ON DELETE CASCADE,
    tenant_id integer NOT NULL,
    conflict_type varchar(60) NOT NULL,
    entity_ids integer[] NOT NULL,
    details jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS customer_merge_history (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
    old_customer_id integer NOT NULL REFERENCES customer(id) ON DELETE RESTRICT,
    new_customer_id integer NOT NULL REFERENCES customer(id) ON DELETE RESTRICT,
    merged_at timestamptz NOT NULL DEFAULT now(),
    reason varchar(200) NOT NULL,
    merge_run_id uuid NOT NULL REFERENCES customer_merge_run(id) ON DELETE RESTRICT,
    details jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_customer_merge_history_old ON customer_merge_history(tenant_id, old_customer_id);
CREATE INDEX IF NOT EXISTS ix_customer_merge_history_new ON customer_merge_history(new_customer_id);
CREATE INDEX IF NOT EXISTS ix_customer_merge_history_run ON customer_merge_history(merge_run_id);

COMMIT;
