BEGIN;

CREATE TABLE IF NOT EXISTS tenant (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name varchar(150) NOT NULL,
    slug varchar(100) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    status varchar(20) NOT NULL DEFAULT 'active',
    status_reason varchar(500),
    access_version bigint NOT NULL DEFAULT 1,
    contact_name varchar(150),
    contact_email varchar(254),
    contact_phone varchar(32),
    legal_name varchar(200),
    tax_id varchar(64),
    billing_address varchar(500),
    suspended_at timestamptz,
    cancelled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

ALTER TABLE tenant ADD COLUMN IF NOT EXISTS public_id uuid;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS status varchar(20);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS status_reason varchar(500);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS access_version bigint;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS contact_name varchar(150);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS contact_email varchar(254);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS contact_phone varchar(32);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS legal_name varchar(200);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS tax_id varchar(64);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS billing_address varchar(500);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS suspended_at timestamptz;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS cancelled_at timestamptz;

INSERT INTO tenant (id, public_id, name, slug, is_active, status, access_version, created_at, updated_at)
VALUES (
    1,
    '86ae3576-33db-483a-9a83-d9087a660651',
    U&'Se\00F1or Arroz',
    'senor-arroz',
    true,
    'active',
    1,
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

DO $$
DECLARE
    tenant_sequence text;
BEGIN
    tenant_sequence := pg_get_serial_sequence('tenant', 'id');
    IF tenant_sequence IS NOT NULL THEN
        PERFORM setval(tenant_sequence, GREATEST((SELECT MAX(id) FROM tenant), 1), true);
    END IF;
END $$;

UPDATE tenant
SET public_id = CASE
        WHEN id = 1 THEN '86ae3576-33db-483a-9a83-d9087a660651'::uuid
        ELSE gen_random_uuid()
    END
WHERE public_id IS NULL;

UPDATE tenant
SET status = CASE WHEN is_active THEN 'active' ELSE 'suspended' END
WHERE status IS NULL;

UPDATE tenant SET access_version = 1 WHERE access_version IS NULL OR access_version < 1;
ALTER TABLE tenant ALTER COLUMN public_id SET DEFAULT gen_random_uuid();
ALTER TABLE tenant ALTER COLUMN public_id SET NOT NULL;
ALTER TABLE tenant ALTER COLUMN status SET DEFAULT 'active';
ALTER TABLE tenant ALTER COLUMN status SET NOT NULL;
ALTER TABLE tenant ALTER COLUMN access_version SET DEFAULT 1;
ALTER TABLE tenant ALTER COLUMN access_version SET NOT NULL;

ALTER TABLE branch ADD COLUMN IF NOT EXISTS tenant_id integer;
UPDATE branch SET tenant_id = 1 WHERE tenant_id IS NULL;

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS tenant_id integer;
UPDATE "user" AS u
SET tenant_id = b.tenant_id
FROM branch AS b
WHERE u.branch_id = b.id
  AND u.tenant_id IS NULL;

ALTER TABLE refresh_token ADD COLUMN IF NOT EXISTS tenant_id integer;
UPDATE refresh_token AS token
SET tenant_id = u.tenant_id
FROM "user" AS u
WHERE token.user_id = u.id
  AND token.tenant_id IS NULL;

ALTER TABLE password_reset_token ADD COLUMN IF NOT EXISTS tenant_id integer;
UPDATE password_reset_token AS token
SET tenant_id = u.tenant_id
FROM "user" AS u
WHERE token.user_id = u.id
  AND token.tenant_id IS NULL;

ALTER TABLE user_device_token ADD COLUMN IF NOT EXISTS tenant_id integer;
UPDATE user_device_token AS token
SET tenant_id = u.tenant_id
FROM "user" AS u
WHERE token.user_id = u.id
  AND token.tenant_id IS NULL;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tenant GROUP BY slug HAVING COUNT(*) > 1) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existen tenants con slug duplicado';
    END IF;

    IF EXISTS (SELECT 1 FROM tenant GROUP BY public_id HAVING COUNT(*) > 1) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existen tenants con public_id duplicado';
    END IF;

    IF EXISTS (SELECT 1 FROM tenant WHERE status NOT IN ('draft', 'active', 'suspended', 'cancelled')) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existen tenants con status invalido';
    END IF;

    IF EXISTS (SELECT 1 FROM tenant WHERE id = 1 AND (status <> 'active' OR NOT is_active OR access_version < 1)) THEN
        RAISE EXCEPTION 'multitenant_core_v2: el tenant 1 debe estar activo y tener access_version valido';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM branch AS b
        LEFT JOIN tenant AS t ON t.id = b.tenant_id
        WHERE b.tenant_id IS NULL OR t.id IS NULL
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe una branch sin tenant valido';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM "user" AS u
        LEFT JOIN branch AS b ON b.id = u.branch_id
        WHERE b.id IS NULL
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un user sin branch valida';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM "user" AS u
        JOIN branch AS b ON b.id = u.branch_id
        LEFT JOIN tenant AS t ON t.id = b.tenant_id
        WHERE t.id IS NULL
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un user cuya branch no tiene tenant valido';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM "user" AS u
        JOIN branch AS b ON b.id = u.branch_id
        WHERE u.tenant_id IS NULL OR u.tenant_id <> b.tenant_id
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un user cuyo tenant no coincide con su branch';
    END IF;

    IF EXISTS (
        SELECT 1 FROM refresh_token AS token
        LEFT JOIN "user" AS u ON u.id = token.user_id
        WHERE u.id IS NULL
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un refresh_token sin user valido';
    END IF;

    IF EXISTS (
        SELECT 1 FROM password_reset_token AS token
        LEFT JOIN "user" AS u ON u.id = token.user_id
        WHERE u.id IS NULL
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un password_reset_token sin user valido';
    END IF;

    IF EXISTS (
        SELECT 1 FROM user_device_token AS token
        LEFT JOIN "user" AS u ON u.id = token.user_id
        WHERE u.id IS NULL
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un user_device_token sin user valido';
    END IF;

    IF EXISTS (
        SELECT 1 FROM refresh_token AS token
        JOIN "user" AS u ON u.id = token.user_id
        WHERE token.tenant_id IS NULL OR token.tenant_id <> u.tenant_id
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un refresh_token con tenant inconsistente';
    END IF;

    IF EXISTS (
        SELECT 1 FROM password_reset_token AS token
        JOIN "user" AS u ON u.id = token.user_id
        WHERE token.tenant_id IS NULL OR token.tenant_id <> u.tenant_id
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un password_reset_token con tenant inconsistente';
    END IF;

    IF EXISTS (
        SELECT 1 FROM user_device_token AS token
        JOIN "user" AS u ON u.id = token.user_id
        WHERE token.tenant_id IS NULL OR token.tenant_id <> u.tenant_id
    ) THEN
        RAISE EXCEPTION 'multitenant_core_v2: existe un user_device_token con tenant inconsistente';
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_tenant_public_id ON tenant(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_tenant_slug ON tenant(slug);
CREATE INDEX IF NOT EXISTS idx_branch_tenant_id ON branch(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_branch_tenant_id_id ON branch(tenant_id, id);
CREATE INDEX IF NOT EXISTS idx_user_tenant_branch ON "user"(tenant_id, branch_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_tenant_id_id ON "user"(tenant_id, id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_tenant_user ON refresh_token(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_tenant_user ON password_reset_token(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_user_device_token_tenant_user ON user_device_token(tenant_id, user_id);

ALTER TABLE branch ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "user" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE refresh_token ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE password_reset_token ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE user_device_token ALTER COLUMN tenant_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_tenant_status') THEN
        ALTER TABLE tenant ADD CONSTRAINT ck_tenant_status
            CHECK (status IN ('draft', 'active', 'suspended', 'cancelled'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_tenant_access_version_positive') THEN
        ALTER TABLE tenant ADD CONSTRAINT ck_tenant_access_version_positive
            CHECK (access_version > 0);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_branch_tenant') THEN
        ALTER TABLE branch ADD CONSTRAINT fk_branch_tenant
            FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_tenant') THEN
        ALTER TABLE "user" ADD CONSTRAINT fk_user_tenant
            FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_tenant_branch') THEN
        ALTER TABLE "user" ADD CONSTRAINT fk_user_tenant_branch
            FOREIGN KEY (tenant_id, branch_id) REFERENCES branch(tenant_id, id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_refresh_token_tenant') THEN
        ALTER TABLE refresh_token ADD CONSTRAINT fk_refresh_token_tenant
            FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_refresh_token_tenant_user') THEN
        ALTER TABLE refresh_token ADD CONSTRAINT fk_refresh_token_tenant_user
            FOREIGN KEY (tenant_id, user_id) REFERENCES "user"(tenant_id, id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_password_reset_token_tenant') THEN
        ALTER TABLE password_reset_token ADD CONSTRAINT fk_password_reset_token_tenant
            FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_password_reset_token_tenant_user') THEN
        ALTER TABLE password_reset_token ADD CONSTRAINT fk_password_reset_token_tenant_user
            FOREIGN KEY (tenant_id, user_id) REFERENCES "user"(tenant_id, id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_device_token_tenant') THEN
        ALTER TABLE user_device_token ADD CONSTRAINT fk_user_device_token_tenant
            FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_device_token_tenant_user') THEN
        ALTER TABLE user_device_token ADD CONSTRAINT fk_user_device_token_tenant_user
            FOREIGN KEY (tenant_id, user_id) REFERENCES "user"(tenant_id, id) ON DELETE CASCADE;
    END IF;
END $$;

COMMIT;
