BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS delivery_app_connection (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE CASCADE,
    provider varchar(40) NOT NULL,
    environment varchar(20) NOT NULL DEFAULT 'sandbox',
    display_name varchar(100) NOT NULL DEFAULT 'Rappi',
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    financial_app_id integer NOT NULL REFERENCES app(id) ON DELETE RESTRICT,
    customer_id integer REFERENCES customer(id) ON DELETE RESTRICT,
    technical_user_id integer REFERENCES "user"(id) ON DELETE RESTRICT,
    default_cooking_time_minutes integer NOT NULL DEFAULT 30,
    estimated_commission_rate numeric(8,6) NOT NULL DEFAULT 0.25,
    pii_retention_days integer NOT NULL DEFAULT 90,
    webhook_configured boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT false,
    is_verified boolean NOT NULL DEFAULT false,
    last_verified_at timestamp with time zone,
    last_menu_published_at timestamp with time zone,
    last_availability_sync_at timestamp with time zone,
    last_webhook_at timestamp with time zone,
    last_error varchar(1000),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ux_delivery_app_connection_branch_provider UNIQUE(branch_id, provider)
);

ALTER TABLE delivery_app_connection
    ADD COLUMN IF NOT EXISTS public_id uuid DEFAULT gen_random_uuid(),
    ADD COLUMN IF NOT EXISTS client_id varchar(255),
    ADD COLUMN IF NOT EXISTS encrypted_client_secret text,
    ADD COLUMN IF NOT EXISTS external_store_id varchar(120),
    ADD COLUMN IF NOT EXISTS encrypted_webhook_secret text,
    ADD COLUMN IF NOT EXISTS customer_id integer,
    ADD COLUMN IF NOT EXISTS technical_user_id integer,
    ADD COLUMN IF NOT EXISTS estimated_commission_rate numeric(8,6) NOT NULL DEFAULT 0.25,
    ADD COLUMN IF NOT EXISTS pii_retention_days integer NOT NULL DEFAULT 90,
    ADD COLUMN IF NOT EXISTS last_menu_published_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS last_availability_sync_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS last_webhook_at timestamp with time zone;

UPDATE delivery_app_connection SET public_id = gen_random_uuid() WHERE public_id IS NULL;
ALTER TABLE delivery_app_connection ALTER COLUMN public_id SET NOT NULL;
ALTER TABLE delivery_app_connection ALTER COLUMN client_id DROP NOT NULL;
ALTER TABLE delivery_app_connection ALTER COLUMN encrypted_client_secret DROP NOT NULL;
ALTER TABLE delivery_app_connection ALTER COLUMN external_store_id DROP NOT NULL;
UPDATE delivery_app_connection
SET client_id = NULL,
    encrypted_client_secret = NULL,
    encrypted_webhook_secret = NULL,
    environment = 'sandbox'
WHERE provider = 'rappi';
ALTER TABLE delivery_app_connection
    DROP COLUMN IF EXISTS client_id,
    DROP COLUMN IF EXISTS encrypted_client_secret,
    DROP COLUMN IF EXISTS external_store_id,
    DROP COLUMN IF EXISTS encrypted_webhook_secret;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_delivery_app_connection_customer') THEN
        ALTER TABLE delivery_app_connection
            ADD CONSTRAINT fk_delivery_app_connection_customer
            FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_delivery_app_connection_technical_user') THEN
        ALTER TABLE delivery_app_connection
            ADD CONSTRAINT fk_delivery_app_connection_technical_user
            FOREIGN KEY (technical_user_id) REFERENCES "user"(id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_delivery_app_connection_public_id
    ON delivery_app_connection(public_id);

CREATE TABLE IF NOT EXISTS delivery_app_store (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id integer NOT NULL REFERENCES delivery_app_connection(id) ON DELETE CASCADE,
    rappi_store_id varchar(120) NOT NULL,
    store_integration_id varchar(120),
    name varchar(160) NOT NULL,
    is_parent boolean NOT NULL DEFAULT false,
    manual_ready_for_pickup_enabled boolean NOT NULL DEFAULT false,
    connectivity_enabled boolean,
    last_ping_at timestamp with time zone,
    last_connectivity_at timestamp with time zone,
    last_error varchar(1000),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ux_delivery_app_store_rappi UNIQUE(connection_id, rappi_store_id)
);

INSERT INTO delivery_app_store(connection_id, rappi_store_id, name, is_parent)
SELECT id, '900173116', 'Señor Arroz Dev1', true
FROM delivery_app_connection c
WHERE c.provider = 'rappi'
  AND NOT EXISTS (
      SELECT 1 FROM delivery_app_store s
      WHERE s.connection_id = c.id AND s.rappi_store_id = '900173116'
  );

INSERT INTO delivery_app_store(connection_id, rappi_store_id, name, is_parent)
SELECT id, '900173117', 'Señor Arroz Dev2', false
FROM delivery_app_connection c
WHERE c.provider = 'rappi'
  AND NOT EXISTS (
      SELECT 1 FROM delivery_app_store s
      WHERE s.connection_id = c.id AND s.rappi_store_id = '900173117'
  );

CREATE TABLE IF NOT EXISTS delivery_app_webhook_subscription (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id integer NOT NULL REFERENCES delivery_app_connection(id) ON DELETE CASCADE,
    event_type varchar(80) NOT NULL,
    encrypted_secret text NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    last_received_at timestamp with time zone,
    last_error varchar(1000),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ux_delivery_app_webhook_event UNIQUE(connection_id, event_type)
);

CREATE TABLE IF NOT EXISTS delivery_app_product_mapping (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id integer NOT NULL REFERENCES delivery_app_connection(id) ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
    sku varchar(160) NOT NULL,
    category_sku varchar(160) NOT NULL,
    is_selected boolean NOT NULL DEFAULT true,
    override_name varchar(300),
    override_description varchar(1000),
    override_image_url varchar(1000),
    override_price integer,
    published_name varchar(300),
    published_description varchar(1000),
    published_image_url varchar(1000),
    published_price integer,
    published_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE delivery_app_product_mapping
    ADD COLUMN IF NOT EXISTS external_product_id varchar(160),
    ADD COLUMN IF NOT EXISTS external_sku varchar(160),
    ADD COLUMN IF NOT EXISTS external_name varchar(300),
    ADD COLUMN IF NOT EXISTS item_type varchar(30),
    ADD COLUMN IF NOT EXISTS is_active boolean,
    ADD COLUMN IF NOT EXISTS sku varchar(160),
    ADD COLUMN IF NOT EXISTS category_sku varchar(160),
    ADD COLUMN IF NOT EXISTS is_selected boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS override_name varchar(300),
    ADD COLUMN IF NOT EXISTS override_description varchar(1000),
    ADD COLUMN IF NOT EXISTS override_image_url varchar(1000),
    ADD COLUMN IF NOT EXISTS override_price integer,
    ADD COLUMN IF NOT EXISTS published_name varchar(300),
    ADD COLUMN IF NOT EXISTS published_description varchar(1000),
    ADD COLUMN IF NOT EXISTS published_image_url varchar(1000),
    ADD COLUMN IF NOT EXISTS published_price integer,
    ADD COLUMN IF NOT EXISTS published_at timestamp with time zone;

DELETE FROM delivery_app_product_mapping WHERE product_id IS NULL;
UPDATE delivery_app_product_mapping
SET sku = COALESCE(NULLIF(sku, ''), 'product-' || product_id),
    category_sku = COALESCE(
        NULLIF(category_sku, ''),
        'category-' || (SELECT p.category_id FROM product p WHERE p.id = product_id)
    ),
    is_selected = COALESCE(is_selected, true)
WHERE product_id IS NOT NULL;
ALTER TABLE delivery_app_product_mapping ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE delivery_app_product_mapping ALTER COLUMN sku SET NOT NULL;
ALTER TABLE delivery_app_product_mapping ALTER COLUMN category_sku SET NOT NULL;
ALTER TABLE delivery_app_product_mapping ALTER COLUMN external_product_id DROP NOT NULL;
ALTER TABLE delivery_app_product_mapping ALTER COLUMN external_sku DROP NOT NULL;
ALTER TABLE delivery_app_product_mapping ALTER COLUMN external_name DROP NOT NULL;
DELETE FROM delivery_app_product_mapping older
USING delivery_app_product_mapping newer
WHERE older.connection_id = newer.connection_id
  AND older.product_id = newer.product_id
  AND older.id < newer.id;
DROP INDEX IF EXISTS ux_delivery_app_mapping_external;
CREATE UNIQUE INDEX IF NOT EXISTS ux_delivery_app_mapping_product
    ON delivery_app_product_mapping(connection_id, product_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_delivery_app_mapping_sku
    ON delivery_app_product_mapping(connection_id, sku);

CREATE TABLE IF NOT EXISTS external_delivery_order (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id integer NOT NULL REFERENCES delivery_app_connection(id) ON DELETE CASCADE,
    store_id integer REFERENCES delivery_app_store(id) ON DELETE RESTRICT,
    branch_id integer NOT NULL REFERENCES branch(id) ON DELETE CASCADE,
    external_order_id varchar(160) NOT NULL,
    external_store_id varchar(120) NOT NULL DEFAULT '',
    status varchar(40) NOT NULL,
    customer_name varchar(200) NOT NULL DEFAULT '',
    customer_phone varchar(50),
    delivery_address varchar(600),
    delivery_method varchar(40) NOT NULL DEFAULT '',
    payment_method varchar(60) NOT NULL DEFAULT '',
    total integer NOT NULL DEFAULT 0,
    total_products integer NOT NULL DEFAULT 0,
    total_discounts integer NOT NULL DEFAULT 0,
    total_discount_by_partner integer NOT NULL DEFAULT 0,
    total_discount_by_rappi integer NOT NULL DEFAULT 0,
    total_charges integer NOT NULL DEFAULT 0,
    cooking_time_minutes integer NOT NULL DEFAULT 30,
    raw_payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    lines_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    discounts_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    validation_errors_json jsonb,
    internal_order_id integer REFERENCES "order"(id) ON DELETE SET NULL,
    accepted_by_user_id integer REFERENCES "user"(id) ON DELETE SET NULL,
    accepted_at timestamp with time zone,
    last_attempt_at timestamp with time zone,
    pii_purged_at timestamp with time zone,
    last_error varchar(1000),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ux_external_delivery_order_provider_id UNIQUE(connection_id, external_order_id)
);

ALTER TABLE external_delivery_order
    ADD COLUMN IF NOT EXISTS store_id integer,
    ADD COLUMN IF NOT EXISTS total_products integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_discounts integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_discount_by_partner integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_discount_by_rappi integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_charges integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS discounts_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS validation_errors_json jsonb,
    ADD COLUMN IF NOT EXISTS last_attempt_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS pii_purged_at timestamp with time zone;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_external_delivery_order_store') THEN
        ALTER TABLE external_delivery_order
            ADD CONSTRAINT fk_external_delivery_order_store
            FOREIGN KEY (store_id) REFERENCES delivery_app_store(id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS integration_webhook_event (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id integer NOT NULL REFERENCES delivery_app_connection(id) ON DELETE CASCADE,
    provider varchar(40) NOT NULL,
    event_key varchar(200) NOT NULL,
    event_type varchar(80) NOT NULL,
    payload_hash varchar(64) NOT NULL DEFAULT '',
    payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    status varchar(40) NOT NULL DEFAULT 'received',
    attempt_count integer NOT NULL DEFAULT 0,
    last_error varchar(1000),
    processed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ux_integration_webhook_event_key UNIQUE(connection_id, event_key)
);
ALTER TABLE integration_webhook_event
    ADD COLUMN IF NOT EXISTS payload_hash varchar(64) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS rappi_menu_publication (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id integer NOT NULL REFERENCES delivery_app_connection(id) ON DELETE CASCADE,
    store_id varchar(120) NOT NULL,
    payload_hash varchar(64) NOT NULL,
    payload_json jsonb NOT NULL,
    status varchar(40) NOT NULL DEFAULT 'pending',
    error varchar(1000),
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rappi_availability_state (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id integer NOT NULL REFERENCES delivery_app_connection(id) ON DELETE CASCADE,
    store_id integer NOT NULL REFERENCES delivery_app_store(id) ON DELETE CASCADE,
    product_mapping_id integer NOT NULL REFERENCES delivery_app_product_mapping(id) ON DELETE CASCADE,
    desired_available boolean NOT NULL,
    last_synced_available boolean,
    status varchar(40) NOT NULL DEFAULT 'pending',
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamp with time zone,
    last_error varchar(1000),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ux_rappi_availability_store_product UNIQUE(store_id, product_mapping_id)
);

ALTER TABLE app_payment
    ADD COLUMN IF NOT EXISTS estimated_commission_rate numeric(8,6),
    ADD COLUMN IF NOT EXISTS estimated_commission_amount numeric(12,2),
    ADD COLUMN IF NOT EXISTS expected_net_amount numeric(12,2),
    ADD COLUMN IF NOT EXISTS actual_settled_amount numeric(12,2),
    ADD COLUMN IF NOT EXISTS settlement_variance numeric(12,2),
    ADD COLUMN IF NOT EXISTS is_reversed boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS reversed_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS reversal_reason varchar(300);

ALTER TABLE "order"
    ADD COLUMN IF NOT EXISTS delivery_app_connection_id integer REFERENCES delivery_app_connection(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS external_order_id varchar(160),
    ADD COLUMN IF NOT EXISTS order_source varchar(40),
    ADD COLUMN IF NOT EXISTS external_fulfillment_provider varchar(40),
    ADD COLUMN IF NOT EXISTS external_store_name varchar(200),
    ADD COLUMN IF NOT EXISTS external_customer_phone varchar(50),
    ADD COLUMN IF NOT EXISTS external_delivery_address varchar(600),
    ADD COLUMN IF NOT EXISTS external_total_discounts integer,
    ADD COLUMN IF NOT EXISTS external_discount_by_rappi integer,
    ADD COLUMN IF NOT EXISTS external_discount_by_partner integer,
    ADD COLUMN IF NOT EXISTS external_charges integer;

CREATE UNIQUE INDEX IF NOT EXISTS ux_order_external_source
    ON "order"(delivery_app_connection_id, external_order_id)
    WHERE external_order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_external_delivery_order_branch_status
    ON external_delivery_order(branch_id, status);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_event_pending
    ON integration_webhook_event(status, created_at)
    WHERE provider = 'rappi';
CREATE INDEX IF NOT EXISTS idx_rappi_availability_pending
    ON rappi_availability_state(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_rappi_menu_publication_connection
    ON rappi_menu_publication(connection_id, created_at);

INSERT INTO "user"(branch_id, role, name, email, phone, password_hash, active)
SELECT b.id, 'cashier', 'Integración Rappi',
       'integracion-rappi@senorarroz.internal', '0000000000', '', false
FROM branch b
WHERE b.name = 'Santander'
  AND NOT EXISTS (
      SELECT 1 FROM "user" u
      WHERE u.branch_id = b.id
        AND u.email = 'integracion-rappi@senorarroz.internal'
  );

COMMIT;
