namespace SenorArroz.Domain.Enums;
public enum WhatsAppOrderDraftStatus{Building,AwaitingCustomerData,AwaitingAddress,AwaitingPayment,ReadyForConfirmation,Confirmed,Cancelled,Expired,ConvertedToOrder}
