-- =============================================================================
-- Impresión de comandas: branch_print_settings + print_job
-- Idempotente para producción (IF NOT EXISTS).
-- =============================================================================

CREATE TABLE IF NOT EXISTS branch_print_settings (
    branch_id integer NOT NULL,
    kitchen_header_line1 character varying(80),
    kitchen_header_line2 character varying(80),
    show_kitchen_order_number boolean NOT NULL DEFAULT true,
    show_kitchen_time boolean NOT NULL DEFAULT true,
    show_kitchen_notes boolean NOT NULL DEFAULT true,
    delivery_show_line_subtotals boolean NOT NULL DEFAULT true,
    delivery_show_payments boolean NOT NULL DEFAULT true,
    delivery_show_loyalty_footer boolean NOT NULL DEFAULT true,
    cashier_mirror_delivery_layout boolean NOT NULL DEFAULT false,
    footer_message_kitchen character varying(200),
    footer_message_delivery character varying(200),
    footer_message_cashier character varying(200),
    paper_width_mm smallint NOT NULL DEFAULT 57,
    enable_kitchen_jobs boolean NOT NULL DEFAULT true,
    enable_delivery_jobs boolean NOT NULL DEFAULT true,
    enable_cashier_jobs boolean NOT NULL DEFAULT false,
    agent_token_hash character varying(128) NOT NULL DEFAULT '',
    agent_token_salt character varying(64) NOT NULL DEFAULT '',
    agent_token_updated_at timestamp with time zone,
    printer_queue_kitchen character varying(128),
    printer_queue_delivery character varying(128),
    printer_queue_cashier character varying(128),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_branch_print_settings" PRIMARY KEY (branch_id),
    CONSTRAINT "FK_branch_print_settings_branch" FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS print_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    kind character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    order_ids_json jsonb NOT NULL,
    payload_json jsonb NOT NULL,
    payload_version smallint NOT NULL DEFAULT 1,
    error_message character varying(500),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    CONSTRAINT "PK_print_job" PRIMARY KEY (id),
    CONSTRAINT "FK_print_job_branch" FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE CASCADE,
    CONSTRAINT "CK_print_job_kind" CHECK (kind IN ('kitchen','delivery','cashier')),
    CONSTRAINT "CK_print_job_status" CHECK (status IN ('pending','processing','done','failed'))
);

CREATE INDEX IF NOT EXISTS "IX_print_job_branch_pending"
    ON print_job (branch_id, created_at)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS "IX_print_job_branch_processing"
    ON print_job (branch_id, started_at)
    WHERE status = 'processing';

-- Filas por sucursal existente sin settings (token vacío = agente deshabilitado hasta configurar en admin)
INSERT INTO branch_print_settings (branch_id)
SELECT b.id FROM branch b
WHERE NOT EXISTS (SELECT 1 FROM branch_print_settings s WHERE s.branch_id = b.id)
ON CONFLICT (branch_id) DO NOTHING;
