-- Fidelización por ciclo (loyalty_cycle_step) + columnas en order. Idempotente.
-- Ejecutar en producción tras backup.
-- Si la BD aún tiene loyalty_rule / order.loyalty_rule_id, aplicar antes o después según convenga:
--   recomendado: primero este script (nuevas columnas y FK), luego Scripts/drop-legacy-loyalty-rule.sql

CREATE TABLE IF NOT EXISTS loyalty_cycle_step (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    step_index integer NOT NULL,
    reward_label text NOT NULL,
    step_name character varying(200),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_loyalty_cycle_step" PRIMARY KEY (id),
    CONSTRAINT "FK_loyalty_cycle_step_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
    CONSTRAINT "UQ_loyalty_cycle_step_branch_step" UNIQUE (branch_id, step_index)
);

CREATE INDEX IF NOT EXISTS "IX_loyalty_cycle_step_branch_id" ON loyalty_cycle_step (branch_id);

ALTER TABLE "order" ADD COLUMN IF NOT EXISTS loyalty_cycle_step_id integer NULL;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS loyalty_reward_snapshot character varying(500) NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_order_loyalty_cycle_step_loyalty_cycle_step_id'
    ) THEN
        ALTER TABLE "order"
            ADD CONSTRAINT "FK_order_loyalty_cycle_step_loyalty_cycle_step_id"
            FOREIGN KEY (loyalty_cycle_step_id) REFERENCES loyalty_cycle_step (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_order_loyalty_cycle_step" ON "order" (loyalty_cycle_step_id);

-- Datos del ciclo (45 pasos) por sucursal existente, sin duplicar filas
INSERT INTO loyalty_cycle_step (branch_id, step_index, reward_label)
SELECT b.id, v.step_idx, v.lbl
FROM branch b
CROSS JOIN (
    VALUES
        (1, 'Domicilio gratis 3k'),
        (2, '5% descuento'),
        (3, 'Yucas gratis'),
        (4, '10% descuento'),
        (5, 'bebida gratis'),
        (6, '15% de descuento'),
        (7, 'Ad costilla bbq gratis'),
        (8, '20% descuento'),
        (9, 'bebida gratis'),
        (10, '25% descuento'),
        (11, 'chicharron gratis'),
        (12, '30% descuento'),
        (13, 'yuca gratis'),
        (14, 'papas gratis'),
        (15, 'bebida gratis'),
        (16, '50% descuento'),
        (17, 'yuca gratis'),
        (18, 'papas gratis'),
        (19, 'bebida gratis'),
        (20, '100% descuento'),
        (21, '5% descuento'),
        (22, 'yuca gratis'),
        (23, '10% descuento'),
        (24, 'papas gratis'),
        (25, 'bebida gratis'),
        (26, '15% de descuento'),
        (27, 'chuleta pollo gratis'),
        (28, '20% descuento'),
        (29, 'chuleta cerdo gratis'),
        (30, 'chicharron gratis'),
        (31, '25% descuento'),
        (32, 'costilla gratis'),
        (33, 'yuca gratis'),
        (34, 'papas gratis'),
        (35, 'bebida gratis'),
        (36, '50% descuento'),
        (37, 'yuca gratis'),
        (38, 'papas gratis'),
        (39, 'bebida gratis'),
        (40, '100% descuento'),
        (41, '5% descuento'),
        (42, 'yuca gratis'),
        (43, '10% descuento'),
        (44, 'papas gratis'),
        (45, 'bebida gratis')
) AS v(step_idx, lbl)
WHERE NOT EXISTS (
    SELECT 1 FROM loyalty_cycle_step s WHERE s.branch_id = b.id AND s.step_index = v.step_idx
);
