-- Préstamos informales por sucursal (fuente de verdad; ya no se guardan en el cierre).
-- Ejecutar en producción una vez.

CREATE TABLE IF NOT EXISTS branch_informal_loan (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    concept character varying(200) NOT NULL,
    amount numeric(12,2) NOT NULL DEFAULT 0,
    created_by_id integer NOT NULL,
    deactivated_at timestamp with time zone NULL,
    deactivated_by_id integer NULL,
    deactivation_notes character varying(500) NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_branch_informal_loan" PRIMARY KEY (id),
    CONSTRAINT "FK_branch_informal_loan_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_branch_informal_loan_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_branch_informal_loan_user_deactivated_by_id" FOREIGN KEY (deactivated_by_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_branch_informal_loan_branch_id" ON branch_informal_loan (branch_id);
CREATE INDEX IF NOT EXISTS "IX_branch_informal_loan_branch_id_deactivated_at" ON branch_informal_loan (branch_id, deactivated_at);
