-- =============================================================================
-- Tabla expense_menu_target: imputación de gastos de catálogo a menú (por gramos).
-- Idempotente: seguro ejecutar varias veces en una BD que ya tiene el esquema base.
--
-- Uso (ejemplo):
--   psql -h localhost -p 5433 -U postgres -d senorArroz -f Scripts/add-expense-menu-target.sql
--
-- Paridad con Scripts/local-init-completo.sql (misma definición).
-- target_type: 0 = categoría de producto (product_category.id), 1 = producto (product.id)
-- =============================================================================

CREATE TABLE IF NOT EXISTS expense_menu_target (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    expense_id integer NOT NULL,
    target_type integer NOT NULL,
    target_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_expense_menu_target" PRIMARY KEY (id),
    CONSTRAINT "FK_expense_menu_target_expense_expense_id" FOREIGN KEY (expense_id) REFERENCES expense (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_expense_menu_target_expense_id_target_type_target_id"
    ON expense_menu_target (expense_id, target_type, target_id);

CREATE INDEX IF NOT EXISTS "IX_expense_menu_target_expense_id" ON expense_menu_target (expense_id);

DROP TRIGGER IF EXISTS update_expense_menu_target_updated_at ON public.expense_menu_target;
CREATE TRIGGER update_expense_menu_target_updated_at
    BEFORE UPDATE ON public.expense_menu_target
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
