START TRANSACTION;
ALTER TABLE supplier ADD branch_id integer NOT NULL DEFAULT 0;

CREATE TABLE supplier_expense (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    supplier_id integer NOT NULL,
    expense_id integer NOT NULL,
    usage_count integer NOT NULL DEFAULT 0,
    last_used_at timestamp with time zone,
    last_unit_price numeric(18,2),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_supplier_expense" PRIMARY KEY (id),
    CONSTRAINT "FK_supplier_expense_expense_expense_id" FOREIGN KEY (expense_id) REFERENCES expense (id) ON DELETE CASCADE,
    CONSTRAINT "FK_supplier_expense_supplier_supplier_id" FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE
);

CREATE INDEX idx_supplier_branch_name ON supplier (branch_id, name);

CREATE INDEX "IX_supplier_expense_expense_id" ON supplier_expense (expense_id);

CREATE UNIQUE INDEX "IX_supplier_expense_supplier_id_expense_id" ON supplier_expense (supplier_id, expense_id);

ALTER TABLE supplier ADD CONSTRAINT "FK_supplier_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251129224645_AddSupplierExpense', '9.0.8');

COMMIT;

