\encoding UTF8
SET client_encoding = 'UTF8';

-- =============================================================================
-- Señor Arroz - Script de inicialización completa para base de datos local
-- =============================================================================
--
-- USO (base de datos vacía):
--   Recomendado: desde SenorArroz/ ejecutar Scripts/reset-local-db.sh o reset-local-db.ps1
--   Manual (puerto 5433, BD "senorArroz"):
--     psql -h localhost -p 5433 -U postgres -d postgres -c 'DROP DATABASE IF EXISTS "senorArroz";'
--     psql -h localhost -p 5433 -U postgres -d postgres -c 'CREATE DATABASE "senorArroz";'
--     psql -h localhost -p 5433 -U postgres -d senorArroz -f Scripts/local-init-completo.sql
--
-- Incluye: tablas, índices, funciones, triggers, datos semilla y todas las
-- modificaciones: loyalty_cycle_step (fidelidad por ciclo), columnas order.loyalty_*,
-- supplier.branch_id, expense_header.created_by_id,
-- supplier_expense, deliveryman_advance (payment_method, bank_id, expense_header_id),
-- deliveryman_day_state (liquidación / bloqueo día, last_liquidation_at_utc para ciclos mismo día),
--   bases existentes: Scripts/add-deliveryman-day-state-last-liquidation-at.sql
-- expense_header.deliveryman_id,
-- branch.latitude/longitude (modelo EF / joins), verified_at, guestname, is_primary,
-- prepare_at, bank.type, bank_transfer, cash_register_closure, product.weight_grams,
-- expense_detail.quantity decimal y totales (paridad con update-expense-quantity-decimal.sql)
-- y tablas hijas.
--
-- Paridad con scripts sueltos (misma semántica, idempotente):
--   Scripts/deliveryman-liquidation-schema.sql (+ branch lat/long + last_liquidation_at_utc)
--   Scripts/add-deliveryman-day-state-last-liquidation-at.sql (ALTER si la tabla ya existía sin la columna)
--   Scripts/add-branch-latitude-longitude.sql (incluido en el bloque anterior)
--   Scripts/update-product-table.sql (weight_grams en product)
--   Scripts/update-expense-quantity-decimal.sql (tipos expense_detail / expense_header.total)
--   Scripts/update-product-weights-by-size.sql = solo datos UPDATE (no se incluye aquí)
--   Scripts/add-expense-menu-target.sql (imputación gastos → menú por gramos; paridad con esta sección)
--
-- =============================================================================

-- Eliminar esquema público si existe (OPCIONAL - descomentar si quieres empezar de cero absoluto)
-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- =============================================================================
-- TABLAS (InitialSchema + modificaciones posteriores)
-- =============================================================================

CREATE TABLE IF NOT EXISTS branch (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    business_name character varying(150),
    nit character varying(32),
    address character varying(200) NOT NULL,
    phone1 character varying(10) NOT NULL,
    phone2 character varying(10),
    latitude numeric(10,6),
    longitude numeric(10,6),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_branch" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS expense_category (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_expense_category" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS supplier (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(10) NOT NULL,
    address character varying(200),
    email character varying(200),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_supplier" PRIMARY KEY (id),
    CONSTRAINT "FK_supplier_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS bank (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    name character varying(150) NOT NULL,
    image_url character varying(200),
    active boolean NOT NULL DEFAULT TRUE,
    -- 0=Normal, 1=CashVault (caja mayor efectivo), 2=RealVault (caja mayor banco)
    type integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_bank" PRIMARY KEY (id),
    CONSTRAINT "FK_bank_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS customer (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    name character varying(150) NOT NULL,
    phone1 character varying(10) NOT NULL,
    phone2 character varying(10),
    active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_customer" PRIMARY KEY (id),
    CONSTRAINT "FK_customer_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS loyalty_cycle_step (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    step_index integer NOT NULL,
    reward_label text NOT NULL,
    step_name character varying(200),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_loyalty_cycle_step" PRIMARY KEY (id),
    CONSTRAINT "FK_loyalty_cycle_step_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
    CONSTRAINT "UQ_loyalty_cycle_step_branch_step" UNIQUE (branch_id, step_index)
);

CREATE INDEX IF NOT EXISTS "IX_loyalty_cycle_step_branch_id" ON loyalty_cycle_step (branch_id);

CREATE TABLE IF NOT EXISTS neighborhood (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    name character varying(150) NOT NULL,
    delivery_fee integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_neighborhood" PRIMARY KEY (id),
    CONSTRAINT "FK_neighborhood_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS product_category (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    name character varying(150) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_product_category" PRIMARY KEY (id),
    CONSTRAINT "FK_product_category_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "user" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    role text DEFAULT 'deliveryman',
    name character varying(150) NOT NULL,
    email character varying(100) NOT NULL,
    phone character varying(10) NOT NULL,
    password_hash character varying(255) NOT NULL,
    active boolean NOT NULL DEFAULT TRUE,
    profile_image_url character varying(300),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_user" PRIMARY KEY (id),
    CONSTRAINT "FK_user_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS expense (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    category_id integer NOT NULL,
    unit character varying(50) NOT NULL DEFAULT 'unit',
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_expense" PRIMARY KEY (id),
    CONSTRAINT "FK_expense_expense_category_category_id" FOREIGN KEY (category_id) REFERENCES expense_category (id) ON DELETE RESTRICT
);

-- Imputación de gastos de catálogo a categorías/productos de menú (reparto por gramos vendidos; target_type 0=categoría, 1=producto)
CREATE TABLE IF NOT EXISTS expense_menu_target (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    expense_id integer NOT NULL,
    target_type integer NOT NULL,
    target_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_expense_menu_target" PRIMARY KEY (id),
    CONSTRAINT "FK_expense_menu_target_expense_expense_id" FOREIGN KEY (expense_id) REFERENCES expense (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_expense_menu_target_expense_id_target_type_target_id" ON expense_menu_target (expense_id, target_type, target_id);

CREATE TABLE IF NOT EXISTS expense_header (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    supplier_id integer NOT NULL,
    created_by_id integer NOT NULL,
    deliveryman_id integer,
    total numeric(12,2),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_expense_header" PRIMARY KEY (id),
    CONSTRAINT "FK_expense_header_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_expense_header_supplier_supplier_id" FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_expense_header_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_expense_header_user_deliveryman_id" FOREIGN KEY (deliveryman_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS app (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    bank_id integer NOT NULL,
    name character varying(150) NOT NULL,
    image_url character varying(200),
    active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_app" PRIMARY KEY (id),
    CONSTRAINT "FK_app_bank_bank_id" FOREIGN KEY (bank_id) REFERENCES bank (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS address (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    neighborhood_id integer NOT NULL,
    address character varying(200) NOT NULL,
    additional_info character varying(150),
    delivery_fee integer NOT NULL,
    latitude numeric(10,6),
    longitude numeric(10,6),
    is_primary boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_address" PRIMARY KEY (id),
    CONSTRAINT "FK_address_customer_customer_id" FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE,
    CONSTRAINT "FK_address_neighborhood_neighborhood_id" FOREIGN KEY (neighborhood_id) REFERENCES neighborhood (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS product (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    category_id integer NOT NULL,
    name character varying(150) NOT NULL,
    price integer NOT NULL,
    stock integer,
    weight_grams integer,
    active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_product" PRIMARY KEY (id),
    CONSTRAINT "FK_product_product_category_category_id" FOREIGN KEY (category_id) REFERENCES product_category (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS password_reset_token (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    token character varying(500) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL DEFAULT FALSE,
    used_at timestamp with time zone,
    used_by_ip character varying(45),
    email character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_password_reset_token" PRIMARY KEY (id),
    CONSTRAINT "FK_password_reset_token_user_user_id" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    token character varying(500) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_revoked boolean NOT NULL DEFAULT FALSE,
    revoked_at timestamp with time zone,
    replaced_by_token character varying(500),
    revoked_by_ip character varying(45),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_refresh_token" PRIMARY KEY (id),
    CONSTRAINT "FK_refresh_token_user_user_id" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS expense_bank_payment (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    bank_id integer NOT NULL,
    expense_header_id integer NOT NULL,
    amount numeric(12,2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_expense_bank_payment" PRIMARY KEY (id),
    CONSTRAINT "FK_expense_bank_payment_bank_bank_id" FOREIGN KEY (bank_id) REFERENCES bank (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_expense_bank_payment_expense_header_expense_header_id" FOREIGN KEY (expense_header_id) REFERENCES expense_header (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS expense_detail (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    header_id integer NOT NULL,
    expense_id integer NOT NULL,
    quantity numeric(12,2) NOT NULL DEFAULT 1,
    amount integer NOT NULL,
    total numeric(12,2),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_expense_detail" PRIMARY KEY (id),
    CONSTRAINT "FK_expense_detail_expense_expense_id" FOREIGN KEY (expense_id) REFERENCES expense (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_expense_detail_expense_header_header_id" FOREIGN KEY (header_id) REFERENCES expense_header (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "order" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    taken_by_id integer NOT NULL,
    customer_id integer,
    address_id integer,
    loyalty_cycle_step_id integer,
    loyalty_reward_snapshot character varying(500),
    delivery_man_id integer,
    guestname character varying(100),
    type text NOT NULL DEFAULT 'delivery',
    delivery_fee integer,
    reserved_for timestamp with time zone,
    prepare_at timestamp with time zone,
    prepared_notified_at timestamp with time zone,
    status text NOT NULL,
    status_times jsonb NOT NULL,
    subtotal integer NOT NULL DEFAULT 0,
    total integer NOT NULL DEFAULT 0,
    discount_total integer NOT NULL DEFAULT 0,
    notes character varying(200),
    cancelled_reason character varying(200),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_order" PRIMARY KEY (id),
    CONSTRAINT "FK_order_address_address_id" FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE SET NULL,
    CONSTRAINT "FK_order_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_order_customer_customer_id" FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE SET NULL,
    CONSTRAINT "FK_order_loyalty_cycle_step_loyalty_cycle_step_id" FOREIGN KEY (loyalty_cycle_step_id) REFERENCES loyalty_cycle_step (id) ON DELETE SET NULL,
    CONSTRAINT "FK_order_user_delivery_man_id" FOREIGN KEY (delivery_man_id) REFERENCES "user" (id) ON DELETE SET NULL,
    CONSTRAINT "FK_order_user_taken_by_id" FOREIGN KEY (taken_by_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

-- Rutas de domicilio (SLA, km, tiempos; sin geometría)
CREATE TABLE IF NOT EXISTS delivery_route (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    deliveryman_id integer NOT NULL,
    branch_id integer NOT NULL,
    status text NOT NULL DEFAULT 'open',
    last_assignment_at_utc timestamp with time zone NOT NULL,
    route_started_at_utc timestamp with time zone,
    planned_distance_meters integer,
    return_to_branch_meters integer,
    planned_driving_duration_seconds integer,
    stop_count integer NOT NULL DEFAULT 0,
    complex_access_stop_count integer NOT NULL DEFAULT 0,
    per_order_buffer_seconds integer NOT NULL DEFAULT 240,
    complex_access_buffer_seconds integer NOT NULL DEFAULT 300,
    meta_duration_seconds integer,
    consolidated_at_utc timestamp with time zone,
    completed_at_utc timestamp with time zone,
    actual_duration_seconds integer,
    met_sla boolean,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_delivery_route" PRIMARY KEY (id),
    CONSTRAINT "FK_delivery_route_user_deliveryman_id" FOREIGN KEY (deliveryman_id) REFERENCES "user" (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_delivery_route_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS delivery_route_stop (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    delivery_route_id integer NOT NULL,
    order_id integer NOT NULL,
    stop_sequence integer NOT NULL,
    address_snapshot_text text,
    requires_complex_access_buffer boolean NOT NULL DEFAULT FALSE,
    complex_access_match_term character varying(64),
    complex_access_bonus_seconds integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_delivery_route_stop" PRIMARY KEY (id),
    CONSTRAINT "FK_delivery_route_stop_delivery_route_delivery_route_id" FOREIGN KEY (delivery_route_id) REFERENCES delivery_route (id) ON DELETE CASCADE,
    CONSTRAINT "FK_delivery_route_stop_order_order_id" FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_delivery_route_stop_order" ON delivery_route_stop (order_id);
CREATE INDEX IF NOT EXISTS "idx_delivery_route_stop_route" ON delivery_route_stop (delivery_route_id);
CREATE INDEX IF NOT EXISTS "idx_delivery_route_dm_branch_status" ON delivery_route (deliveryman_id, branch_id, status);

ALTER TABLE "order" ADD COLUMN IF NOT EXISTS delivery_route_id integer NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_order_delivery_route_delivery_route_id'
    ) THEN
        ALTER TABLE "order"
            ADD CONSTRAINT "FK_order_delivery_route_delivery_route_id"
            FOREIGN KEY (delivery_route_id) REFERENCES delivery_route (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_order_delivery_route" ON "order" (delivery_route_id);

ALTER TABLE "order" ADD COLUMN IF NOT EXISTS loyalty_cycle_step_id integer NULL;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS loyalty_reward_snapshot character varying(500) NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_order_loyalty_cycle_step_loyalty_cycle_step_id'
    ) THEN
        ALTER TABLE "order"
            ADD CONSTRAINT "FK_order_loyalty_cycle_step_loyalty_cycle_step_id"
            FOREIGN KEY (loyalty_cycle_step_id) REFERENCES loyalty_cycle_step (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_order_loyalty_cycle_step" ON "order" (loyalty_cycle_step_id);

-- Quitar loyalty_rule legado (migración en instalaciones que aún lo tengan)
ALTER TABLE "order" DROP CONSTRAINT IF EXISTS "FK_order_loyalty_rule_loyalty_rule_id";
DROP INDEX IF EXISTS "IX_order_loyalty_rule_id";
ALTER TABLE "order" DROP COLUMN IF EXISTS loyalty_rule_id;
DROP TABLE IF EXISTS loyalty_rule;

CREATE TABLE IF NOT EXISTS app_payment (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    app_id integer NOT NULL,
    amount numeric NOT NULL,
    is_setted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_app_payment" PRIMARY KEY (id),
    CONSTRAINT "FK_app_payment_app_app_id" FOREIGN KEY (app_id) REFERENCES app (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_app_payment_order_order_id" FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bank_payment (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    bank_id integer NOT NULL,
    amount numeric(12,2) NOT NULL,
    is_verified boolean NOT NULL DEFAULT FALSE,
    verified_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_bank_payment" PRIMARY KEY (id),
    CONSTRAINT "FK_bank_payment_bank_bank_id" FOREIGN KEY (bank_id) REFERENCES bank (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_bank_payment_order_order_id" FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_detail (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_price integer NOT NULL DEFAULT 0,
    discount integer NOT NULL DEFAULT 0,
    subtotal integer,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_order_detail" PRIMARY KEY (id),
    CONSTRAINT "FK_order_detail_order_order_id" FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_order_detail_product_product_id" FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT
);

-- Tabla supplier_expense (AddSupplierExpense)
CREATE TABLE IF NOT EXISTS supplier_expense (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    supplier_id integer NOT NULL,
    expense_id integer NOT NULL,
    usage_count integer NOT NULL DEFAULT 0,
    last_used_at timestamp with time zone,
    last_unit_price numeric(18,2),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_supplier_expense" PRIMARY KEY (id),
    CONSTRAINT "FK_supplier_expense_expense_expense_id" FOREIGN KEY (expense_id) REFERENCES expense (id) ON DELETE CASCADE,
    CONSTRAINT "FK_supplier_expense_supplier_supplier_id" FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE
);

-- Tabla deliveryman_advance (AddDeliverymanAdvanceTable)
CREATE TABLE IF NOT EXISTS deliveryman_advance (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    deliveryman_id integer NOT NULL,
    amount numeric(10,2) NOT NULL CHECK (amount > 0),
    payment_method integer NOT NULL DEFAULT 0,
    bank_id integer,
    expense_header_id integer,
    notes text,
    created_by integer NOT NULL,
    branch_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_deliveryman_advance" PRIMARY KEY (id),
    CONSTRAINT "FK_deliveryman_advance_user_deliveryman_id" FOREIGN KEY (deliveryman_id) REFERENCES "user" (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_deliveryman_advance_user_created_by" FOREIGN KEY (created_by) REFERENCES "user" (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_deliveryman_advance_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_deliveryman_advance_bank_bank_id" FOREIGN KEY (bank_id) REFERENCES bank (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_deliveryman_advance_expense_header_expense_header_id" FOREIGN KEY (expense_header_id) REFERENCES expense_header (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS deliveryman_day_state (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    deliveryman_id integer NOT NULL,
    date date NOT NULL,
    liquidation_mode integer NOT NULL DEFAULT 0,
    blocked boolean NOT NULL DEFAULT false,
    unlocked_at timestamp with time zone,
    unlocked_by_id integer,
    last_liquidation_at_utc timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_deliveryman_day_state" PRIMARY KEY (id),
    CONSTRAINT "uq_deliveryman_day_state_branch_dm_date" UNIQUE (branch_id, deliveryman_id, date),
    CONSTRAINT "FK_deliveryman_day_state_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_deliveryman_day_state_user_deliveryman_id" FOREIGN KEY (deliveryman_id) REFERENCES "user" (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_deliveryman_day_state_user_unlocked_by_id" FOREIGN KEY (unlocked_by_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

-- Tabla bank_transfer (movimientos entre bancos)
CREATE TABLE IF NOT EXISTS bank_transfer (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    from_bank_id integer NOT NULL,
    to_bank_id integer NOT NULL,
    amount numeric(12,2) NOT NULL,
    note character varying(500),
    created_by_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_bank_transfer" PRIMARY KEY (id),
    CONSTRAINT "FK_bank_transfer_bank_from_bank_id" FOREIGN KEY (from_bank_id) REFERENCES bank (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_bank_transfer_bank_to_bank_id" FOREIGN KEY (to_bank_id) REFERENCES bank (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_bank_transfer_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

-- Tabla cash_register_closure (cuadre de caja)
CREATE TABLE IF NOT EXISTS cash_register_closure (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    closed_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    opening_cash numeric(12,2) NOT NULL DEFAULT 0,
    closing_cash numeric(12,2) NOT NULL DEFAULT 0,
    denomination_counts character varying(500) NOT NULL DEFAULT '{}',
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_cash_register_closure" PRIMARY KEY (id),
    CONSTRAINT "FK_cash_register_closure_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_cash_register_closure_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

-- Tabla cash_closure_bank_reconciliation (conciliación por banco en el cuadre)
CREATE TABLE IF NOT EXISTS cash_closure_bank_reconciliation (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cash_closure_id integer NOT NULL,
    bank_id integer NOT NULL,
    expected_balance numeric(12,2) NOT NULL DEFAULT 0,
    actual_balance numeric(12,2) NOT NULL DEFAULT 0,
    adjustments character varying(2000),
    difference numeric(12,2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_cash_closure_bank_reconciliation" PRIMARY KEY (id),
    CONSTRAINT "FK_cash_closure_bank_reconciliation_bank_bank_id" FOREIGN KEY (bank_id) REFERENCES bank (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_cash_closure_bank_reconciliation_cash_register_closure_cash_closure_id" FOREIGN KEY (cash_closure_id) REFERENCES cash_register_closure (id) ON DELETE CASCADE
);

-- Tabla cash_closure_informal_loan (préstamos informales en el cuadre)
CREATE TABLE IF NOT EXISTS cash_closure_informal_loan (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cash_closure_id integer NOT NULL,
    concept character varying(200) NOT NULL,
    amount numeric(12,2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_cash_closure_informal_loan" PRIMARY KEY (id),
    CONSTRAINT "FK_cash_closure_informal_loan_cash_register_closure_cash_closure_id" FOREIGN KEY (cash_closure_id) REFERENCES cash_register_closure (id) ON DELETE CASCADE
);

-- =============================================================================
-- Paridad idempotente con Scripts/deliveryman-liquidation-schema.sql
-- (BD nueva: no-op o duplicados seguros; BD antigua sin migrar: añade columnas/tablas/índices)
-- =============================================================================

-- Branch: coordenadas (evita error SQL "no existe la columna b2.latitude" en joins EF)
ALTER TABLE public.branch
    ADD COLUMN IF NOT EXISTS latitude numeric(10,6) NULL,
    ADD COLUMN IF NOT EXISTS longitude numeric(10,6) NULL;

-- Abonos domiciliario: método de pago, banco, gasto vinculado
ALTER TABLE public.deliveryman_advance
    ADD COLUMN IF NOT EXISTS payment_method integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bank_id integer NULL REFERENCES public.bank (id),
    ADD COLUMN IF NOT EXISTS expense_header_id integer NULL REFERENCES public.expense_header (id);

CREATE INDEX IF NOT EXISTS idx_deliveryman_advance_bank ON public.deliveryman_advance (bank_id);
CREATE INDEX IF NOT EXISTS idx_deliveryman_advance_expense ON public.deliveryman_advance (expense_header_id);

-- Gastos asociados a domiciliario
ALTER TABLE public.expense_header
    ADD COLUMN IF NOT EXISTS deliveryman_id integer NULL REFERENCES public."user" (id);

CREATE INDEX IF NOT EXISTS idx_expense_header_deliveryman ON public.expense_header (deliveryman_id);

-- Nota: deliveryman_day_state ya está creada arriba en este archivo (misma semántica que
-- Scripts/deliveryman-liquidation-schema.sql; allí usa serial, aquí IDENTITY).

-- =============================================================================
-- ÍNDICES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_address_customer ON address (customer_id);
CREATE INDEX IF NOT EXISTS idx_address_neighborhood ON address (neighborhood_id);
CREATE INDEX IF NOT EXISTS "IX_app_bank_id" ON app (bank_id);
CREATE INDEX IF NOT EXISTS "IX_app_payment_app_id" ON app_payment (app_id);
CREATE INDEX IF NOT EXISTS "IX_app_payment_order_id" ON app_payment (order_id);
CREATE INDEX IF NOT EXISTS "IX_bank_branch_id" ON bank (branch_id);
CREATE INDEX IF NOT EXISTS idx_supplier_branch_name ON supplier (branch_id, name);
CREATE INDEX IF NOT EXISTS "IX_bank_payment_bank_id" ON bank_payment (bank_id);
CREATE INDEX IF NOT EXISTS "IX_bank_payment_order_id" ON bank_payment (order_id);
CREATE INDEX IF NOT EXISTS idx_customer_active ON customer (active) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_customer_branch ON customer (branch_id);
CREATE INDEX IF NOT EXISTS idx_customer_phone ON customer (phone1);
CREATE INDEX IF NOT EXISTS "IX_expense_category_id" ON expense (category_id);
CREATE INDEX IF NOT EXISTS "IX_expense_menu_target_expense_id" ON expense_menu_target (expense_id);
CREATE INDEX IF NOT EXISTS idx_expense_header_created_by ON expense_header (created_by_id);
CREATE INDEX IF NOT EXISTS "IX_expense_bank_payment_bank_id" ON expense_bank_payment (bank_id);
CREATE INDEX IF NOT EXISTS "IX_expense_bank_payment_expense_header_id" ON expense_bank_payment (expense_header_id);
CREATE INDEX IF NOT EXISTS idx_expense_detail_header ON expense_detail (header_id);
CREATE INDEX IF NOT EXISTS "IX_expense_detail_expense_id" ON expense_detail (expense_id);
CREATE INDEX IF NOT EXISTS idx_expense_header_branch ON expense_header (branch_id);
CREATE INDEX IF NOT EXISTS idx_expense_header_supplier ON expense_header (supplier_id);
CREATE INDEX IF NOT EXISTS "IX_neighborhood_branch_id" ON neighborhood (branch_id);
CREATE INDEX IF NOT EXISTS idx_order_branch ON "order" (branch_id);
CREATE INDEX IF NOT EXISTS idx_order_customer ON "order" (customer_id);
CREATE INDEX IF NOT EXISTS idx_order_date ON "order" (created_at);
CREATE INDEX IF NOT EXISTS idx_order_delivery_man ON "order" (delivery_man_id);
CREATE INDEX IF NOT EXISTS idx_order_status ON "order" (status);
CREATE INDEX IF NOT EXISTS idx_order_type ON "order" (type);
CREATE INDEX IF NOT EXISTS "IX_order_address_id" ON "order" (address_id);
CREATE INDEX IF NOT EXISTS "IX_order_taken_by_id" ON "order" (taken_by_id);
CREATE INDEX IF NOT EXISTS idx_order_detail_order ON order_detail (order_id);
CREATE INDEX IF NOT EXISTS idx_order_detail_product ON order_detail (product_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_email ON password_reset_token (email);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_expires_at ON password_reset_token (expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_password_reset_token_token ON password_reset_token (token);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_user_id ON password_reset_token (user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_user_used ON password_reset_token (user_id, is_used);
CREATE INDEX IF NOT EXISTS idx_product_active ON product (active) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_product_category ON product (category_id);
CREATE INDEX IF NOT EXISTS "IX_product_category_branch_id" ON product_category (branch_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires_at ON refresh_token (expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_refresh_token_token ON refresh_token (token);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_active ON refresh_token (user_id, is_revoked);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id ON refresh_token (user_id);
CREATE INDEX IF NOT EXISTS idx_user_active ON "user" (active) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_user_branch ON "user" (branch_id);
CREATE INDEX IF NOT EXISTS idx_user_role ON "user" (role);
CREATE INDEX IF NOT EXISTS "IX_supplier_expense_expense_id" ON supplier_expense (expense_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_supplier_expense_supplier_id_expense_id" ON supplier_expense (supplier_id, expense_id);
CREATE INDEX IF NOT EXISTS idx_deliveryman_advance_deliveryman ON deliveryman_advance (deliveryman_id);
CREATE INDEX IF NOT EXISTS idx_deliveryman_advance_created_at ON deliveryman_advance (created_at);
CREATE INDEX IF NOT EXISTS idx_deliveryman_advance_branch ON deliveryman_advance (branch_id);
CREATE INDEX IF NOT EXISTS idx_deliveryman_advance_created_by ON deliveryman_advance (created_by);
CREATE INDEX IF NOT EXISTS idx_deliveryman_advance_bank ON deliveryman_advance (bank_id);
CREATE INDEX IF NOT EXISTS idx_deliveryman_advance_expense ON deliveryman_advance (expense_header_id);
CREATE INDEX IF NOT EXISTS idx_deliveryman_day_state_branch_date ON deliveryman_day_state (branch_id, date);
CREATE INDEX IF NOT EXISTS idx_expense_header_deliveryman ON expense_header (deliveryman_id);
CREATE INDEX IF NOT EXISTS "IX_bank_transfer_from_bank_id" ON bank_transfer (from_bank_id);
CREATE INDEX IF NOT EXISTS "IX_bank_transfer_to_bank_id" ON bank_transfer (to_bank_id);
CREATE INDEX IF NOT EXISTS "IX_bank_transfer_created_by_id" ON bank_transfer (created_by_id);
CREATE INDEX IF NOT EXISTS "IX_cash_register_closure_branch_id" ON cash_register_closure (branch_id);
CREATE INDEX IF NOT EXISTS "IX_cash_register_closure_created_by_id" ON cash_register_closure (created_by_id);
CREATE INDEX IF NOT EXISTS "IX_cash_closure_bank_reconciliation_bank_id" ON cash_closure_bank_reconciliation (bank_id);
CREATE INDEX IF NOT EXISTS "IX_cash_closure_bank_reconciliation_cash_closure_id" ON cash_closure_bank_reconciliation (cash_closure_id);
CREATE INDEX IF NOT EXISTS "IX_cash_closure_informal_loan_cash_closure_id" ON cash_closure_informal_loan (cash_closure_id);

-- =============================================================================
-- FUNCIONES
-- =============================================================================

CREATE OR REPLACE FUNCTION public.calculate_expense_detail_total() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.total = NEW.quantity * NEW.amount;
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.calculate_order_detail_subtotal() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.subtotal = (NEW.quantity * NEW.unit_price) - COALESCE(NEW.discount, 0);
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.update_expense_header_total() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    header_total INTEGER;
    target_header_id INTEGER;
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_header_id = OLD.header_id;
    ELSE
        target_header_id = NEW.header_id;
    END IF;

    SELECT COALESCE(SUM(total), 0) INTO header_total
    FROM expense_detail WHERE header_id = target_header_id;

    UPDATE expense_header SET total = header_total, updated_at = NOW() WHERE id = target_header_id;

    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END; $$;

CREATE OR REPLACE FUNCTION public.update_order_total_on_delivery_fee_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.delivery_fee IS DISTINCT FROM NEW.delivery_fee THEN
        NEW.total = NEW.subtotal + COALESCE(NEW.delivery_fee, 0);
    END IF;
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.update_order_totals() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    order_subtotal INTEGER;
    order_discount_total INTEGER;
    order_delivery_fee INTEGER;
    target_order_id INTEGER;
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_order_id = OLD.order_id;
    ELSE
        target_order_id = NEW.order_id;
    END IF;

    SELECT COALESCE(SUM(subtotal), 0) INTO order_subtotal FROM order_detail WHERE order_id = target_order_id;
    SELECT COALESCE(SUM(discount), 0) INTO order_discount_total FROM order_detail WHERE order_id = target_order_id;
    SELECT COALESCE(delivery_fee, 0) INTO order_delivery_fee FROM "order" WHERE id = target_order_id;

    UPDATE "order" SET
        subtotal = order_subtotal,
        discount_total = order_discount_total,
        total = order_subtotal + order_delivery_fee,
        updated_at = NOW()
    WHERE id = target_order_id;

    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END; $$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.update_bank_payment_verified_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.is_verified = true AND (OLD.is_verified = false OR OLD.is_verified IS NULL) THEN
        NEW.verified_at := NOW();
    ELSIF NEW.is_verified = false AND OLD.is_verified = true THEN
        NEW.verified_at := NULL;
    END IF;
    RETURN NEW;
END; $$;

-- =============================================================================
-- TRIGGERS
-- =============================================================================

DROP TRIGGER IF EXISTS calculate_expense_detail_total_trigger ON public.expense_detail;
CREATE TRIGGER calculate_expense_detail_total_trigger BEFORE INSERT OR UPDATE ON public.expense_detail FOR EACH ROW EXECUTE FUNCTION public.calculate_expense_detail_total();

DROP TRIGGER IF EXISTS update_expense_header_total_on_detail_insert ON public.expense_detail;
CREATE TRIGGER update_expense_header_total_on_detail_insert AFTER INSERT ON public.expense_detail FOR EACH ROW EXECUTE FUNCTION public.update_expense_header_total();

DROP TRIGGER IF EXISTS update_expense_header_total_on_detail_update ON public.expense_detail;
CREATE TRIGGER update_expense_header_total_on_detail_update AFTER UPDATE ON public.expense_detail FOR EACH ROW EXECUTE FUNCTION public.update_expense_header_total();

DROP TRIGGER IF EXISTS update_expense_header_total_on_detail_delete ON public.expense_detail;
CREATE TRIGGER update_expense_header_total_on_detail_delete AFTER DELETE ON public.expense_detail FOR EACH ROW EXECUTE FUNCTION public.update_expense_header_total();

DROP TRIGGER IF EXISTS calculate_order_detail_subtotal_trigger ON public.order_detail;
CREATE TRIGGER calculate_order_detail_subtotal_trigger BEFORE INSERT OR UPDATE ON public.order_detail FOR EACH ROW EXECUTE FUNCTION public.calculate_order_detail_subtotal();

DROP TRIGGER IF EXISTS update_order_totals_on_detail_insert ON public.order_detail;
CREATE TRIGGER update_order_totals_on_detail_insert AFTER INSERT ON public.order_detail FOR EACH ROW EXECUTE FUNCTION public.update_order_totals();

DROP TRIGGER IF EXISTS update_order_totals_on_detail_update ON public.order_detail;
CREATE TRIGGER update_order_totals_on_detail_update AFTER UPDATE ON public.order_detail FOR EACH ROW EXECUTE FUNCTION public.update_order_totals();

DROP TRIGGER IF EXISTS update_order_totals_on_detail_delete ON public.order_detail;
CREATE TRIGGER update_order_totals_on_detail_delete AFTER DELETE ON public.order_detail FOR EACH ROW EXECUTE FUNCTION public.update_order_totals();

DROP TRIGGER IF EXISTS update_order_total_on_delivery_fee_change_trigger ON public."order";
CREATE TRIGGER update_order_total_on_delivery_fee_change_trigger BEFORE UPDATE ON public."order" FOR EACH ROW EXECUTE FUNCTION public.update_order_total_on_delivery_fee_change();

DROP TRIGGER IF EXISTS update_order_updated_at ON public."order";
CREATE TRIGGER update_order_updated_at BEFORE UPDATE ON public."order" FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS trigger_bank_payment_verified_at ON public.bank_payment;
CREATE TRIGGER trigger_bank_payment_verified_at BEFORE UPDATE ON public.bank_payment FOR EACH ROW EXECUTE FUNCTION public.update_bank_payment_verified_at();

DROP TRIGGER IF EXISTS update_address_updated_at ON public.address;
CREATE TRIGGER update_address_updated_at BEFORE UPDATE ON public.address FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_branch_updated_at ON public.branch;
CREATE TRIGGER update_branch_updated_at BEFORE UPDATE ON public.branch FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_customer_updated_at ON public.customer;
CREATE TRIGGER update_customer_updated_at BEFORE UPDATE ON public.customer FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_neighborhood_updated_at ON public.neighborhood;
CREATE TRIGGER update_neighborhood_updated_at BEFORE UPDATE ON public.neighborhood FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_order_detail_updated_at ON public.order_detail;
CREATE TRIGGER update_order_detail_updated_at BEFORE UPDATE ON public.order_detail FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_password_reset_token_updated_at ON public.password_reset_token;
CREATE TRIGGER update_password_reset_token_updated_at BEFORE UPDATE ON public.password_reset_token FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_product_category_updated_at ON public.product_category;
CREATE TRIGGER update_product_category_updated_at BEFORE UPDATE ON public.product_category FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_product_updated_at ON public.product;
CREATE TRIGGER update_product_updated_at BEFORE UPDATE ON public.product FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_refresh_token_updated_at ON public.refresh_token;
CREATE TRIGGER update_refresh_token_updated_at BEFORE UPDATE ON public.refresh_token FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_updated_at ON public."user";
CREATE TRIGGER update_user_updated_at BEFORE UPDATE ON public."user" FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS trigger_deliveryman_advance_updated_at ON public.deliveryman_advance;
CREATE TRIGGER trigger_deliveryman_advance_updated_at BEFORE UPDATE ON public.deliveryman_advance FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_expense_header_updated_at ON public.expense_header;
CREATE TRIGGER update_expense_header_updated_at BEFORE UPDATE ON public.expense_header FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_supplier_expense_updated_at ON public.supplier_expense;
CREATE TRIGGER update_supplier_expense_updated_at BEFORE UPDATE ON public.supplier_expense FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_expense_menu_target_updated_at ON public.expense_menu_target;
CREATE TRIGGER update_expense_menu_target_updated_at BEFORE UPDATE ON public.expense_menu_target FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- =============================================================================
-- DATOS SEMILLA
-- =============================================================================

DO $$
DECLARE
    branch_id_var INTEGER;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM branch WHERE name = 'Santander') THEN
        INSERT INTO branch (name, address, phone1, phone2) VALUES ('Santander', 'calle 108a # 77d-30', '0000000000', NULL);
    END IF;
    SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
    IF branch_id_var IS NULL THEN RETURN; END IF;
    IF EXISTS (SELECT 1 FROM "user" LIMIT 1) THEN RETURN; END IF;  -- Ya hay datos, no duplicar

    INSERT INTO "user" (branch_id, role, name, email, phone, password_hash, active)
    VALUES
        (branch_id_var, 'superadmin', 'Santiago', 'santyvano@outlook.com', '0000000000', '$2a$11$5ERmxaaUoW.MLkirB/l22eyaZxF1OCK2kjtN9DtYo14k.o2XmkyBy', true),
        (branch_id_var, 'admin', 'Daniel Alvarez', 'daniel@daniel.com', '3125486596', '$2a$12$FR0XMK.2RulbbSgH5un0Uu8fZ/KcfXMZdGtng4N8jIiaxe/nbkanS', true),
        (branch_id_var, 'deliveryman', 'Abelardo', 'abelardo@abelardo.com', '3226474857', '$2a$12$QRFDuTrE7HfTefR5syYkV.6JQ62bGYheR56Qhs9TCuhAVzr0FnGGy', true),
        (branch_id_var, 'deliveryman', 'Maikol Martinez Serna', 'maikol@maikol.com', '3021563245', '$2a$12$9wl/bOW4736yr3ssYHweUekgRch7RnafYTKHo2RVKcUH1kYJlSVbG', true),
        (branch_id_var, 'kitchen', 'juan', 'juan@juan.com', '3256325695', '$2a$12$oPImGwKsmXYVhlY1spD3ROyNZXDGchLNnIYl9B97KY1Sok9Cb6Wna', true);

    INSERT INTO neighborhood (branch_id, name, delivery_fee)
    SELECT branch_id_var, n, f FROM (VALUES ('Castilla',3000),('Santander',4000),('Pedregal',2500),('Florencia',3500),('Picacho',5000)) AS v(n,f)
    WHERE NOT EXISTS (SELECT 1 FROM neighborhood WHERE branch_id = branch_id_var LIMIT 1);

    IF NOT EXISTS (SELECT 1 FROM bank WHERE branch_id = branch_id_var AND type = 0 LIMIT 1) THEN
        INSERT INTO bank (branch_id, name, image_url, active, type) VALUES (branch_id_var, 'Bancolombia', NULL, true, 0);
    END IF;
    -- Segundo banco principal: Nequi
    IF NOT EXISTS (SELECT 1 FROM bank WHERE branch_id = branch_id_var AND name = 'Nequi' LIMIT 1) THEN
        INSERT INTO bank (branch_id, name, image_url, active, type) VALUES (branch_id_var, 'Nequi', NULL, true, 0);
    END IF;
    -- Bancos vault (ocultos, solo visibles para admin/superadmin)
    IF NOT EXISTS (SELECT 1 FROM bank WHERE branch_id = branch_id_var AND type = 1 LIMIT 1) THEN
        INSERT INTO bank (branch_id, name, image_url, active, type) VALUES (branch_id_var, 'Caja Mayor Efectivo', NULL, true, 1);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM bank WHERE branch_id = branch_id_var AND type = 2 LIMIT 1) THEN
        INSERT INTO bank (branch_id, name, image_url, active, type) VALUES (branch_id_var, 'Caja Mayor Banco', NULL, true, 2);
    END IF;
END $$;

DO $$
DECLARE branch_id_var INTEGER; bank_id_var INTEGER;
BEGIN
    SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
    SELECT id INTO bank_id_var FROM bank WHERE name = 'Bancolombia' AND branch_id = branch_id_var LIMIT 1;
    IF bank_id_var IS NOT NULL AND NOT EXISTS (SELECT 1 FROM app WHERE bank_id = bank_id_var AND name = 'Didi') THEN
        INSERT INTO app (bank_id, name, image_url, active) VALUES (bank_id_var, 'Didi', NULL, true);
    END IF;
END $$;

-- Ciclo de fidelidad (45 pasos por sucursal, idempotente)
INSERT INTO loyalty_cycle_step (branch_id, step_index, reward_label)
SELECT b.id, v.step_idx, v.lbl
FROM branch b
CROSS JOIN (
    VALUES
        (1, 'Domicilio gratis 3k'),
        (2, '5% descuento'),
        (3, 'Yucas gratis'),
        (4, '10% descuento'),
        (5, 'bebida gratis'),
        (6, '15% de descuento'),
        (7, 'Ad costilla bbq gratis'),
        (8, '20% descuento'),
        (9, 'bebida gratis'),
        (10, '25% descuento'),
        (11, 'chicharron gratis'),
        (12, '30% descuento'),
        (13, 'yuca gratis'),
        (14, 'papas gratis'),
        (15, 'bebida gratis'),
        (16, '50% descuento'),
        (17, 'yuca gratis'),
        (18, 'papas gratis'),
        (19, 'bebida gratis'),
        (20, '100% descuento'),
        (21, '5% descuento'),
        (22, 'yuca gratis'),
        (23, '10% descuento'),
        (24, 'papas gratis'),
        (25, 'bebida gratis'),
        (26, '15% de descuento'),
        (27, 'chuleta pollo gratis'),
        (28, '20% descuento'),
        (29, 'chuleta cerdo gratis'),
        (30, 'chicharron gratis'),
        (31, '25% descuento'),
        (32, 'costilla gratis'),
        (33, 'yuca gratis'),
        (34, 'papas gratis'),
        (35, 'bebida gratis'),
        (36, '50% descuento'),
        (37, 'yuca gratis'),
        (38, 'papas gratis'),
        (39, 'bebida gratis'),
        (40, '100% descuento'),
        (41, '5% descuento'),
        (42, 'yuca gratis'),
        (43, '10% descuento'),
        (44, 'papas gratis'),
        (45, 'bebida gratis')
) AS v(step_idx, lbl)
WHERE NOT EXISTS (
    SELECT 1 FROM loyalty_cycle_step s WHERE s.branch_id = b.id AND s.step_index = v.step_idx
);

DO $$
DECLARE
    branch_id_var INTEGER;
    paisa_cat_id INTEGER;
    ranchero_cat_id INTEGER;
    carbonara_cat_id INTEGER;
    ropa_vieja_cat_id INTEGER;
    ropa_vieja_chich_cat_id INTEGER;
    paisa_chich_cat_id INTEGER;
    combos_cat_id INTEGER;
    adiciones_cat_id INTEGER;
    gaseosas_cat_id INTEGER;
    vegetariano_cat_id INTEGER;
BEGIN
    SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
    IF branch_id_var IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO product_category (branch_id, name)
    VALUES
        (branch_id_var, 'Paisa'),
        (branch_id_var, 'Ranchero'),
        (branch_id_var, 'Carbonara'),
        (branch_id_var, 'Ropa Vieja'),
        (branch_id_var, 'Ropa Vieja Chich'),
        (branch_id_var, 'Paisa Chich'),
        (branch_id_var, 'Combos'),
        (branch_id_var, 'Adiciones'),
        (branch_id_var, 'Gaseosas'),
        (branch_id_var, 'Vegetariano')
    ON CONFLICT DO NOTHING;

    SELECT id INTO paisa_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Paisa' LIMIT 1;
    SELECT id INTO ranchero_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Ranchero' LIMIT 1;
    SELECT id INTO carbonara_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Carbonara' LIMIT 1;
    SELECT id INTO ropa_vieja_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Ropa Vieja' LIMIT 1;
    SELECT id INTO ropa_vieja_chich_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Ropa Vieja Chich' LIMIT 1;
    SELECT id INTO paisa_chich_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Paisa Chich' LIMIT 1;
    SELECT id INTO combos_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Combos' LIMIT 1;
    SELECT id INTO adiciones_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Adiciones' LIMIT 1;
    SELECT id INTO gaseosas_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Gaseosas' LIMIT 1;
    SELECT id INTO vegetariano_cat_id FROM product_category WHERE branch_id = branch_id_var AND name = 'Vegetariano' LIMIT 1;

    -- Arroz Ropa Vieja con Chicharrón
    INSERT INTO product (category_id, name, price, stock, active)
    SELECT ropa_vieja_chich_cat_id, n, p, 100, true
    FROM (VALUES
        ('Arroz ropa vieja con chicharrón Personal', 21000),
        ('Arroz ropa vieja con chicharrón Dúo',      37000),
        ('Arroz ropa vieja con chicharrón Trío',     50000),
        ('Arroz ropa vieja con chicharrón Familiar', 66000),
        ('Arroz ropa vieja con chicharrón Súper',    84000)
    ) AS v(n, p);

    -- Arroz Paisa con Chicharrón
    INSERT INTO product (category_id, name, price, stock, active)
    SELECT paisa_chich_cat_id, n, p, 100, true
    FROM (VALUES
        ('Arroz paisa con chicharrón Personal', 20000),
        ('Arroz paisa con chicharrón Dúo',      35000),
        ('Arroz paisa con chicharrón Trío',     45000),
        ('Arroz paisa con chicharrón Familiar', 61000),
        ('Arroz paisa con chicharrón Súper',    77000)
    ) AS v(n, p);

    -- Arroz Carbonara
    INSERT INTO product (category_id, name, price, stock, active)
    SELECT carbonara_cat_id, n, p, 100, true
    FROM (VALUES
        ('Arroz carbonara Personal', 19000),
        ('Arroz carbonara Dúo',      33000),
        ('Arroz carbonara Trío',     44000),
        ('Arroz carbonara Familiar', 58000),
        ('Arroz carbonara Súper',    73000)
    ) AS v(n, p);

    -- Arroz Ropa Vieja
    INSERT INTO product (category_id, name, price, stock, active)
    SELECT ropa_vieja_cat_id, n, p, 100, true
    FROM (VALUES
        ('Arroz ropa vieja Personal', 19000),
        ('Arroz ropa vieja Dúo',      33000),
        ('Arroz ropa vieja Trío',     44000),
        ('Arroz ropa vieja Familiar', 58000),
        ('Arroz ropa vieja Súper',    73000)
    ) AS v(n, p);

    -- Arroz Ranchero
    INSERT INTO product (category_id, name, price, stock, active)
    SELECT ranchero_cat_id, n, p, 100, true
    FROM (VALUES
        ('Arroz ranchero Personal', 18000),
        ('Arroz ranchero Dúo',      31000),
        ('Arroz ranchero Trío',     40000),
        ('Arroz ranchero Familiar', 53000),
        ('Arroz ranchero Súper',    66000)
    ) AS v(n, p);

    -- Arroz Paisa
    INSERT INTO product (category_id, name, price, stock, active)
    SELECT paisa_cat_id, n, p, 100, true
    FROM (VALUES
        ('Arroz paisa Personal', 18000),
        ('Arroz paisa Dúo',      31000),
        ('Arroz paisa Trío',     40000),
        ('Arroz paisa Familiar', 53000),
        ('Arroz paisa Súper',    66000)
    ) AS v(n, p);

    -- Arroz Vegetariano
    INSERT INTO product (category_id, name, price, stock, active)
    SELECT vegetariano_cat_id, n, p, 100, true
    FROM (VALUES
        ('Arroz vegetariano Personal', 15000),
        ('Arroz vegetariano Dúo',      22000),
        ('Arroz vegetariano Trío',     28000),
        ('Arroz vegetariano Familiar', 33000),
        ('Arroz vegetariano Súper',    39000)
    ) AS v(n, p);

    -- Combos
    INSERT INTO product (category_id, name, price, stock, active)
    VALUES
        (combos_cat_id, 'Combochicharrón', 25000, 100, true),
        (combos_cat_id, 'Costicombo',      25000, 100, true);

    -- Adiciones
    INSERT INTO product (category_id, name, price, stock, active)
    VALUES
        (adiciones_cat_id, 'Trocitos de chicharrón',         12000, 100, true),
        (adiciones_cat_id, 'Chicharrón 250 gr',              12000, 100, true),
        (adiciones_cat_id, 'Costilla BBQ 500 gr',            15000, 100, true),
        (adiciones_cat_id, 'Yuca x5 unidades',                5000, 100, true),
        (adiciones_cat_id, 'Yuca x10 unidades',              10000, 100, true),
        (adiciones_cat_id, 'Papas a la francesa 250 gr',      5000, 100, true),
        (adiciones_cat_id, 'Papas a la francesa 500 gr',     10000, 100, true);

    -- Gaseosas 1.5L (todas a 7000)
    INSERT INTO product (category_id, name, price, stock, active)
    VALUES
        (gaseosas_cat_id, 'CocaCola 1.5L', 7000, 100, true),
        (gaseosas_cat_id, 'Premio 1.5L',   7000, 100, true),
        (gaseosas_cat_id, 'Quatro 1.5L',   7000, 100, true),
        (gaseosas_cat_id, 'Sprite 1.5L',   7000, 100, true);

    -- Gaseosas 3L
    INSERT INTO product (category_id, name, price, stock, active)
    VALUES
        (gaseosas_cat_id, 'CocaCola 3L', 12000, 100, true),
        (gaseosas_cat_id, 'Quatro 3L',   11000, 100, true);

    -- Gaseosas PET 400 ml (todas a 3500)
    INSERT INTO product (category_id, name, price, stock, active)
    VALUES
        (gaseosas_cat_id, 'CocaCola PET 400', 3500, 100, true),
        (gaseosas_cat_id, 'Premio PET 400',   3500, 100, true),
        (gaseosas_cat_id, 'Quatro PET 400',   3500, 100, true),
        (gaseosas_cat_id, 'Sprite PET 400',   3500, 100, true);
END $$;

DO $$
DECLARE
    branch_id_var INTEGER; castilla_id INTEGER; santander_id INTEGER; pedregal_id INTEGER; florencia_id INTEGER; picacho_id INTEGER;
    c1 INTEGER; c2 INTEGER; c3 INTEGER; c4 INTEGER; c5 INTEGER; c6 INTEGER; c7 INTEGER; c8 INTEGER;
BEGIN
    SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
    SELECT id INTO castilla_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Castilla' LIMIT 1;
    SELECT id INTO santander_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Santander' LIMIT 1;
    SELECT id INTO pedregal_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Pedregal' LIMIT 1;
    SELECT id INTO florencia_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Florencia' LIMIT 1;
    SELECT id INTO picacho_id FROM neighborhood WHERE branch_id = branch_id_var AND name = 'Picacho' LIMIT 1;

    INSERT INTO customer (branch_id, name, phone1, phone2, active) VALUES (branch_id_var, 'Maria Gonzalez', '3001234567', NULL, true) RETURNING id INTO c1;
    IF c1 IS NOT NULL AND castilla_id IS NOT NULL THEN INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary) VALUES (c1, castilla_id, 'Calle 65 #45-20, Castilla', NULL, 3000, 6.2810, -75.5710, true); END IF;

    INSERT INTO customer (branch_id, name, phone1, phone2, active) VALUES (branch_id_var, 'Carlos Ramirez', '3102345678', NULL, true) RETURNING id INTO c2;
    IF c2 IS NOT NULL AND santander_id IS NOT NULL THEN INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary) VALUES (c2, santander_id, 'Carrera 50 #30-15, Santander', NULL, 4000, 6.2910, -75.5610, true); END IF;

    INSERT INTO customer (branch_id, name, phone1, phone2, active) VALUES (branch_id_var, 'Ana Martinez', '3203456789', NULL, true) RETURNING id INTO c3;
    IF c3 IS NOT NULL AND pedregal_id IS NOT NULL THEN INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary) VALUES (c3, pedregal_id, 'Calle 70 #55-30, Pedregal', NULL, 2500, 6.3010, -75.5510, true); END IF;

    INSERT INTO customer (branch_id, name, phone1, phone2, active) VALUES (branch_id_var, 'Luis Perez', '3154567890', NULL, true) RETURNING id INTO c4;
    IF c4 IS NOT NULL AND florencia_id IS NOT NULL THEN INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary) VALUES (c4, florencia_id, 'Carrera 45 #25-10, Florencia', NULL, 3500, 6.2710, -75.5810, true); END IF;

    INSERT INTO customer (branch_id, name, phone1, phone2, active) VALUES (branch_id_var, 'Sofia Rodriguez', '3005678901', NULL, true) RETURNING id INTO c5;
    IF c5 IS NOT NULL AND picacho_id IS NOT NULL THEN INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary) VALUES (c5, picacho_id, 'Calle 80 #60-40, Picacho', NULL, 5000, 6.3110, -75.5410, true); END IF;

    INSERT INTO customer (branch_id, name, phone1, phone2, active) VALUES (branch_id_var, 'Diego Torres', '3106789012', NULL, true) RETURNING id INTO c6;
    IF c6 IS NOT NULL AND castilla_id IS NOT NULL THEN INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary) VALUES (c6, castilla_id, 'Carrera 55 #35-25, Castilla', NULL, 3000, 6.2820, -75.5720, true); END IF;

    INSERT INTO customer (branch_id, name, phone1, phone2, active) VALUES (branch_id_var, 'Laura Sanchez', '3207890123', NULL, true) RETURNING id INTO c7;
    IF c7 IS NOT NULL AND santander_id IS NOT NULL THEN INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary) VALUES (c7, santander_id, 'Calle 75 #50-35, Santander', NULL, 4000, 6.2920, -75.5620, true); END IF;

    INSERT INTO customer (branch_id, name, phone1, phone2, active) VALUES (branch_id_var, 'Andres Lopez', '3158901234', NULL, true) RETURNING id INTO c8;
    IF c8 IS NOT NULL AND pedregal_id IS NOT NULL THEN INSERT INTO address (customer_id, neighborhood_id, address, additional_info, delivery_fee, latitude, longitude, is_primary) VALUES (c8, pedregal_id, 'Carrera 60 #40-20, Pedregal', NULL, 2500, 6.3020, -75.5520, true); END IF;
END $$;

-- Proveedor por defecto (necesario para expense_header; branch_id ya existe)
DO $$
DECLARE branch_id_var INTEGER;
BEGIN
    SELECT id INTO branch_id_var FROM branch WHERE name = 'Santander' LIMIT 1;
    IF branch_id_var IS NOT NULL AND NOT EXISTS (SELECT 1 FROM supplier WHERE branch_id = branch_id_var) THEN
        INSERT INTO supplier (branch_id, name, phone, address, email) VALUES (branch_id_var, 'Proveedor General', '0000000000', 'N/A', 'proveedor@local.com');
    END IF;
END $$;

-- =============================================================================
-- REGISTRO DE MIGRACIONES (para que EF Core no las vuelva a ejecutar)
-- =============================================================================

-- Sin migraciones EF — esquema completo gestionado por este script.

-- =============================================================================
-- TABLA: reservation_deposit
-- =============================================================================
CREATE TABLE IF NOT EXISTS reservation_deposit (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    branch_id integer NOT NULL,
    amount numeric(18,2) NOT NULL,
    is_effective boolean NOT NULL DEFAULT false,
    bank_id integer,
    app_id integer,
    received_at timestamp with time zone NOT NULL,
    received_by_id integer NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_reservation_deposit" PRIMARY KEY (id),
    CONSTRAINT "FK_reservation_deposit_order" FOREIGN KEY (order_id) REFERENCES "order"(id) ON DELETE RESTRICT,
    CONSTRAINT "FK_reservation_deposit_branch" FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE RESTRICT,
    CONSTRAINT "FK_reservation_deposit_bank" FOREIGN KEY (bank_id) REFERENCES bank(id) ON DELETE RESTRICT,
    CONSTRAINT "FK_reservation_deposit_app" FOREIGN KEY (app_id) REFERENCES app(id) ON DELETE RESTRICT,
    CONSTRAINT "FK_reservation_deposit_user" FOREIGN KEY (received_by_id) REFERENCES "user"(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_reservation_deposit_order_id" ON reservation_deposit(order_id);
CREATE INDEX IF NOT EXISTS "IX_reservation_deposit_branch_id" ON reservation_deposit(branch_id);
CREATE INDEX IF NOT EXISTS "IX_reservation_deposit_received_at" ON reservation_deposit(received_at);

-- =============================================================================
-- TABLAS: branch_print_settings, print_job (comandas térmicas / agente local)
-- =============================================================================
CREATE TABLE IF NOT EXISTS branch_print_settings (
    branch_id integer NOT NULL,
    kitchen_header_line1 character varying(80),
    kitchen_header_line2 character varying(80),
    show_kitchen_order_number boolean NOT NULL DEFAULT true,
    show_kitchen_time boolean NOT NULL DEFAULT true,
    show_kitchen_notes boolean NOT NULL DEFAULT true,
    delivery_show_line_subtotals boolean NOT NULL DEFAULT true,
    delivery_show_payments boolean NOT NULL DEFAULT true,
    delivery_show_loyalty_footer boolean NOT NULL DEFAULT true,
    cashier_mirror_delivery_layout boolean NOT NULL DEFAULT false,
    footer_message_kitchen character varying(200),
    footer_message_delivery character varying(200),
    footer_message_cashier character varying(200),
    paper_width_mm smallint NOT NULL DEFAULT 58,
    paper_width_mm_kitchen smallint NOT NULL DEFAULT 58,
    paper_width_mm_delivery smallint NOT NULL DEFAULT 58,
    paper_width_mm_cashier smallint NOT NULL DEFAULT 58,
    enable_kitchen_jobs boolean NOT NULL DEFAULT true,
    enable_delivery_jobs boolean NOT NULL DEFAULT true,
    enable_cashier_jobs boolean NOT NULL DEFAULT false,
    agent_token_hash character varying(128) NOT NULL DEFAULT '',
    agent_token_salt character varying(64) NOT NULL DEFAULT '',
    agent_token_updated_at timestamp with time zone,
    printer_queue_kitchen character varying(128),
    printer_queue_delivery character varying(128),
    printer_queue_cashier character varying(128),
    receipt_logo_path character varying(500),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_branch_print_settings" PRIMARY KEY (branch_id),
    CONSTRAINT "FK_branch_print_settings_branch" FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS print_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    branch_id integer NOT NULL,
    kind character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    order_ids_json jsonb NOT NULL,
    payload_json jsonb NOT NULL,
    payload_version smallint NOT NULL DEFAULT 1,
    error_message character varying(500),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    CONSTRAINT "PK_print_job" PRIMARY KEY (id),
    CONSTRAINT "FK_print_job_branch" FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE CASCADE,
    CONSTRAINT "CK_print_job_kind" CHECK (kind IN ('kitchen','delivery','cashier')),
    CONSTRAINT "CK_print_job_status" CHECK (status IN ('pending','processing','done','failed'))
);

CREATE INDEX IF NOT EXISTS "IX_print_job_branch_pending"
    ON print_job (branch_id, created_at)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS "IX_print_job_branch_processing"
    ON print_job (branch_id, started_at)
    WHERE status = 'processing';

INSERT INTO branch_print_settings (branch_id)
SELECT b.id FROM branch b
WHERE NOT EXISTS (SELECT 1 FROM branch_print_settings s WHERE s.branch_id = b.id)
ON CONFLICT (branch_id) DO NOTHING;

-- =============================================================================
-- Alter idempotente (bases creadas antes de business_name / nit / logo)
-- =============================================================================
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'branch' AND column_name = 'tax_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'branch' AND column_name = 'nit'
    ) THEN
        ALTER TABLE branch RENAME COLUMN tax_id TO nit;
    END IF;
END $$;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS business_name character varying(150);
ALTER TABLE branch ADD COLUMN IF NOT EXISTS nit character varying(32);
ALTER TABLE branch_print_settings ADD COLUMN IF NOT EXISTS receipt_logo_path character varying(500);

-- Anchos de papel por cola (cocina / domicilio / caja)
ALTER TABLE branch_print_settings ADD COLUMN IF NOT EXISTS paper_width_mm_kitchen smallint;
ALTER TABLE branch_print_settings ADD COLUMN IF NOT EXISTS paper_width_mm_delivery smallint;
ALTER TABLE branch_print_settings ADD COLUMN IF NOT EXISTS paper_width_mm_cashier smallint;

UPDATE branch_print_settings SET
    paper_width_mm_kitchen = COALESCE(paper_width_mm_kitchen, paper_width_mm),
    paper_width_mm_delivery = COALESCE(paper_width_mm_delivery, paper_width_mm),
    paper_width_mm_cashier = COALESCE(paper_width_mm_cashier, paper_width_mm)
WHERE paper_width_mm_kitchen IS NULL
   OR paper_width_mm_delivery IS NULL
   OR paper_width_mm_cashier IS NULL;

ALTER TABLE branch_print_settings ALTER COLUMN paper_width_mm_kitchen SET NOT NULL;
ALTER TABLE branch_print_settings ALTER COLUMN paper_width_mm_kitchen SET DEFAULT 58;
ALTER TABLE branch_print_settings ALTER COLUMN paper_width_mm_delivery SET NOT NULL;
ALTER TABLE branch_print_settings ALTER COLUMN paper_width_mm_delivery SET DEFAULT 58;
ALTER TABLE branch_print_settings ALTER COLUMN paper_width_mm_cashier SET NOT NULL;
ALTER TABLE branch_print_settings ALTER COLUMN paper_width_mm_cashier SET DEFAULT 58;

UPDATE branch_print_settings SET paper_width_mm = paper_width_mm_kitchen WHERE paper_width_mm <> paper_width_mm_kitchen;
