-- Rutas de domicilio (SLA, métricas Google opcionales, buffers torre/bloque/unidad).
-- Idempotente. Ejecutar en Railway, por ejemplo:
--   psql "$DATABASE_URL" -f railway-delivery-route-schema.sql

CREATE TABLE IF NOT EXISTS delivery_route (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    deliveryman_id integer NOT NULL,
    branch_id integer NOT NULL,
    status text NOT NULL DEFAULT 'open',
    last_assignment_at_utc timestamp with time zone NOT NULL,
    route_started_at_utc timestamp with time zone,
    planned_distance_meters integer,
    return_to_branch_meters integer,
    planned_driving_duration_seconds integer,
    stop_count integer NOT NULL DEFAULT 0,
    complex_access_stop_count integer NOT NULL DEFAULT 0,
    per_order_buffer_seconds integer NOT NULL DEFAULT 240,
    complex_access_buffer_seconds integer NOT NULL DEFAULT 300,
    meta_duration_seconds integer,
    consolidated_at_utc timestamp with time zone,
    completed_at_utc timestamp with time zone,
    actual_duration_seconds integer,
    met_sla boolean,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_delivery_route" PRIMARY KEY (id),
    CONSTRAINT "FK_delivery_route_user_deliveryman_id" FOREIGN KEY (deliveryman_id) REFERENCES "user" (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_delivery_route_branch_branch_id" FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS delivery_route_stop (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    delivery_route_id integer NOT NULL,
    order_id integer NOT NULL,
    stop_sequence integer NOT NULL,
    address_snapshot_text text,
    requires_complex_access_buffer boolean NOT NULL DEFAULT FALSE,
    complex_access_match_term character varying(64),
    complex_access_bonus_seconds integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_delivery_route_stop" PRIMARY KEY (id),
    CONSTRAINT "FK_delivery_route_stop_delivery_route_delivery_route_id" FOREIGN KEY (delivery_route_id) REFERENCES delivery_route (id) ON DELETE CASCADE,
    CONSTRAINT "FK_delivery_route_stop_order_order_id" FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_delivery_route_stop_order" ON delivery_route_stop (order_id);
CREATE INDEX IF NOT EXISTS "idx_delivery_route_stop_route" ON delivery_route_stop (delivery_route_id);
CREATE INDEX IF NOT EXISTS "idx_delivery_route_dm_branch_status" ON delivery_route (deliveryman_id, branch_id, status);

ALTER TABLE "order" ADD COLUMN IF NOT EXISTS delivery_route_id integer NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_order_delivery_route_delivery_route_id'
    ) THEN
        ALTER TABLE "order"
            ADD CONSTRAINT "FK_order_delivery_route_delivery_route_id"
            FOREIGN KEY (delivery_route_id) REFERENCES delivery_route (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_order_delivery_route" ON "order" (delivery_route_id);

ALTER TABLE delivery_route
    ADD COLUMN IF NOT EXISTS return_to_branch_meters integer NULL;
