using System.Text.Json;
namespace SenorArroz.Application.Common.Models;
public record AiChatMessage(string Role, string? Content, string? ToolCallId = null, IReadOnlyList<AiToolCall>? ToolCalls = null);
public record AiToolDefinition(string Name, string Description, JsonElement ParametersSchema);
public record AiToolCall(string Id, string Name, JsonElement Arguments);
public record AiChatRequest(string Model, string ApiKey, IReadOnlyList<AiChatMessage> Messages, IReadOnlyList<AiToolDefinition> Tools, double? Temperature);
public record AiChatResponse(string? Text, IReadOnlyList<AiToolCall> ToolCalls, string Model, string? FinishReason, int? InputTokens, int? OutputTokens, bool IsTransientError = false, string? Error = null);
public record AgentToolExecutionContext(int ConversationId, int BranchId);
public record AgentToolExecutionResult(bool Success, object? Data, string? Error = null);
public record WhatsAppAiProcessingResult(bool Processed, bool Ignored, string? IgnoreReason, bool ResponseSent, bool TransferredToHuman, string? Provider, string? Model, int ModelCalls, int ToolsExecuted, string? Error);
